### ISSUE TITLE
pub tells me that there is no `appengine` `0.3.0` but there is

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1]
I hope it's ok to create the issue here instead of http://dartbug.com?

```yaml
dependencies:
  appengine: '>=0.3.0 <0.4.0'
```
or 
```yaml
dependencies:
  appengine: ^0.3.0
```
```
 (v1service_mock) $ pub upgrade
Resolving dependencies... (4.5s) 
Package appengine has no versions that match >=0.3.0 <0.4.0 derived from:
- bwu_datastore_connection depends on version >=0.3.0 <0.4.0
```
https://pub.dartlang.org/packages/appengine

when I change the constraint to `^0.2.0` I get
```
Package gcloud has no versions that match >=0.1.0 <0.2.0 derived from:
- appengine 0.2.2 depends on version >=0.1.0 <0.2.0
```

full `pubspec.yaml`
```yaml
name: bwu_datastore_connection
version: 0.0.1
author: Günter Zöchbauer <guenter@gzoechbauer.com>
publish-to: none
environment:
  sdk: ">=1.8.0-dev.3.0 <2.0.0"

dependencies:
  appengine: '>=0.3.0 <0.4.0'
  fixnum: ^0.9.1
  googleapis_auth: ^0.2.3
  googleapis_beta: ^0.14.0
  http: ^0.11.0
  logging: ^0.11.0
  logging_handlers: ^0.8.0
  protobuf: ^0.3.6
  quiver_log: ^1.0.3
  shelf: ^0.6.0
  uuid: ^0.5.0

dev_dependencies:
  bwu_datastore_launcher:
    path: ../bwu_datastore_launcher
  bwu_utils_dev:
    path: ../bwu_utils_dev
  dart_style: ^0.1.8
  grinder: ^0.7.1+3
  linter: ^0.0.2+3
  test: ^0.12.2
```
