### ISSUE TITLE
Add `path` option to git dependencies

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1305]
Today you can do:

``` yaml
dependencies:
  my_package:
    git:
      ref: my_branch
      url: https://github.com/username/repo_name.git
```

It is assumed the path lives at the root of the repo. I propose an additional `path` option, which allows you to specify a path to the root of the package inside the specified repo.
