### ISSUE TITLE
Conflict name with your app name and a dependencies name

### ISSUE THREAD

**Issue by Kleak** [dart-lang/pub#1337]
Hi,
Today i have tried flutter with some pain, due to my stupid mind ;)
I have created a project and name it test because it is a test, after that we need to import sky.
So we have this beautiful pubspec.yaml :

```yaml
name: test
description: A minimal Sky project.
version: 0.0.1
dependencies:
  sky: any
  sky_tools: any
```

now i need to get my dependencies so let go for :

```shell
pub get
```

And now you don't have the latest version of sky, instead you have the 0.0.34 version (pretty old)
So lets put a hard coded version number in the pubspec.yaml somethings like :

```yaml
name: test
description: A minimal Sky project.
version: 0.0.1
dependencies:
  sky: 0.0.51
  sky_tools: any
```

now 

```shell
pub get
```

and what happen :

```shell
Package sky_tools has no versions that match >=0.0.15 <0.1.0 derived from:
- sky 0.0.51 depends on version ^0.0.15
- test depends on version any
```

My question is : Is there a possibility to have a better error message ?
Or somethings else :)
