### ISSUE TITLE
`pub build` tries to build all dependencies

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/pub#1341]
It seems that `pub build` always pre-compiles every dependency in pubspec. But since some projects has both a front and back end, some dependencies can't be built (i.e. native-ext, I believe is the issue).

I want to build `web/main.dart` with no imports, but since my server side depends on the package `libffi6_extension`, I get the following error message:

```
[Error from Dart2JS]:
file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart: Exception: Cannot read file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart because it is outside of the build environment.
[Info from Dart2JS]:
Took 0:00:01.636863 to compile app|web/main.dart.
Build failed.
```

I don't think this is a problem with `libffi6_extension`, but I might be wrong.

**Comment by zoechi** [comment]
https://www.dartlang.org/tools/pub/assets-and-transformers.html#excluding-assets

**Comment by emilniklas** [comment]
@zoechi How would I use that to exclude a dependency? This does nothing:

```yaml
transformers:
  - $dart2js:
      $exclude: packages/libffi6_extension
```

**Comment by emilniklas** [comment]
Got it! I had to do:

```yaml
transformers:
  - $dart2js
      $include: '**/*.dart'
```

**Comment by emilniklas** [comment]
Actually, no. It didn't work. It did like once, and now it fails again.. Strange!

**Comment by zoechi** [comment]
Where is the entry point of your "server side"?

Try

```yaml
- $dart2js:
    $exclude: bin
```

**Comment by emilniklas** [comment]
Even when having this:

```yaml
transformers:
- $dart2js:
    $exclude:
    - config
    - storage
    - tool
    - lib/app
    - lib/main
    - lib/service_providers
    - lib/templates
    - lib/app.dart
    - lib/migrations.dart
    - lib/services.dart
    $include:
    - web/main.dart
    - lib/client.dart
    - lib/app_client
    - lib/app_shared
```

Excluding everything not client specific and including everything client specific, it still tries to incorporate the `libffi6_extension` somehow. Oh, and main.dart looks like this:

```dart
main() {}
```

**Comment by zoechi** [comment]
Where is your server entry point. It is usually in `bin`? You haven't excluded `bin`.

**Comment by emilniklas** [comment]
There is no bin folder. My entry point is a file in root called `bridge`. Including that doesn't help either

**Comment by zoechi** [comment]
Is this a typo? I thought you want to **exclude** it or is `bridge` not your server side entry point?. 
> entry point in root called "bridge"
  
is weird. Is it a Dart file? Server entry points have to be in `bin` by `pub` convention.

**Comment by emilniklas** [comment]
I'm sorry, I was unclear.

The real server side entry point is in a package, so to start the server and such we just need a startup file. For aesthetical reasons (it's nice to write `dart bridge`), this file doesn't have an extension. In production, the startup file would be something like `bin/server.dart`. 

And "Including that doesn't help either" was my bad, I meant "Including that file in `$exclude` doesn't help either"

**Comment by emilniklas** [comment]
And, before you ask: If I change `bridge` to `bin/bridge.dart` and `$exclude` `bin`, it still doesn't work

**Comment by zoechi** [comment]
Ok, I'm almost out of questions ;-) but one: Can you provide a github repo with a project that allows to reproduce the problem.

**Comment by emilniklas** [comment]
Already did ;)

https://github.com/dart-bridge/bridge

**Comment by emilniklas** [comment]
@zoechi You'll have to clone the `develop` branch, btw

**Comment by zoechi** [comment]
It's the default branch anyway.
What does
> I want to build web/main.dart **with no imports**

actually mean?
Does your code in `web/main.dart` actually import the `libffi*` stuff (transitively) but you want `pub build` to ignore these imports?

I don't get any error when I run `pub build`

>  (develop) $ pub build
Loading source assets... 
Loading libffi6_extension and unsafe_extension transformers... 
Building app... Setup libffi6_extension.so.
Already installed binary 'compiled/X86_64/linux/libffi6_extension.so'
The setup successful.
Building app... Setup libunsafe_extension.so.
Already installed binary 'compiled/X86_64/linux/libunsafe_extension.so'
The setup successful.
Building app... (1.6s) 
Built 39 files to "build".

There also is no `index.html` in the `web` directory. How is that supposed to work?

**Comment by emilniklas** [comment]
> What does "I want to build web/main.dart with no imports" actually mean?

Of course I want main.dart to have imports at some point, but just to make sure that the file _didn't_ import the extension (transitively or otherwise), i made a completely empty file (except for a main method).

> I don't get any error when I run `pub build`

I just now created a temporary fix for this issue, so the pubspec now excludes all dart files:

```yaml
# Temporary (https://github.com/dart-lang/pub/issues/1341)
transformers:
- $dart2js:
    $exclude: web/**.dart
```

Just remove that piece of code and rerun `pub build` and you'll see the issue, I'm sure.

> There also is no `index.html` in the `web` directory. How is that supposed to work?

The HTML is being generated on the server side.
