### ISSUE TITLE
Pub: Expected a key while parsing a block mapping. path:

### ISSUE THREAD

**Issue by madsager** [dart-lang/pub#1347]
_From @Gen8 on October 21, 2015 10:22_

My pubspec.yaml contains this:

```
name: Name1
version: 2015.10.20
dependencies:
  test: ">=0.0.0"
  Name2: ">=0.0.0"
    path: ../Name2-2015-10-21
```

And I get this error:

```
Error on line 6, column 5 of pubspec.yaml: Expected a key while parsing a block mapping.
    path: ../tenum-2015-09-28
    ^
```

I get no error if I remove the version constraint for the Name2 package:

```
name: Name1
version: 2015.10.20
dependencies:
  test: ">=0.0.0"
  Name2:
    path: ../Name2-2015-10-21
```

_Copied from original issue: dart-lang/sdk#24663_
