### ISSUE TITLE
pub build fails – Could not find asset web_components|lib/README.md.

### ISSUE THREAD

**Issue by madsager** [dart-lang/pub#1354]
_From @davenotik on October 27, 2015 17:3_

```
ERR : Could not find asset web_components|lib/README.md.
FINE: Exception type: AssetNotFoundException
ERR : package:pub/src/barback/pub_package_provider.dart 112   PubPackageProvider._assertExists
    | package:pub/src/barback/pub_package_provider.dart 106   PubPackageProvider.getAsset.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Completer.completeError
    | package:pub/src/barback/pub_package_provider.dart 111   PubPackageProvider.getAsset.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              Future.Future.microtask
    | package:pub/src/barback/pub_package_provider.dart       PubPackageProvider.getAsset
    | ===== asynchronous gap ===========================
    | dart:async                                              Stream.toList
    | package:barback/src/graph/static_asset_cascade.dart 46  StaticAssetCascade.availableOutputs
    | package:barback/src/graph/package_graph.dart 178        PackageGraph.getAllAssets.<fn>
    | dart:async                                              Future.wait
    | package:barback/src/graph/package_graph.dart 177        PackageGraph.getAllAssets
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets.<fn>
    | dart:async                                              _BroadcastStreamController.add
    | package:barback/src/graph/package_graph.dart 266        PackageGraph._tryScheduleResult.<fn>
    | package:barback/src/utils.dart 241                      newFuture.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets.<fn>
    | dart:async                                              _BroadcastStreamController.add
    | package:barback/src/graph/package_graph.dart 266        PackageGraph._tryScheduleResult.<fn>
    | package:barback/src/utils.dart 241                      newFuture.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:barback/src/graph/package_graph.dart 161        PackageGraph.getAllAssets
    | package:barback/src/barback.dart 106                    Barback.getAllAssets
    | package:pub/src/command/build.dart 97                   BuildCommand.onRunTransformerCommand.<async>.<fn>.<fn>.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:pub/src/command/build.dart 95                   BuildCommand.onRunTransformerCommand.<async>.<fn>.<fn>
    | package:pub/src/log.dart 393                            progress
    | package:pub/src/command/build.dart 89                   BuildCommand.onRunTransformerCommand.<async>.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                              _Future.then
    | package:pub/src/command/build.dart 67                   BuildCommand.onRunTransformerCommand.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                              Future.Future.microtask
    | package:pub/src/command/build.dart                      BuildCommand.onRunTransformerCommand
    | package:pub/src/command/barback.dart 58                 BarbackCommand.run
    | package:args/command_runner.dart 178                    CommandRunner.runCommand.<fn>
    | dart:async                                              Future.Future.sync
    | package:args/command_runner.dart 131                    CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130                 PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                              Future.Future.sync
    | package:pub/src/utils.dart 103                          captureErrors.<fn>
    | package:stack_trace                                     Chain.capture
    | package:pub/src/utils.dart 117                          captureErrors
    | package:pub/src/command_runner.dart 130                 PubCommandRunner.runCommand.<async>
---- End log transcript ----
```

This is after I overrode the webcomponents dependency in my pubspec.yaml as a possible solution to Polymer not working on Safari. See: http://stackoverflow.com/questions/33361258/polymer-app-wont-load-in-safari-pre-1-0?noredirect=1

_Copied from original issue: dart-lang/sdk#24741_

**Comment by nex3** [comment]
What version of pub are you using? What's the contents of your `pubspec.lock`?

**Comment by davenotik** [comment]
Pub 1.12.1

```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description: analyzer
    source: hosted
    version: "0.22.4"
  args:
    description: args
    source: hosted
    version: "0.12.2+6"
  async:
    description: async
    source: hosted
    version: "1.3.0"
  barback:
    description: barback
    source: hosted
    version: "0.15.2+7"
  browser:
    description: browser
    source: hosted
    version: "0.10.0+2"
  charcode:
    description: charcode
    source: hosted
    version: "1.1.0"
  cli_util:
    description: cli_util
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description: code_transformers
    source: hosted
    version: "0.2.9+3"
  collection:
    description: collection
    source: hosted
    version: "1.1.3"
  core_elements:
    description: core_elements
    source: hosted
    version: "0.6.1+2"
  crypto:
    description: crypto
    source: hosted
    version: "0.9.1"
  csslib:
    description: csslib
    source: hosted
    version: "0.12.1"
  custom_element_apigen:
    description: custom_element_apigen
    source: hosted
    version: "0.1.7+1"
  dart_style:
    description: dart_style
    source: hosted
    version: "0.1.3"
  emoji:
    description: emoji
    source: hosted
    version: "1.1.2"
  firebase:
    description: firebase
    source: hosted
    version: "0.6.4"
  glob:
    description: glob
    source: hosted
    version: "1.0.5"
  googleapis:
    description: googleapis
    source: hosted
    version: "0.1.1"
  googleapis_auth:
    description: googleapis_auth
    source: hosted
    version: "0.2.3+1"
  html:
    description: html
    source: hosted
    version: "0.12.2"
  html5lib:
    description: html5lib
    source: hosted
    version: "0.12.1"
  http:
    description: http
    source: hosted
    version: "0.11.3+2"
  http_parser:
    description: http_parser
    source: hosted
    version: "1.0.0"
  http_server:
    description: http_server
    source: hosted
    version: "0.9.5+1"
  initialize:
    description: initialize
    source: hosted
    version: "0.6.1+2"
  intl:
    description: intl
    source: hosted
    version: "0.12.4+2"
  jwt:
    description: jwt
    source: hosted
    version: "0.1.4"
  logging:
    description: logging
    source: hosted
    version: "0.9.3"
  matcher:
    description: matcher
    source: hosted
    version: "0.11.4+4"
  meta:
    description: meta
    source: hosted
    version: "0.8.8"
  mime:
    description: mime
    source: hosted
    version: "0.9.3"
  mustache:
    description: mustache
    source: hosted
    version: "0.1.8"
  notification:
    description: notification
    source: hosted
    version: "0.0.1"
  observe:
    description: observe
    source: hosted
    version: "0.13.1+2"
  paper_elements:
    description: paper_elements
    source: hosted
    version: "0.6.2+3"
  path:
    description: path
    source: hosted
    version: "1.3.6"
  petitparser:
    description: petitparser
    source: hosted
    version: "1.5.0"
  polymer:
    description: polymer
    source: hosted
    version: "0.16.3+3"
  polymer_expressions:
    description: polymer_expressions
    source: hosted
    version: "0.13.1"
  polymer_interop:
    description: polymer_interop
    source: hosted
    version: "0.1.1"
  pool:
    description: pool
    source: hosted
    version: "1.2.0"
  query_string:
    description: query_string
    source: hosted
    version: "1.0.4"
  quiver:
    description: quiver
    source: hosted
    version: "0.20.0"
  route:
    description: route
    source: hosted
    version: "0.4.6"
  shelf:
    description: shelf
    source: hosted
    version: "0.6.3+1"
  shelf_cors:
    description: shelf_cors
    source: hosted
    version: "0.2.1"
  shelf_static:
    description: shelf_static
    source: hosted
    version: "0.2.3+1"
  smoke:
    description: smoke
    source: hosted
    version: "0.2.1+1"
  source_maps:
    description: source_maps
    source: hosted
    version: "0.10.1"
  source_span:
    description: source_span
    source: hosted
    version: "1.2.1"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.4.2"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.4"
  template_binding:
    description: template_binding
    source: hosted
    version: "0.14.0+2"
  uri:
    description: uri
    source: hosted
    version: "0.9.5"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+2"
  watcher:
    description: watcher
    source: hosted
    version: "0.9.7"
  web_components:
    description: web_components
    source: hosted
    version: "0.12.0+3"
  when:
    description: when
    source: hosted
    version: "0.2.0"
  which:
    description: which
    source: hosted
    version: "0.1.3"
  yaml:
    description: yaml
    source: hosted
    version: "2.1.7"
```

I believe this is after I did the web_components override in pubspec.yaml:

```
dependency_overrides:
  web_components: "^0.12.0+3"
```
