### ISSUE TITLE
pub get produces an empty lockfile on a malformed pubspec

### ISSUE THREAD

**Issue by munificent** [dart-lang/pub#1361]
Create this pubspec:

```yaml
name: <%= package %>
version: 0.0.1
```

Run pub get. It crashes:

```
Resolving dependencies...
Got dependencies!
Invalid argument(s): "<%= package %>" is not a valid package name
package:package_config/packages_file.dart 108  write.<fn>
dart:collection                                _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach
package:package_config/packages_file.dart 105  write
package:pub/src/lock_file.dart 172             LockFile.packagesFile
package:pub/src/entrypoint.dart 192            Entrypoint.acquireDependencies.<async>
This is an unexpected error. Please run

    pub --trace get

and include the results in a bug report on http://dartbug.com/new.
```

And also produces a lock file:

```
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages: {}
```

It produces a `packages` directory but it's empty (not even a self link). It doesn't produce a `.packages` file.

What it should do is gracefully detect the bad name and fail early without producing a lock file or `packages` directory.

**Comment by scheglov** [comment]
Please note, that the `pubspec.yaml` sometimes more complex than that.
For example it may reference other packages.
I'm sorry that I did not provide the full contents initially.

```
name: <%= package %>
version: 0.0.1
description: Material Design Lite '<%= templatename %>'
author: <<%= name %>> <<%= email %>>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl: '>=1.0.0 <2.0.0'

  logging: any
  logging_handlers: any
  console_log_handler: any

  di: any

transformers:
  - di
```
