### ISSUE TITLE
Support release/debug overrides for transformer settings

### ISSUE THREAD

**Issue by ochafik** [dart-lang/pub#1363]
I would be _great_ if we could have different behaviour for all transformers in debug vs. release (see similar request for Angular2: angular/angular#5379, and [existing feature in dart-scissors](https://github.com/google/dart-scissors#defaults-vs-debug-vs-release)).

Proposal: `$debug` and `$release` subsections, and union semantics to reconcile with the default settings.

``` yaml
transformers:
- $dart2js:
    $debug:
        environment:
            COMPILATION_MODE: debug
        commandLineOptions:
            - --disable-type-inference
            - --trust-type-annotations
            - --trust-primitives
            - --fast-startup # unless this makes the compilation slower
    $release:
        environment:
            COMPILATION_MODE: release
        commandLineOptions:
            - --dump-info
    commandLineOptions: [...] # options common to both debug and release
```

(initial request for `$dart2js` transformer: https://github.com/dart-lang/sdk/issues/24951)
