### ISSUE TITLE
pub get/upgrade fails to deal with dependencies from git repos

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/pub#1368]
I use dependences from git repos with a following entry in `pubspec.yaml`.
```
  xtra:
    git: git@github.com:dynaxis/xtra.git
    version: any
```
I get the following error when `pub get` or `pub upgrade` for the entry.
```
C:\...\>pub get
Resolving dependencies...
Error on line 18, column 10 of pubspec.yaml: Invalid description: Illegal scheme
 character
    git: git@github.com:dynaxis/xtra.git
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
It is broken since 1.14.0-dev.5.0. Was ok even in dev.4.0.

**Comment by dynaxis** [comment]
I guess it is related to https://github.com/dart-lang/pub/commit/a69f0c9c1f1cbc029969ae0fba9a8bc6cdedf467.

**Comment by travissanderson-wf** [comment]
Seeing a similar thing, our github dependencies are defined like so:
```
internal_dart_library:
    git:
      url: git@github.com:Workiva/internal_dart_library.git
      ref: 0.0.12
```
