### ISSUE TITLE
Apparent infinite loop in `pub upgrade`

### ISSUE THREAD

**Issue by eernstg** [dart-lang/pub#1371]
The following setup causes `pub upgrade` to loop (at least, it's not finished if you start it in the evening and check it out the next morning):

```
# ---------- FILE client/pubspec.yaml ----------
name: client
version: 0.0.1
dependencies:
  service:
    path: ../service
  analyzer: ^0.27.0

# ---------- FILE service/pubspec.yaml ----------
name: service
version: 0.0.1
dependencies:
  charted: ^0.3.0
  polymer: ^0.16.3
```

How to reproduce: `mkdir client service`, create the above-mentioned files in there, `cd client`, `pub upgrade` (or `downgrade`, or `get`, all three commands behave similarly here).

Expected outcome: The command terminates (it might succeed or it might declare a version conflict, but it shouldn't loop).

Actual outcome: It loops.

Note that it will terminate if the line containing 'charted' is removed.
