### ISSUE TITLE
"pub get" failing for git repositories when run from Windows with git version 2.5.3.windows.1

### ISSUE THREAD

**Issue by sgerhardt** [dart-lang/pub#1372]
Setup:
OS: Windows 8 64 bit
Git: git version 2.5.3.windows.1
Dart SDK: 1.13
IDE: WebStorm 11.0.2

Issue:
"pub get" failing for git repositories when run from Windows with git version 2.5.3.windows.1. This happens when ".git" is not added to the line specifying the git repository location.

Expected Operation:
I believe the expected behavior is for it to work with or without the ".git" at the end of the line specifying the repository.

When I try to do a "pub get" on the following .yaml for example:

    name: unittest_v1
    description: A sample command-line application
    dependencies:
      dartlero:
        git: https://github.com/dzenanr/dartlero
      test: any

I get the following output error, `C:\tools\dart-sdk\bin\pub.bat get
Resolving dependencies...
Git error. Command: git fetch
fatal: Not a git repository (or any of the parent directories): .git
Process finished with exit code 1`

It appears that simply making the git line, "`git: https://github.com/dzenanr/dartlero.git` (adding .git to the end)" fixes the issue. I've run the same command on OS X on yaml without the ".git" with success using a different version of git. 
![image](https://cloud.githubusercontent.com/assets/4251684/11987055/02ebeeee-a99e-11e5-8d54-f403856ae89d.png)

**Comment by Andersmholmgren** [comment]
I also get an error on git dependencies but I'm on a mac and the output is different

```
 pub get --trace
Resolving dependencies... 
Error on line 14, column 7 of pubspec.yaml: Invalid description: Illegal scheme character
      url: git@bitbucket.org:andersmholmgren/hateoas_models.git
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
---- Log transcript ----
FINE: Pub 1.14.0-dev.5.0
FINE: Resolving dependencies finished (0.0s).
ERR : Error on line 14, column 7 of pubspec.yaml: Invalid description: Illegal scheme character
    |       url: git@bitbucket.org:andersmholmgren/hateoas_models.git
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FINE: Exception type: PubspecException
FINE: package:pub/src/pubspec.dart 573                     Pubspec._error
    | package:pub/src/pubspec.dart 559                     Pubspec._wrapFormatException
    | package:pub/src/pubspec.dart 499                     Pubspec._parseDependencies.<fn>
    | dart:collection                                      MapView.forEach
    | package:pub/src/pubspec.dart 450                     Pubspec._parseDependencies
    | package:pub/src/pubspec.dart 114                     Pubspec.dependencies
    | package:pub/src/package.dart 53                      Package.dependencies
    | package:pub/src/solver/backtracking_solver.dart 619  BacktrackingSolver._logParameters
    | package:pub/src/solver/backtracking_solver.dart 155  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _Completer.completeError
    | package:pub/src/solver/backtracking_solver.dart 201  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
    | package:pub/src/log.dart 393                         progress
    | package:pub/src/solver/version_solver.dart 38        resolveVersions
    | package:pub/src/entrypoint.dart 158                  Entrypoint.acquireDependencies.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 30                  GetCommand.run
    | package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
    | dart:async                                           Future.Future.sync
    | package:args/command_runner.dart 131                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/utils.dart 111                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 125                       captureErrors
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>
---- End log transcript ----
```

It works with 1.13.1 though

```
description: A library useful for applications or for sharing on pub.dartlang.org.
name: frentity
version: 1.4.7
dependencies: 
  built_collection: '^1.0.0'
  frappe: '^0.4.0+2'
  logging: '>=0.9.2'
  observe: '^0.13.1'
  option: '>=0.3.3 <2.0.0'
  quiver: '^0.21.0'
  uri: '>=0.9.5'
  hateoas_models:
    git: 
      url: git@bitbucket.org:andersmholmgren/hateoas_models.git
      ref: aac65e3b864f64dc62785c12d982ff752c917c0d
  stuff:
    git: 
      url: git@bitbucket.org:andersmholmgren/stuff.git
      ref: 15f054476b69d88fc6a8a2566d30f2b351f98b57
dependency_overrides:
dev_dependencies: 
  guinness: '^0.1.17'
  mockito: '>=0.10.0 <0.11.0'
  test: '^0.12.0'
environment: 
  sdk: '>=1.9.0 <2.0.0'
```
