### ISSUE TITLE
pub build/serve uses over 4 GiB RAM on a project with JS dependencies

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub#1395]
_From @akdor1154 on January 27, 2016 0:25_

Hi,
I have a project that is mixed AngularJS and Polymer Dart. My own JS is entirely contained in web/angular/lib, and has JS dependencies in web/angular/jspm_packages, managed by the JSPM package manager (this is similar to bower). jspm_packages then has many thousands of small JS files that are built and minified into a single JS file independently from Dart, and my Polymer entry point index.html only contains a <link> to the final built js file.
However, it seems pub doesn't really care, and is choking on the amount of JS in my project. It uses over 4 GiB of RAM to do a build or serve, or 10GiB if I try to build with -v (separate issue?). This means I am unable to build on my webserver, which is a pain in the neck. Serving with or without dart2js is also very, very slow to start (about three minutes), though once it's initialized the continuous rebuild system works adequately to make things bearable.
I have tried removing Polymer entirely to ensure it's not the Polymer transformers causing issues.

Long term, is there any reason Dart needs so much RAM? Even in 'dumb mode' (i.e. blindly copying every existent JS file in the project) I can't see why so much memory should be needed for what should be a simple copy or hardlink operation.
Short term, is there any way to get pub build to just ignore a specified directory? I have tried the $exclude directive under the dart2js transformer in pubspec.yaml but it doesn't reduce memory usage at all. Reading past github issues, it looks like .gitignore used to be parsed as a hacky exclude list, but this functionality has been removed. I have tried using Dart 1.13 Stable and the latest 1.14 Unstable from the official apt repository.

Cheers
Jarrad

_Copied from original issue: dart-lang/sdk#25591_

**Comment by anders-sandholm** [comment]
_From @kevmoo on February 1, 2016 22:3_

@akdor1154 By "js dependencies" do you mean using the new JS facades in Dart 1.13?

**Comment by anders-sandholm** [comment]
_From @akdor1154 on February 1, 2016 23:25_

No, structure wise I have built my page as a standard Polymer Dart 0.5 SPA, with a single div designated as an angular JS root element, and angular included from a normal script tag and bootstrapped in the standard fashion. I only use Dart:JS for its jsify functions; all communication is done with CustomEvents on Window.
By JS dependencies I mean things like Angular itself, the Angular Material library, etc. These are built and minified into a single JS file as is standard for JS projects, but the original sources for these appear to be what is causing headaches for pub.

**Comment by anders-sandholm** [comment]
_From @kevmoo on February 2, 2016 16:48_

Could you include your `pubspec.yaml` contents in the bug?

**Comment by anders-sandholm** [comment]
_From @sigmundch on February 4, 2016 23:56_

This could be a pub issue, a transformer issue, or a dart2js issue.

It doesn't sound like this is directly a dart2js issue, but just in case try excluding everything from dart2js and tell us if that makes a difference. You can do this by using `$include: []` (basically include nothing).

Some transformers in polymer might be trying to process the js files too, so another thing to try is to include/exclude directories there as well.

/cc @nex3 (for pub) @jakemac53 (for polymer 0.5 transformers)

**Comment by anders-sandholm** [comment]
@akdor1154 , not sure if you were able to try any of @sigmundch 's suggestions?

**Comment by anders-sandholm** [comment]
_From @akdor1154 on February 26, 2016 0:6_

sorry, I missed the notifications. I'll check it at work on Monday. One thing I found that does fix it is removing all `packages` directories and running all instantiations of `pub` with `--no-symlink-packages`.

**Comment by anders-sandholm** [comment]
_From @akdor1154 on February 26, 2016 0:8_

pubspec:
```
name: chopper
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.9.0-dev.7.1 <2.0.0'
dependencies:
  crypto: any
  observe: any
  core_elements: any
  paper_elements: any
  polymer: '>0.16.0'                                                                                                                
  vector_math: any                                                                                                                  
transformers:                                                                                                                       
- polymer:                                                                                                                          
    entry_points: web/index.html                                                                                                    
    inject_build_logs_in_output: false                                                                                              
    $exclude: ["web/angular"]                                                                                                       
- $dart2js:                                                                                                                         
    $exclude: ["web/angular"]
```

**Comment by anders-sandholm** [comment]
_From @akdor1154 on February 26, 2016 0:12_

(just realized I have remote access to work, so can test now)
If I run a blind `pub get` to re-add those packages directories, then excluding everything from `transformers` does not help, unfortunately. :(
relevant section of pubspec:
```
transformers:
- polymer:
    entry_points: web/index.html
    inject_build_logs_in_output: false
    $include: []
- $dart2js:
    $include: []
```
