### ISSUE TITLE
Dart pub wants to install alpha version

### ISSUE THREAD

**Issue by jrote1** [dart-lang/pub#1403]
in my pubspec.yaml I have the following version constraint. But it wants to install an alpha version this should not happen

`analyzer: '>=0.24.4 <0.28.0'`

```
Resolving dependencies...
analyzer 0.27.3-alpha.7
```

**Comment by zoechi** [comment]
Can't reproduce. 

With this `pubspec.yaml`
```yaml
name: xxx
dependencies:
  analyzer: '>=0.24.4 <0.28.0'
```

It prints (beside others)

> + analyzer 0.27.2 (0.27.3-alpha.7 available)

Which means `0.27.2` was added to `pubspec.lock` and informs that a newer version (0.27.3-alpha.7) is available.
