### ISSUE TITLE
Unable to spawn isolate on pub get with angular2 and polymer

### ISSUE THREAD

**Issue by ilikerobots** [dart-lang/pub#1410]
_From @ilikerobots on April 21, 2016 8:21_

As of polymer 1.0.0-rc.16, when running pub get I receive the error

```
ERR : Unable to spawn isolate: Unhandled exception:
    | Could not import "package:crypto/crypto.dart" from "package:protobuf/protobuf.dart": Failure getting http://localhost:39400/packages/crypto/crypto.dart:
    |   404 Not Found
```
 
for the following pubspec 

```
name: angular_polymer_test
environment:
  sdk: '1.15.0'
dependencies:
  polymer: '1.0.0-rc.16'
  angular2: '2.0.0-beta.15'
```

I'm not sure if the issue is here or angular2, but i note the problem seems to exist in all angular2 2.0.0 betas and only appears >= polymer rc 16.

_Copied from original issue: dart-lang/polymer-dart#694_
