### ISSUE TITLE
Class 'AppEnginePackageMemcache' has no instance method '_packageUIKey' with matching arguments.

### ISSUE THREAD

**Issue by soloproyectos** [dart-lang/pub#1424]
I get the following error when trying to publish a new package:

```text
Looks great! Are you ready to upload your package (y/n)? y
Uploading... (4.0s) 
Class 'AppEnginePackageMemcache' has no instance method '_packageUIKey' with matching arguments.

NoSuchMethodError: incorrect number of arguments passed to method named '_packageUIKey'
Receiver: Instance of 'AppEnginePackageMemcache'
Tried calling: _packageUIKey("domnode")
Found: _packageUIKey(package, version).
```

**More info:**
Pub 1.16.0
Dart VM version: 1.16.0 (Tue Apr 26 14:18:21 2016) on "linux_x64"
Xubuntu 16.04

**Comment by zoechi** [comment]
Can you post your `pubspec.yaml`?

**Comment by soloproyectos** [comment]
No problem:

```yaml
name: axis_mobile
description: Axistools for mobile devices
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  ng2_strap: ^0.0.6+1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.3+7
  domquery: ^1.1.3
  sass: ^0.4.2
transformers:
- sass:
    compass: true
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    entry_points:
    - 'web/index.dart'
- dart_to_js_script_rewriter
```
