### ISSUE TITLE
Blow up if a pubspec has two identical dependencies defined

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1459]
Context https://github.com/dart-lang/http_parser/pull/7

```yaml
name: http_parser
dependencies:
  string_scanner: ">=0.0.0 <0.2.0"
  string_scanner: ">=0.0.0 <2.0.0"
```

This should be illegal
