### ISSUE TITLE
Version solver should skip versions with unparseable pubspecs

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1479]
_From @stephan-gruen on December 1, 2016 11:2_

sdk 1.21.0-dev.11.0
Windows 7 / WebStorm 2016.3.1
All works well with the stable sdk version 1.20.1, but I'm not able to use the latest dev sdk version (I tryed 9 and 11) anymore, because pub throws "Duplicate mapping key" if polymer_elements are used.

Not really sure if this is a sdk or a pub error or what to do or update to solve it.

Pub:
```
Working dir: C:\Users\Stephan\dart\Angular2\test
D:\dart\dartium-1.21.0-dev.11.0\dart-sdk\bin\pub.bat get
Resolving dependencies...
Error on line 198, column 1 of ..\..\..\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\polymer_elements-1.0.0-rc.9\pubspec.yaml: Duplicate mapping key.
environment:
^^^^^^^^^^^
Process finished with exit code 65
```
yaml:
```
name: test
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.1.1
  angular2_components: ^0.2.0
  browser: ^0.10.0
  polymer: ^1.0.0-rc.18
  polymer_elements: ^1.0.0-rc.9
  web_components: ^0.12.0
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- polymer:
    entry_points: web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
```
If you do not specify a version for polymer_elements pub will simply get the first version:
```
Working dir: C:\Users\Stephan\dart\Angular2\test
D:\dart\dartium-1.21.0-dev.11.0\dart-sdk\bin\pub.bat get
Resolving dependencies...
+ polymer_elements 0.0.2 (0.3.0 available)
Changed 1 dependency!
Process finished with exit code 0
```

_Copied from original issue: dart-lang/sdk#27956_
