### ISSUE TITLE
piping to `pub global activated` or `pub run` doesn't close `stdin`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1482]
**bin/repo.dart**
```dart
import 'dart:convert' show LineSplitter, UTF8;
import 'dart:io' show stdin;
import 'dart:async' show Future;

Future<Null> main(List<String> arguments) async {
  await for (final file
      in stdin.transform(UTF8.decoder).transform(const LineSplitter())) {
    print(file);
  }
}
```
**pubspec.yaml**
```yml
name: stdin_err
version: 0.0.1
environment:
  sdk: '>=1.0.0 <2.0.0'
executables:
  repo:
```
```
pub global activate -s path .
```
These keep the application open
```
echo xxx | repo
echo xxx | pub run stdin_err:repo
```
This works fine and the application exists after the input was processed
```
echo xxx | dart bin/repo
```
