### ISSUE TITLE
pub build works poorly for non-web uses

### ISSUE THREAD

**Issue by ianloic** [dart-lang/pub#1490]
I have written a pub transformer that packages a dart application as a snapshot for use in a particular embedding. My pubspec contains:
```
transformers:
  - my_transformer
  # Stop dart2js from running
  - $dart2js:
      $exclude: "**.dart"
```
because otherwise dart2js will try to run against all my code.

I have to invoke `pub build --all` because without `--all` I get an error:
```
Your package must have a "web" directory,
or you must specify the source directories.
```
