### ISSUE TITLE
After adding isolate to dependencies `pub upgrade` can't resolve anymore

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1509]
`isolate` itself doesn't have any dependencies 

[out.txt](https://github.com/dart-lang/pub/files/727041/out.txt) with isolate

[out.txt](https://github.com/dart-lang/pub/files/727043/out.txt) without isolate

```yaml
environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  analyzer: '^0.29.0'
  angular2: ^3.0.0-alpha
  angular2_components: ^0.3.0-alpha
  bwu_ng_mdl:
    path: '../../../bwu_ng_mdl'
  browser: ^0.10.0+2
  code_builder: ^1.0.0-alpha+7
  fhir_client_api:
    path: '../fhir_client_api'
  google_maps: ^3.1.0
  http: ^0.11.3+9
#  isolate: '^1.0.0'
  logging: ^0.11.3+1
  meta: ^1.0.1
  path: ^1.3.9
  quiver: ^0.24.0
  recase: '^1.0.0'
  sass: ^0.4.2
  uuid: ^0.5.3

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  build_runner: ^0.1.1
  build: '>=0.3.0 <0.7.0'
  source_gen: '^0.5.1+4'
  test: '^0.12.15+6'

dependency_overrides:
  quiver: ^0.24.0 # same error without this line, I left it because it was in when above log files where created
```
