### ISSUE TITLE
`pub server` after `pub upgrade` says "pubspec.yaml file has changed"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1510]
```
zoechi@zdev ~/dart/customers/cust1/test_project
 $ pub upgrade
Resolving dependencies... (12.7s)
  analyzer 0.29.5 (0.30.0-alpha.0 available)
  angular2 3.0.0-alpha
  angular2_components 0.3.0-alpha
  args 0.13.7
  async 1.12.0
  barback 0.15.2+9
  boolean_selector 1.0.2
  browser 0.10.0+2
  build 0.6.3
  bwu_ng_mdl 0.1.0 from path ../../../bwu_ng_mdl
  charcode 1.1.1
  code_builder 1.0.0-beta+1
  collection 1.13.0
  convert 2.0.1
  crypto 2.0.1
  csslib 0.13.3+1
  dart_style 0.2.15
  dart_to_js_script_rewriter 1.0.2
  fhir_client 0.1.0 from path ../fhir_client
  fhir_client_api 0.1.0 from path ../fhir_client_api
  fixnum 0.10.5
  func 0.1.1
  glob 1.1.3
  google_maps 3.2.0+2
  html 0.13.1
  http 0.11.3+9
  http_multi_server 2.0.3
  http_parser 3.1.1
  intl 0.14.0
  isolate 0.2.3 (1.0.0 available)
  js 0.6.1
  js_wrapping 0.3.0
  logging 0.11.3+1
  matcher 0.12.0+2
  meta 1.0.4
  mime 0.9.3
  observable 0.20.2
  package_config 1.0.0
  package_resolver 1.0.2
  path 1.4.1
  perf_api 0.1.0
  plugin 0.2.0
  pool 1.2.4
  protobuf 0.5.3
  pub_semver 1.3.2
  quiver 0.24.0
  recase 1.0.0
  sass 0.4.2 (0.4.2+7 available)
  shelf 0.6.7+2
  shelf_packages_handler 1.0.0
  shelf_static 0.2.4
  shelf_web_socket 0.2.1
  source_map_stack_trace 1.1.4
  source_maps 0.10.2
  source_span 1.3.1
  stack_trace 1.7.0
  stream_channel 1.6.1
  string_scanner 1.0.1
  test 0.12.18+1
  typed_data 1.1.3
  utf 0.9.0+3
  uuid 0.5.3
  watcher 0.9.7+3
  web_socket_channel 1.0.4
  yaml 2.1.12
No dependencies changed.
zoechi@zdev ~/dart/customers/cust1/test_project
 $ pub serve --verbose
FINE: Pub 1.22.0-edge.b699aba744bf857d0187c7a5afc8e9c702e4d9db
FINE: Loading asset environment...
FINE: Loading asset environment finished (0.052s).
ERR : The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
FINE: Exception type: DataException
FINE: package:pub/src/utils.dart 788                     dataError
    | package:pub/src/entrypoint.dart 576                Entrypoint._assertLockFileUpToDate
    | package:pub/src/entrypoint.dart 521                Entrypoint.assertUpToDate
    | package:pub/src/entrypoint.dart 106                Entrypoint.packageGraph
    | package:pub/src/barback/asset_environment.dart 75  AssetEnvironment.create.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                         _Completer.completeError
    | package:pub/src/barback/asset_environment.dart 84  AssetEnvironment.create.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.Future.microtask
    | package:pub/src/barback/asset_environment.dart     AssetEnvironment.create.<fn>
    | package:pub/src/log.dart 408                       progress
    | package:pub/src/barback/asset_environment.dart 74  AssetEnvironment.create
    | package:pub/src/command/serve.dart 94              ServeCommand.onRunTransformerCommand.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.Future.microtask
    | package:pub/src/command/serve.dart                 ServeCommand.onRunTransformerCommand
    | package:pub/src/command/barback.dart 56            BarbackCommand.run
    | package:args/command_runner.dart 177               CommandRunner.runCommand.<fn>
    | dart:async                                         Future.Future.sync
    | package:args/command_runner.dart 130               CommandRunner.runCommand
    | package:pub/src/command_runner.dart 128            PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                         Future.Future.sync
    | package:pub/src/utils.dart 72                      captureErrors.<fn>
    | package:stack_trace                                Chain.capture
    | package:pub/src/utils.dart 86                      captureErrors
    | package:pub/src/command_runner.dart 128            PubCommandRunner.runCommand.<async>
    | dart:async                                         _SyncCompleter.complete
    | package:pub/src/command_runner.dart 214            PubCommandRunner._validatePlatform.<async>
```

> Dart VM version: 1.22.0-edge.0e00b3e5c83e4173d442bf287eb99d1dd12cb09b (Wed Jan 25 15:35:49 2017) on "linux_x64"

The project is entirely auto-generated

**Comment by zoechi** [comment]
pubspec.yaml

```yaml
name: test_project
version: 0.1.0
author: Cust1
description: auto-generated
homepage: ''
environment:
  sdk: '>= 1.20.0 <2.0.0'

dependencies:
  angular2: '^2.1.0'
  angular2_components: '^0.2.0'
  bwu_ng_mdl:
    path: '../../../bwu_ng_mdl'
  browser: '^0.10.0+2'
  fhir_client_api:
    path: '../fhir_client_api'
  fhir_client:
    path: '../fhir_client'
  http: '^0.11.3+9'
  logging: '^0.11.3+1'
  meta: '^1.0.1'
  sass: '^0.4.2'
  uuid: '^0.5.3'

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  test: '^0.12.15+6'

dependency_overrides:
#  quiver: ^0.24.0

transformers:
- sass
- angular2:
    mirror_mode: verbose
    entry_points:
    - web/index.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        BaseClient: 'package:http/http.dart'
- angular2/transform/reflection_remover:
    $include:
    - web/index.dart

- $dart2js:
#    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives


- test/pub_serve:
    $include: test/**_test.dart

- dart_to_js_script_rewriter
```
