### ISSUE TITLE
Cryptic error when package name collides with a library name

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/pub#1570]
Running `pub get` on this `pubspec.yaml`

```
name: plugin
description: Cryptic error.
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.2.0
  google_maps: "^3.2.0"
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dart_to_js_script_rewriter

```
... prints:

```
Package analyzer has no versions that match >=0.27.2 <0.28.0 derived from:
- angular2 2.2.0 depends on version >=0.27.0 <0.30.0
- build 0.3.0 depends on version ^0.27.1
- code_transformers 0.4.1 depends on version >=0.27.2 <0.28.0
- dart_style 0.2.2 depends on version ^0.27.0
```

Which is very confusing, the problem is in package name "plugin", change it to something more specific and pub get finishes ok. It's because of collision of package name with the library 'plugin'.

Understandable, but please find some way how to handle this kind of error smarter.
