### ISSUE TITLE
Support semver package matching with git dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1626]
This was [just implemented in npmv5](https://twitter.com/kaelig/status/868129705529978881).

```yaml
dependencies:
  some_dep:
    git: 
      url: git://github.com/dart-lang/async
      version: ^1.0.0
```

**Comment by nex3** [comment]
I'm not sure exactly what behavior you're looking for. Your example is already close to a valid dependency; the valid version would look like

```yaml
dependencies:
  some_dep:
    git: 
      url: git://github.com/dart-lang/async
    version: ^1.0.0
```

This will depend on the version of `git://github.com/dart-lang/async` at `master`, and fail if its version doesn't match `^1.0.0`. If that's the behavior you want, then you're in luck, because it works already!

On the other hand, if you want Pub to look at different revisions in the repository to try to find one that matches the version constraint, this is a duplicate of #1250. We actually [had a pull request for that](https://github.com/dart-lang/pub/pull/1335), but we were unable to find a good backwards-compatible way of making it work. If that's what you're looking for, I don't think it's likely to happen.
