### ISSUE TITLE
Support a nested package structure with git dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1627]
For example, with the [build package](https://github.com/dart-lang/build):

```yaml
dependencies:
  build_runner:
    git: 
      url: https://github.com/dart-lang/build
      path: build_runner
```
