### ISSUE TITLE
more detailed dependency information

### ISSUE THREAD

**Issue by danrubel** [dart-lang/pub#1721]
When analysis server generates code completions, it currently relies on the types that have already been imported. We would like to [suggest identifiers for code that is not yet imported](https://github.com/dart-lang/sdk/issues/25820) but if we are providing completions in the `lib` directory we don't want to suggest identifiers from any dev-dependencies. The `.packages` file provides information about dependencies, but does not specify which of those are dev-dependencies.

If we know which dependencies are dev-dependencies, then we can limit our suggestions when completing code in the `lib` directory. In addition, if we know which dependencies are transitive, we could even generate a hint for each import that is not explicitly listed in the pubspec.

One solution discussed today is to provide that information as part of the lock file. 

@nex3 @munificent @bwilkerson

**Comment by nex3** [comment]
Here's a straw man:

```yaml
packages:
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    dependency: main
    version: "0.13.7"
```

Where `dependency`'s value would be `main`, `dev`, or `transitive`. Would that work?
