### ISSUE TITLE
Flutter SDK dependency support for <flutter>/bin/cache/pkg

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1775]
Pub currently supports resolving packages located in `<flutter>/packages` when using an SDK dependency:

```
flutter:
    description: flutter
    source: sdk
    version: "0.0.41-dev"
```

This bug requests that it additionally also looks for matching packages in `<flutter>/bin/cache/pkg` when using a `sdk_cache` dependency:

```
sky_engine:
    description: flutter
    source: sdk_cache
```
