### ISSUE TITLE
"Incompatible version constraints on async" that makes no sense

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/pub#1794]
I'm running `flutter packages upgrade` on a project (it uses `pub get` under the hood) and get this strange error message in the end of a verbose log:
```
FINE: Resolving dependencies finished (9.1s).
ERR : Incompatible version constraints on async:
    | - flutter_test 0.0.0 depends on version 2.0.3
    | - <mypackage> 0.0.0 depends on version ^1.13.3
    | - pub itself depends on version >=1.8.0 <3.0.0
```
It seems that Flutter's `2.0.3` would be a perfect contender for a compatible version.

`flutter_test` [has a ton of dependencies](https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml) and `<mypackage>` has following dependencies:
```yaml
dependencies:
  async: ^1.13.3
  hex: ^0.1.1
  grpc: ^0.2.1
  logging: ^0.11.3+1
```
