### ISSUE TITLE
Shorter syntax for hosted dependencies on a different pub server

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1806]
_From @robbecker-wf on February 16, 2018 17:26_

# Overview

It's rather cumbersome and repetitive to specify hosted dependencies that are on a different server than the main public server. Let's take a look at how a dependency is declared currently

```
dependencies:
  my_package_name:
    hosted:
      name: my_package_name # duplicated information in this dependency
      url: https://pub.domain.com  # duplicated information across multiple dependencies
    version: ^2.1.0
  my_package_name2:
    hosted:
      name: my_package_name2  # duplicated information in this dependency
      url: https://pub.domain.com  # duplicated information across multiple dependencies
    version: ^1.2.3
```

As you can see, there is a lot of duplicated information, careful indentation and key names to remember or copy and paste to add a new hosted dependency. The minimal needed information is the dependency **name**, **pub server name**, and **version**. 

# Proposal
```
dependencies:
  browser: ^0.10.0 # Comes from the main public pub server. pub.dartlang.org
  rxdart@pub.dartlang.org: ^0.15.0 # Also comes from the main public pub server. pub.dartlang.org
  my_package_name@pub.domain.com: ^2.1.0 # Comes from a private hosted pub server
  my_package_name2@pub.domain.com: ^1.2.3
```
In this scenario, the fact that it is a hosted dependency and the https scheme can be inferred.
If the `@pub.domain.com` is left off, then the default public pub server would be defaulted.

_Copied from original issue: dart-lang/sdk#32201_

**Comment by kevmoo** [comment]
Seems reasonable, @robbecker-wf – thoughts, @nex3 ?

**Comment by natebosch** [comment]
I'm trying to come up with something using yaml aliases but I'm not finding anything thats much of an improvement other than being able to avoid repeating the `url` field. Someone else might have better luck than me though.

Also not sure of the syntax or if I'm doing this right...

```yaml
alias:
  - &hosted
    hosted:
      url: https://pub.domain.com

dependencies:
  some_package_name:
    <<: *hosted
      name: some_package_name
    version: ^1.2.0
```

**Comment by robbecker-wf** [comment]
Our original discussion was to have a shared hosted parent key that specified the pub server once and then each package could just be the name and version ... but I couldn't think of a way to do that in a backwards compatible way since everything under `dependencies:` (dev, and overrides) is assumed to be a package name.

The proposed solution would require changes to pub to parse out the pub server host from the key. Are there any characters that are restricted from a yaml key that would cause problems for a domain name?

**Comment by robbecker-wf** [comment]
Also worth a mention that pubspecs that were written in this style would break in older versions of pub. :(

**Comment by kevmoo** [comment]
> Also worth a mention that pubspecs that were written in this style would break in older versions of pub. :( . But since this style would be primarily used by companies with their own pub server ... maybe that isn't a problem for the majority of the community.

@robbecker-wf – we could disallow publishing such packages to the package site – at least until we felt most of the ecosystem has moved to pub clients that support the syntax

**Comment by robbecker-wf** [comment]
I like that solution @kevmoo

**Comment by nex3** [comment]
I'm not a huge fan of supporting multiple ways of expressing the same thing, but since we already have multiple ways of writing hosted dependencies I suppose it's not the worst. Before we dive in to adding totally new syntax, though, would it make sense to simplify the original example by allowing the `name:` field to be omitted for expanded-form hosted dependencies? Then you could write:

```yaml
dependencies:
  my_package_name:
    hosted: {url: https://pub.domain.com}
    version: ^2.1.0
  my_package_name2:
    hosted: {url: https://pub.domain.com}
    version: ^1.2.3
```

or using aliases:

```yaml
dependencies:
  my_package_name:
    hosted: &domain {url: https://pub.domain.com}
    version: ^2.1.0
  my_package_name2:
    hosted: *domain
    version: ^1.2.3
```

In terms of backwards-compatibility, it's not a big deal to add new syntax to pubspecs. We have validation machinery in place to ensure that packages that use new features have appropriate SDK constraints, and older versions of pub will look at the SDK constraint before they even try to parse dependencies.

**Comment by robbecker-wf** [comment]
@nex3 While I like the shorter version with name assumed and using aliases, I still like the very terse proposal. 
Could we break this into 2 tasks then? First make name optional as you suggest and then this issue can be for follow up work for the 1 line syntax?

**Comment by nex3** [comment]
I understand the value of having something super terse, but there's also a cost in terms of complexity both for humans and other systems that parse the pubspec. Embedding information in dependency names lays a trap for third-party tools that might not thoroughly read the pubspec format documentation and assume that dependency names need no extra parsing. Given that making `name:` optional is already much more terse than the current syntax, I'd like to stick with that unless it's absolutely unworkable.

**Comment by robbecker-wf** [comment]
Ok, I'll concede. optional name it is. I can see that it could be trouble for tools other than pub.

Do you want to use this issue for making name optional or a new one?

**Comment by jonasfj** [comment]
I would suggest we allow shorthand like:
```yaml
dependencies:
  my_package_name:
    hosted:
      url: https://pub.domain.com
      # before we would have to write:
      # name: my_package_name
      # this is now optional -- since it's always the same name.
    version: ^2.1.0
  my_package_name2:
    hosted: {url: https://pub.domain.com}
    version: ^1.2.3
```
Basically, making the package name optional. This is the only sensible thing anyways. Why would anyone want to write the package name twice? (it only makes sense if we support renaming packages -- and internally in `pub` it also makes a bit sense).

If we want to allow an even more terse syntax we could add support for:

```yaml
dependencies:
  my_package_name:
    hosted: https://pub.domain.com
    version: ^2.1.0
  my_package_name2:
    hosted: https://pub.domain.com
    version: ^1.2.3
```

I'm open to that, but I don't think it's necessary. @themisir, @sigurdm thoughts? It this perhaps a quick thing worth fixing now that we support authentication for 3rd-party package repositories?

> We have validation machinery in place to ensure that packages that use new features have appropriate SDK constraints, and older versions of pub will look at the SDK constraint before they even try to parse dependencies.

That's sounds amazing, we should probably test this as we develop this feature :D

**Comment by themisir** [comment]
I personally liked last proposal:

```yaml
dependencies:
  my_package_name:
    hosted: https://pub.domain.com
    version: ^2.1.0
  my_package_name2:
    hosted: https://pub.domain.com
    version: ^1.2.3
```

- it's not necessarily required to write pkg name twice
- hosted packages only have one property if we eliminate name - url. So nesting `hosted` field is unnecessary
