### ISSUE TITLE
"flutter packages get" throws no versions available but actually the version exists

### ISSUE THREAD

**Issue by hemanthrajv** [dart-lang/pub#1849]
How to reproduce?

Clone flutter repo with master branch as active branch.

edit pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_built_redux: ^0.5.0
  built_redux: ^7.4.0
  built_value: ^5.2.1
  built_collection: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^0.11.2
  build_runner: ^0.8.0
  built_value_generator: ^5.2.1
  source_gen: ^0.7.5+1
```

then run

`flutter packages get`

Error:

```
Running "flutter packages get" in test_app...
Package build_runner has no versions that match >=0.8.0 <0.9.0 derived from:
- test_app depends on version ^0.8.0
pub get failed (1)
Process finished with exit code 1
```

But the version [`0.8.0`](https://pub.dartlang.org/packages/build_runner#-readme-tab-) exists.

Not sure why pub throws such error when the package is actually available.
