### ISSUE TITLE
pub upgrade hangs 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1863]
This is the whole output and then it's stuck:

![image](https://user-images.githubusercontent.com/405837/38350782-2380a1cc-38ad-11e8-8ab9-f09f7ae10e42.png)

```yml
name: foo
version: 0.1.0
environment:
  sdk: '>=1.24.2 <2.0.0-f'

publish_to: none # prevent accidental publishing

dependencies:
  async: '^2.0.3'
  built_collection: ^3.0.0
  built_redux: 7.4.0-dev
  built_value: ^5.3.0
  http: ^0.11.3
  intl: ^0.15.0
  logging: ^0.11.3+1
  meta: ^1.1.1
  path: ^1.4.2
  rxdart: ^0.16.0

dev_dependencies:
  build: ^0.12.0
  build_runner: ^0.8.0
  built_value_generator: ^5.4.1
  built_value_test: ^5.3.0
  bwu_grinder_tasks: ^0.1.1-dev
  grinder: ^0.8.0
  source_gen: ^0.7.0
  test: ^0.12.20+3

dependency_overrides:
```

It works with `built_value_generator: ^5.3.0`

`Dart VM version: 2.0.0-dev.45.0 (Wed Apr 4 16:01:54 2018 +0200) on "macos_x64"`
