### ISSUE TITLE
Error when running pub downgrade

### ISSUE THREAD

**Issue by saibotma** [dart-lang/pub#1909]
Getting this error when running `pub downgrade` on Windows.
Pub version: Pub 2.0.0-dev.53.0

```
SLVR: Version solving took 0:00:09.530894 seconds.
    | Tried 7 solutions.
FINE: Resolving dependencies finished (9.5s).
ERR : type 'Symbol' is not a subtype of type 'String' in type cast where
    |   Symbol is from dart:_internal
    |   String is from dart:core
FINE: Exception type: _CastError
ERR : dart:core                                       Object._as
    | package:pub/src/solver/version_solver.dart 137  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96   VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                      _Completer.completeError
    | package:pub/src/solver/version_solver.dart      VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                      _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart 86   VersionSolver.solve
    | package:pub/src/solver.dart 35                  resolveVersions.<fn>
    | package:pub/src/log.dart 378                    progress
    | package:pub/src/solver.dart 32                  resolveVersions
    | package:pub/src/entrypoint.dart 193             Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                      new Future.microtask
    | package:pub/src/entrypoint.dart 192             Entrypoint.acquireDependencies
    | package:pub/src/command/downgrade.dart 37       DowngradeCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                      new Future.microtask
    | package:pub/src/command/downgrade.dart 35       DowngradeCommand.run
    | package:args/command_runner.dart 194            CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                      new Future.microtask
    | package:args/command_runner.dart 142            CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168         PubCommandRunner.runCommand.<fn>
    | dart:async                                      new Future.sync
    | package:pub/src/utils.dart 108                  captureErrors.<fn>
    | package:stack_trace                             Chain.capture
    | package:pub/src/utils.dart 123                  captureErrors
    | package:pub/src/command_runner.dart 168         PubCommandRunner.runCommand
```

`pubspec.yaml`:
```
name: timecoder_common
description: A Dart Libary containin all the shared logic
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.53.0 <2.0.0'

dependencies:
  uuid: "^0.5.3"
  json_annotation: "^0.2.3"
  http: "^0.11.3"
  rxdart: "^0.16.6"
  test: "^0.12.34"

dev_dependencies:
  build_runner: "^0.8.0"
  json_serializable: "^0.5.0"
```
