### ISSUE TITLE
pub publish doesn't detect SDK constraints

### ISSUE THREAD

**Issue by Gigahawk** [dart-lang/pub#1916]
Output of `flutter packages pub publish --dry-run`
```
Publishing android_permissions_manager 0.0.1 to https://pub.dartlang.org:

...

Missing requirements:
* Older versions of pub don't support the Flutter SDK.
  Make sure your SDK constraint excludes old versions:
  
  environment:
    sdk: ">=1.19.0 <2.0.0"
* Published packages should have an upper bound constraint on the Dart SDK (typically this should restrict to less than the next major version to guard against breaking changes).
  See https://www.dartlang.org/tools/pub/pubspec#sdk-constraints for instructions on setting an sdk version constraint.

...

Sorry, your package is missing some requirements and can't be published yet.
For more information, see: https://www.dartlang.org/tools/pub/cmd/pub-lish.
pub finished with exit code 65
```

Content of my `pubspec.yaml`:
```
name: android_permissions_manager
description: Plugin to manage permissions on android
version: 0.0.1
author: Gigahawk
homepage: https://github.com/Gigahawk/android_permissions_manager

dependencies:
  flutter:
    sdk: flutter

environtment:
  sdk: ">=1.19.0 <2.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.gameboy.androidpermissionsmanager
    pluginClass: AndroidPermissionsManagerPlugin

...

```

I've already tried to change what's in `sdk:`, as well as publishing on a linux and Windows machine.
