### ISSUE TITLE
pub global activate and git sub directory

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/pub#1934]
_From @alextekartik on June 22, 2018 9:52_

Using 2.0.0-dev.63 on Ubuntu 16.04

There is currently a way to define a git dependency with a a sub directory

```yaml
  my_package:
    git:
      url: <git_url>
      path: <sub_path>
```

however using `pub global activate` you can only specify a url. Is there a plan to support specifying a url and path when using a git source? thanks!

_Copied from original issue: dart-lang/sdk#33583_
