### ISSUE TITLE
dart packages error with dialogflow dependencies

### ISSUE THREAD

**Issue by fcu-d0530299** [dart-lang/pub#2006]
my pubspec.yaml

```
name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_dialogflow: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/My Project-97cd26790e30.json

```

```
Running "flutter packages get" in myapp...                      
Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\XXXXX\AppData\Local\Temp\pub_1498e884-f4c5-11e8-97dd-ac9e17ba5b07\data.tar

Extracting  doc\api\__404error.html
Extracting  doc\api\categories.json
Extracting  doc\api\flutter_dialogflow\AIResponse-class.html
Extracting  doc\api\flutter_dialogflow\AIResponse\AIResponse.html
...
Extracting  doc\api\v2_message\QuickReplies\operator_equals.html
file doc\api\v2_message\QuickReplies\quickReplies.html
already exists. Overwrite with 
doc\api\v2_message\QuickReplies\quickReplies.html?
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
ERROR: Can't allocate required memory!

package:pub/src/io.dart 944:7               _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 821:20              withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 915:10              _extractTarGzWindows
package:pub/src/io.dart 843:18              extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 367:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```
