### ISSUE TITLE
Can't pull a package and its generator using git

### ISSUE THREAD

**Issue by jorgecoca** [dart-lang/pub#2047]
I have a utility project that consists of two packages: an API package with annotations, and a generator package that will inspect those annotations, and generate some code.

The `pubspec.yaml` of the generator package looks like this:

```yaml
name: annotation_generator

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: 1.0.1
  collection: 1.14.11
  source_gen: 0.9.1+3
  annnotation:
    git:
      url: git@mycompany:team20/annotation.git
      path: translator
  
dev_dependencies:
  build_test: 0.10.3+3
  build_runner: 1.0.0
  test: '>=1.5.1+1 <2.0.0'
```

When I add these packages to a project, I do it like this:

```yaml
name: my_project

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  annotation:
    git:
      url: git@mycompany:team20/annotation.flutter.git
      path: annotation
      ref: v1.0.0

dev_dependencies:
  build_runner: 1.0.0
  test: 1.5.1+1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  annotation_generator:
    git:
      url: git@mycompany:team20/annotation.flutter.git
      path: annotation_generator
      ref: v1.0.0
  args: 1.5.0
  mockito: 4.0.0
```

However, this gives the following error when running `packages get`:

```
Because every version of translator_generator from git depends on translator from git {url: git@code.connected.bmw:mobile20/translator.flutter.git, ref: HEAD, path: translator} and mobile_connected depends on translator from git {url: git@code.connected.bmw:mobile20/translator.flutter.git, ref: v1.0.0, path: translator}, translator_generator from git is forbidden.
So, because mobile_connected depends on translator_generator from git, version solving failed.
 
pub get failed (1)
```

Is this expected? What would an alternative for this scenario?
