### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by lesnitsky** [dart-lang/pub#2054]
```
FINE: Resolving dependencies finished (0.1s).
ERR : The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
    | 
    | Because project requires SDK version 2.1.1-dev.0.1.ec86471ccc, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- End log transcript ----
```

**Comment by lesnitsky** [comment]
```
FINE: Resolving dependencies finished (3.6s).
ERR : The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
    | 
    | Because turtle_chat depends on photo_view >=0.2.0 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- End log transcript ----
```

**Comment by zoechi** [comment]
What does the `pubspec.yaml` look like?

**Comment by lesnitsky** [comment]
```
version: 2.0.11+353

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^3.2.2
  flutter_svg: ^0.6.3
  cached_network_image: ^0.5.0+1
  http: ^0.12.0
  graphql_flutter: ^0.9.5
  phoenix_wings: ^0.1.2
  localstorage: ^1.0.1
  shared_preferences: ^0.4.3
  firebase_messaging: ^2.1.0
  json_annotation: ^2.0.0
  sentry: ">=2.0.0 <3.0.0 "
  url_launcher: ^5.0.1
  photo_view: ^0.2.0
  image_picker: 0.4.12+1
  mime: ^0.9.6
  xml: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  perf_timer: ^1.0.4
  json_serializable: ^2.0.0
  build_runner: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - images/
```
