### ISSUE TITLE
Misleading error message when git dependency name doesn't match

### ISSUE THREAD

**Issue by PhilipRoman** [dart-lang/pub#2096]
Contents of `pubspec.yaml`:
```yaml
name: my_package
dependencies:
  wrong_name:
    git: git://github.com/user/different_name.git
```
Running
```bash
$ pub get
```
fails with exit code 65 and a misleading error message:
```
Resolving dependencies...
Error on line 1, column 7: "name" field doesn't match expected name "wrong_name".
name: different_name
      ^^^^^^^^^^^^^^
```
The error message indicates an error on line 1, which would mean there is an issue with the name of `my_package`. This is completely wrong as the actual error is that dependency `wrong_name` points to a Dart project with package name `different_name`.
## Software Versions
```bash
$ pub --version
Pub 2.2.0
```
```bash
$ dart --version
Dart VM version: 2.2.0 (Unknown timestamp) on "linux_x64"
```
