### ISSUE TITLE
Pub crashes in "cache add" command

### ISSUE THREAD

**Issue by simolus3** [dart-lang/pub#2157]
# Environment
- `pub version`: `Pub 2.3.1`
- OS version: Running `Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_x64"` on `Manjaro Linux x86_64`
- I'm not behind a firewall

# Problem
I was trying to run `pana` locally, which failed on `pub cache add --verbose .` This is the pubspec for the package in question:
```yaml
name: moor
version: 1.4.0+1
# description, authors, maintainer and a bunch of links omitted
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: '>= 1.0.0 <2.0.0'
  collection: '>= 1.0.0 <2.0.0'

dev_dependencies:
  moor_generator: ^1.4.0
  build_runner: '>=1.3.0 <2.0.0'
  build_test: ^0.10.8
  test: ^1.6.4
  test_api: '>=0.2.0 <1.0.0'
  test_core: '>=0.2.0 <1.0.0'
  mockito: ^4.1.0
  grinder: ^0.8.3
  coverage: ^0.12.4

dependency_overrides:
  moor_generator:
    path: ../moor_generator
  coverage:
    git: https://github.com/simolus3/coverage.git
```

I tried running `pub cache repair`, but that didn't fix the problem. I also tried to remove the `dependency_overrides` section and run `pub get`/`pub upgrade`, but that didn't fix it either.

## Expected behavior
I'm not really sure what to expect, I just ran it as part of `pana`.

## Actual behavior
Running `pub --trace cache add --verbose .` prints:
```
FINE: Pub 2.3.1
IO  : Get versions from https://pub.dartlang.org/api/packages/.
IO  : HTTP GET https://pub.dartlang.org/api/packages/
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: cache add
    | X-Pub-Session-ID: 93EFDC61-4391-4A97-A1B5-A6F9AC007E68
    | user-agent: Dart pub 2.3.1
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/
    | took 0:00:00.717380
    | transfer-encoding: chunked
    | date: Thu, 20 Jun 2019 14:49:02 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | strict-transport-security: max-age=7200; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
ERR : The method 'map' was called on null.
    | Receiver: null
    | Tried calling: map<PackageId>(Closure: (dynamic) => PackageId)
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                     Object.noSuchMethod
    | package:pub/src/source/hosted.dart 154:38     BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                    _AsyncAwaitCompleter.completeError
    | package:pub/src/source/hosted.dart            BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                    _asyncThenWrapperHelper
    | package:pub/src/source/hosted.dart            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12            BoundSource.getVersions
    | package:pub/src/command/cache_add.dart 57:29  CacheAddCommand.run
---- Log transcript ----
FINE: Pub 2.3.1
IO  : Get versions from https://pub.dartlang.org/api/packages/.
IO  : HTTP GET https://pub.dartlang.org/api/packages/
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: linux
    | X-Pub-Command: cache add
    | X-Pub-Session-ID: 93EFDC61-4391-4A97-A1B5-A6F9AC007E68
    | user-agent: Dart pub 2.3.1
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/
    | took 0:00:00.717380
    | transfer-encoding: chunked
    | date: Thu, 20 Jun 2019 14:49:02 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | strict-transport-security: max-age=7200; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
ERR : The method 'map' was called on null.
    | Receiver: null
    | Tried calling: map<PackageId>(Closure: (dynamic) => PackageId)
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                     Object.noSuchMethod
    | package:pub/src/source/hosted.dart 154:38     BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                    _AsyncAwaitCompleter.completeError
    | package:pub/src/source/hosted.dart            BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                    _asyncThenWrapperHelper
    | package:pub/src/source/hosted.dart            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12            BoundSource.getVersions
    | package:pub/src/command/cache_add.dart 57:29  CacheAddCommand.run
---- End log transcript ----
```
