### ISSUE TITLE
Test that pre-releases do not take precedence over stable releases

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2164]
Maybe I missed it, but I couldn't find any tests that if we have two versions of package foo `1.0.0` and `1.1.0-dev`, then `1.0.0` will be installed unless the other version is explicitly pinned.

We should have tests for this.

**Comment by jakemac53** [comment]
There is actually no guarantee for this (I know because it has caused problems).

Pub only prefers stable release versions but it won't backtrack to try and find a solution without pre-release versions.

**Comment by jakemac53** [comment]
To clarify, lets say you have the following pubspecs, where `a` and `b` are published on pub and `app` is the application package:

Latest `a` pubspec:
```yaml
name: a
version: 2.0.0
```

Pre-release `b` pubspec:
```yaml
name: b
version: 2.0.0-dev
dependencies:
  a: ^2.0.0
```


Stable `b` pubspec:
```yaml
name: b
version: 1.0.0
dependencies:
  a: ^1.0.0
```

`app` pubspec:
```yaml
name: app
version: 1.0.0
dependencies:
  a: '>=1.0.0 <3.0.0'
```

In this scenario, I believe that pub will always select version `2.0.0` of `a`, and `2.0.0-dev` of `b`, even though it could get the stable `1.0.0` of each of them.

This is because it first went to find a version of `a`, which chooses the stable `2.0.0` release. It then tries to select a version of `b` that is compatible, but only the pre-release version is, so it selects that. It does not backtrack to find a version solve with only stable releases. I believe that is purely for performance reasons.

I think this is also the case if there was a direct dependency on `b` from the `app` package.
