### ISSUE TITLE
Package angular has no versions that match >=5.0.0 <6.0.0 derived from:

### ISSUE THREAD

**Issue by hpoit** [dart-lang/pub#2179]
How do I solve this? 
![image](https://user-images.githubusercontent.com/3711100/62252049-075edf80-b3c8-11e9-979a-186f0d48a432.png)

Related to https://github.com/dart-lang/pub/issues/912

**Comment by johnpryan** [comment]
This is an issue with the version of `angular_router` you are trying to use. If you are using Dart 2 (which includes [PubGrub](https://medium.com/@nex3/pubgrub-2fb6470504f)) you can track down the issue without too many hiccups. 

For example, with the Dart 2.4.0 SDK, running `pub get` on this file produces the following message:

```
Because foo depends on angular_router >=1.0.1 <2.0.0-alpha+16 which requires SDK version
  >=1.24.0 <2.0.0 or >=2.0.0-dev.3.0 <2.0.0, version solving failed.
```

OK, so there's an issue with `angular_router`. Let's see if we can relax that version:

```
name: foo
dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: any
dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_test: ^0.10.2
  build_web_compilers: ">=1.2.0 <3.0.0"
```

Now, running `pub get` fetches `angular_router 2.0.0-alpha+22` without any issues.
