### ISSUE TITLE
Multiple pub repo support

### ISSUE THREAD

**Issue by kangwang1988** [dart-lang/pub#2185]
Corresponding to cocoapods for iOS and maven for android, multiple repo support is missing in Flutter(pub design).

Can we support this feature, so that developers can have multiple repo support, typically a public repo and a intracompany(private) repo?

Though git can also do the trick, a native support multiple pub support would made it nicer.

@jonasfj

**Comment by jonasfj** [comment]
Don't we have this? see: https://dart.dev/tools/pub/dependencies#hosted-packages
```yaml
dependencies:
  meta: ^1.0.0 # will be installed from pub.dev
  transmogrify: # will be installed from your-package-server.com
    hosted:
      name: transmogrify
      url: http://your-package-server.com
    version: ^1.4.0
```

**Comment by kangwang1988** [comment]
@jonasfj 
In this design, what if the transmogrify has some dependency, lets say package_other, will it work fine no matter package_other is hosted on your-package-server.com or PUB_HOSTED_URL?

**Comment by jonasfj** [comment]
I haven't tested it, but I would imagine that `package_other` would have to exist on `pub.dev`. If it exists on `your-package-server.com` then `transmogrify` should reference it the same way I showed above.

I would suggest testing it out. Maybe write a blog post on how to use third party repositories.

Note. If mixing `pub.dev` with third party repositories  you're not going to want to use `PUB_HOSTED_URL`, instead you should use `hosted` as shown above, and `publish_to`.

**example:**
```yaml
name: my_self_hosted_package
version: 1.2.0
publish_to: https://my-own-package-repo.com
dependencies:
  meta: ^1.1.6 # from pub.dev
  my_other_self_hosted_package:
    hosted:
      name: my_other_self_hosted_package
      url: https://my-own-package-repo.com
    version: ^1.4.0
```
