### ISSUE TITLE
Add 'hooks' sections into pubspec.yaml.

### ISSUE THREAD

**Issue by qianxinfeng** [dart-lang/pub#2190]
Pub manager feature request.
Add 'preget' and 'postget' sections into pubspec.yaml.
This can be useful when installing the packages.
Example.

```
#pubspec.yaml
name: my_lib
hooks:
   preget: 
      - sh ./bin/my_pre_get_script.sh
   postget:
      - sh ./bin/my_post_get_script.sh

```
```
# my_pre_get_script.sh
#do something check before `pub get`
```
```
# my_post_get_script.sh
#do something init after `pub get`
```
