### ISSUE TITLE
Error trying to publish package front_end

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/pub#2191]
# Environment

- `pub version` or `flutter pub version`: Pub 2.5.0-edge.b99df2be860490e6825a8f2e16eb4b2fd7a33b9e
- OS version: Debian 4.19.37-5+deb10u1rodete1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

Trying to publish package `front_end` I got the following stack trace:

```
Missing package name (at offset 26)
package:package_config/packages_file.dart 47:9                  parse
package:analyzer/src/context/builder.dart 272:30                ContextBuilder.createPackageMap
package:analyzer/src/workspace/simple.dart 41:28                SimpleWorkspace.packages
package:analyzer/src/workspace/simple.dart 36:51                SimpleWorkspace.packageMap
package:analyzer/src/workspace/simple.dart 47:43                SimpleWorkspace.packageUriResolver
package:analyzer/src/workspace/simple.dart 59:19                SimpleWorkspace.createSourceFactory
package:analyzer/src/context/builder.dart 436:45                ContextBuilder.getAnalysisOptions
package:analyzer/src/context/builder.dart 179:9                 ContextBuilder.buildDriver
package:analyzer/src/dart/analysis/context_builder.dart 106:37  ContextBuilderImpl.createContext
package:pub/src/dart.dart 111:36                                AnalysisContextManager.createContextsForDirectory
package:pub/src/validator/strict_dependencies.dart 26:28        new StrictDependenciesValidator
package:pub/src/validator.dart 126:7                            Validator.runAll
package:pub/src/command/lish.dart 156:32                        LishCommand._validate
dart:async                                                      _AsyncAwaitCompleter.start
package:pub/src/command/lish.dart 155:25                        LishCommand._validate
package:pub/src/command/lish.dart 136:15                        LishCommand.run
dart:async                                                      _AsyncAwaitCompleter.start
package:pub/src/command/lish.dart 112:13                        LishCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
dart:async                                                      _AsyncAwaitCompleter.start
package:args/command_runner.dart 142:23                         CommandRunner.runCommand
package:pub/src/command_runner.dart 171:39                      PubCommandRunner.runCommand.<fn>
dart:async                                                      new Future.sync
package:pub/src/utils.dart 109:12                               captureErrors.<fn>
dart:async                                                      runZoned
package:pub/src/utils.dart 126:5                                captureErrors
package:pub/src/command_runner.dart 171:13                      PubCommandRunner.runCommand
```

Pubspec.yaml is as follows:

```yaml
name: front_end
# Currently, front_end API is not stable and users should not
# depend on semver semantics when depending on this package.
version: 0.1.23
author: Dart Team <misc@dartlang.org>
description: Front end for compilation of Dart code.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/front_end
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  kernel: 0.3.23
  package_config: '^1.1.0'
  path: '^1.3.9'
  yaml: '^2.1.12'
dev_dependencies:
  analyzer: 0.38.1
  args: '>=0.13.0 <2.0.0'
  build_integration:
    path: ../build_integration
  dart_style: '^1.0.7'
  json_rpc_2: ^2.0.9
  test: ^1.3.4
  test_reflective_loader: ^0.1.0
  web_socket_channel: ^1.0.4
```

## Expected behavior

Package should be published.

## Actual behavior

Stack trace - see above

## --trace output

Nearly 9000 lines long.  Available on request.
