### ISSUE TITLE
The gzip file did not contain a tar file. pub get failed (65)

### ISSUE THREAD

**Issue by SharlSherif** [dart-lang/pub#2196]
I'm having this issue when installing any packages to my basic Flutter app.

pubspec.yaml

```
name: employee_timer
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  local_auth: ^0.5.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
CMD: 
```
>flutter packages get or flutter pub get

The gzip file did not contain a tar file.
package:pub/src/io.dart 931:7               _extractTarGzWindows.<fn>.<fn>
dart:collection                             _ListBase&Object&ListMixin.firstWhere
package:pub/src/io.dart 930:10              _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 815:20              withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 909:10              _extractTarGzWindows
package:pub/src/io.dart 837:18              extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 374:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 370:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 231:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in employee_timer...
pub get failed (65)

```
