### ISSUE TITLE
Expose a package path for the Dart SDK

### ISSUE THREAD

**Issue by dnfield** [dart-lang/pub#2240]
Pub portion of dart-lang/sdk#39167

Currently, https://github.com/dart-lang/pub/blob/master/lib/src/sdk/dart.dart#L49 returns `null` as the Dart SDK does not ship with packages.

If Dart can ship with its various in-sdk packages, pub should be updated so that things like

```yaml
dependencies:
  kernel:
    sdk: dart
  meta:
    sdk: dart
```

will work.
