### ISSUE TITLE
pub get hangs after about 10s of resolving dependencies

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/pub#2256]
# Environment

- `pub version`: 2.5.2
- OS version: Chrome OS Version 78.0.3904.92 
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

Running `pub get` produces the following output:

> Resolving dependencies... (time)

And continues to update the time every millisecond until about 10 seconds and then it ceases to update. It's been running for about 7 minutes with no update since 10.3 seconds.

Steps to reproduce:

```shell
$ git clone git@github.com:leonsenft/path_to_regexp_demo.git
$ cd path_to_regexp_demo
$ git checkout bc3d2d3141021eac650e097cee45841fd4ac5204
$ pub get
```

```yaml
name: path_to_regexp_demo
description: A path_to_regexp demo for testing routes.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp_demo

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_components: ^0.12.0
  path_to_regexp: ^0.2.1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.2.0
  build_test: ^0.10.0
  build_web_compilers: ^1.1.0
  pageloader: ^3.1.0
  sass_builder: ^2.1.0
  test: ^1.3.0
```

## Expected behavior

`pub get` successfully resolves dependencies, or fails trying with the usual descriptive error message as to why it failed.

## Actual behavior

`pub get` seems to hang indefinitely with no update to the time after about 10 seconds.

## --trace output

Doesn't seem to produce any additional output on stdout or stderr. Is it written to a file somewhere?
