### ISSUE TITLE
The Flutter plugin platforms schema is allowed when no Flutter SDK constraint is set

### ISSUE THREAD

**Issue by amirh** [dart-lang/pub#2264]
The following `pubspec.yaml` passes `pub publish --dry-run`:

```yaml
name: hello
description: A new flutter plugin project.
version: 0.0.1
homepage: https://www.google.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hello
        pluginClass: HelloPlugin
      ios:
        pluginClass: HelloPlugin
      macos:
        pluginClass: HelloPlugin
      web:
        pluginClass: HelloPlugin
        fileName: hello_web.dart
```

Since no Flutter SDK constraint is specified, It should instead print:
```
* pubspec.yaml allows Flutter SDK version 1.9.x, which does not support the flutter.plugin.platforms key.
  Please consider increasing the Flutter SDK requirement to ^1.10.0 (environment.sdk.flutter)
```

Note that when adding `  flutter: ">=1.9.1+hotfix.5 <2.0.0"` to the `environment:` map the error message is showing (as expected).

@jonasfj
