### ISSUE TITLE
Need the ability to pull packages from an internal repository

### ISSUE THREAD

**Issue by juancdelgado** [dart-lang/pub#2310]
I'm in a corporate firewall which blocks me from pulling packages from pub.dev. However i was given the option to use an internal repository where I can pull the packages from there. 

Maven and Gradle already has the ability to allow me to pull packages from another sources. However, after reading `https://dart.dev/tools/pub/pubspec#repository`, I don't see where anything where I can do something like this in my `pubspec.yaml` file:
```
dependencies:
  flutter:
    sdk: flutter

  http:
    hosted:
      name: http
      url: http://repository.internal-repo.com/repository/packages/
    version: ^0.12.0+4
```

If I were to hit the link directly via Chrome `http://repository.internal-repo.com/repository/packages/http-0.12.0+4.tar.gz` the package downloads

But when i run a `pub get`:
```
502 notresolvable trying to find package http-0.12.0+4.tar.gz at http://repository.internal-repo.com/repository/packages/.
pub get failed (server unavailable) -- attempting retry 1 in 1 second...

```

I see that you can pull from github directly however that is also blocked by our proxy.

Am i doing something wrong here or is this feature not available?
