### ISSUE TITLE
pub run build_runner build does not work on armhf

### ISSUE THREAD

**Issue by guyluz11** [dart-lang/pub#2347]
# Environment

- `dart-sdk 2.7.0/2.7.1 Stable Linux | ARMv7`
- OS version: `Linux NanoPi-Duo2 4.14.111 #1 SMP Fri Dec 13 14:32:09 IST 2019 armv7l armv7l armv7l GNU/Linux`

# Problem
Running `pub run build_runner build` on armhf stuck and does not retrieving any output to the console

This is my pubspec.yaml

```
name: appName
description: A sample command-line application.
version: 1.0.0
homepage: https://www.example.com
author: name

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  firedart: ^0.6.1
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.8.9
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^3.1.0
  # Convenient code generator for get_it
  injectable: ^0.2.2
  # Allow returning more than one type of object
  equatable: ^1.1.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.4
  # Library for mocks
  mockito: ^4.1.1
  build_runner:
  # A generator for injectable library
  injectable_generator: ^0.2.2
```
