### ISSUE TITLE
Error in pub get 

### ISSUE THREAD

**Issue by Ankit-afk** [dart-lang/pub#2383]
I get this error when `flutter pub get` is used in the project directory.

```
Invalid argument(s): Minimum version ("1.0.0") must be less than maximum ("1.0.0-0").
package:pub_semver/src/version_range.dart 67:7                                        new VersionRange
package:pub/src/solver/reformat_ranges.dart 61:27                                     _reformatTerm
package:pub/src/solver/reformat_ranges.dart 39:26                                     reformatRanges.<fn>
dart:_internal                                                                        ListIterable.toList
package:pub/src/solver/reformat_ranges.dart 40:12                                     reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                                     reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                                     reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                                     reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                                     reformatRanges
package:pub/src/solver/reformat_ranges.dart 33:27                                     reformatRanges
package:pub/src/solver/version_solver.dart 308:24                                     VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 131:27                                     VersionSolver._propagate
package:pub/src/solver/version_solver.dart 96:9                                       VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                                     resolveVersions.<fn>
package:pub/src/log.dart 378:18                                                       progress
package:pub/src/solver.dart 32:10                                                     resolveVersions
package:pub/src/entrypoint.dart 217:24                                                Entrypoint.acquireDependencies
package:pub/src/command/get.dart 41:23                                                GetCommand.run
package:args/command_runner.dart 197:27                                               CommandRunner.runCommand
package:pub/src/command_runner.dart 171:39                                            PubCommandRunner.runCommand.<fn>
dart:async                                                                            new Future.sync
package:pub/src/utils.dart 109:12                                                     captureErrors.<fn>
dart:async                                                                            runZoned
package:pub/src/utils.dart 126:5                                                      captureErrors
package:pub/src/command_runner.dart 171:13                                            PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                                            PubCommandRunner.run
C:\b\s\w\ir\cache\builder\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in munchapp...
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

pubspec.yaml file:
```
name: test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.24+1
  flutter_polyline_points: ^0.1.0
  location: ^2.5.3
  geolocator: ^5.3.0
  path_provider: ^1.6.1
  cached_network_image: ^2.0.0
  flutter_bloc: ^3.2.0
  simple_animations: ^1.3.3
  http: ^0.12.0+1
  shared_preferences: ^0.5.6+1
  flutter_whatsnew: ^0.2.0+3
  local_auth: ^0.6.1
  provider: ^4.0.2
  equatable: ^1.1.1
  flutter_launcher_icons: ^0.7.4
  flutter_xlider: ^3.1.1
  url_launcher: ^5.4.2
  intl: ^0.16.1
  flutter_slidable: ^0.5.4
  sticky_headers: ^0.1.8+1

  cupertino_icons: ^0.1.2


flutter:
  uses-material-design: true
  assets:
   
    - assets/logos/logo.png

    - assets/styles/map_style.txt

    - assets/icons/bar.png
    - assets/icons/burger.png
    - assets/icons/cafe.png
    - assets/icons/chinese.png
    - assets/icons/contemporary.png
    - assets/icons/default.png
    - assets/icons/fast_food.png
    - assets/icons/healthy.png
    - assets/icons/indian.png
    - assets/icons/pizza.png
    - assets/icons/pub.png
    - assets/icons/sandwiches.png
    - assets/icons/sea_food.png
    - assets/icons/sushi.png

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

```

`flutter doctor`
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at E:\Softwares\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Admin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0
