### ISSUE TITLE
Pubspec.yaml constraints resolved to unexpected version

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/pub#2446]
`package:aqueduct` has versions on pub.dev `3.2.1`, `3.3.0`, and `3.3.0-b1`. The constraint `^3.0.0` selects `3.3.0-b1`. I would expect it to select `3.3.0`. 

It also selected `3.3.0-b1` when only `3.2.1` and `3.3.0-b1` existed (and `3.3.0` did not). If both `3.3.0-b1` and `3.3.0` can simply be deleted from pub.dev, that is best, however, I'd also like to understand what creates that behavior.

pub 2.7.0 macOS.

```yaml
name: foobar
description: An empty Aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
```
