### ISSUE TITLE
Cannot depend on a git package if the git package depends on a path package.

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [dart-lang/pub#2447]
I have a problem when I want to add dependency from another team.

Assume my company has a partner. The partner allows my company access to their git repository `ssh://git@partner.com/root_project.git`. In `root_project`, we have 2 sub-projects: `project_a` and `project_b`. Below is the `pubspec.yaml` of `project_a`:

```
# /project_a/pubspec.yaml

dependencies:
  project_b:
    path: ../project_b
```

My `pubspec.yaml`:
```
dependencies:
  project_a:
    git:
      url: ssh://git@partner.com/root_project.git
      path: project_a
```

If I run `pub get`, I hope that it's smart enough to find `project_b` from relative path of the git repository.

Unfortunately, I get error: `dependency: "../project_b" is a relative path, but this isn't a local pubspec.`

The problem is that I have no permission to change the file `/project_a/pubspec.yaml` to use git url because it's not my project.

**Comment by sigurdm** [comment]
Yes, my guess is that these are the same.

Is the path being interpreted relative to the git root?
Ie. what happens if you use:

```
# /project_a/pubspec.yaml

dependencies:
  project_b:
    path: project_b
```

**Comment by nguyenxndaidev** [comment]
> Is the path being interpreted relative to the git root?
* The partner project has 2 sub projects (project_a depends on project_b). Both are belong to the partner.
* project_a point to project_b using local path
* The configuration of local path is correct and relative to the repository root.

> Ie. what happens if you use:
> 
> ```
> # /project_a/pubspec.yaml
> 
> dependencies:
>   project_b:
>     path: project_b
> ```
As I mentioned, project_a is not my project so I cannot change `/project_a/pubspec.yaml`.

My project depends on project_a:
```
dependencies:
  project_a:
    git:
      url: ssh://git@partner.com/root_project.git
      path: project_a
```
