### ISSUE TITLE
Output from pub outdated is confusing when using pre-release package versions

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#2469]
Repro steps:

1. Create a `pubspec.yaml` with:
```
name: test

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
```
2. Run `pub get`
3. Run `pub outdated`

<img width="466" alt="Screenshot 2020-04-29 at 13 50 12" src="https://user-images.githubusercontent.com/13644170/80592853-6d909580-8a20-11ea-9ebe-0d0df48e7a7f.png">

It's a bit confusing that outdated lists versions in Resolveable and Latest that are older than what's currently used.
