### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by vishnuiiit** [dart-lang/pub#2470]
I am trying to create a new flutter project but it was showing me errors like URI not found for material.dart etc. which were supposed to be even in flutter SDK. so I tried to do flutter pub get but it gave me this error 
```
D:\AndroidDevelopment\stock_exchange>flutter pub get
Because every version of flutter from sdk depends on meta 1.1.8 which doesn't match any versions, flutter from sdk is forbidden.
So, because stockexchange depends on flutter any from sdk, version solving failed.
Running "flutter pub get" in stock_exchange...
pub get failed (1; So, because stockexchange depends on flutter any from sdk, version solving failed.)
```

so I decided to check with flutter doctor but it gives me
```
D:\AndroidDevelopment\stock_exchange>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.1039], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at D:\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

what should I do?

**Comment by vishnuiiit** [comment]
![image](https://user-images.githubusercontent.com/53317018/80622404-5e343b00-8a66-11ea-98a8-1989e438b7df.png)

one more thing that I noticed is that as shown in the above image, there is no option for adding dart libraries and therefore there is no path to dart packages in flutter

**Comment by sigurdm** [comment]
Could you reproduce your `pubspec.yaml` here?

**Comment by vishnuiiit** [comment]
pubspec.yaml
```
name: stockexchange
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

flutter:

  uses-material-design: true
```

**Comment by sigurdm** [comment]
That looks ok. That's mysterious.

Perhaps it is a network issue.
Can you access: https://pub.dev/api/packages/meta in a browser?
Where are you located (country)?

**Comment by vishnuiiit** [comment]
> That looks ok. That's mysterious.
> 
> Perhaps it is a network issue.
> Can you access: https://pub.dev/api/packages/meta in a browser?
> Where are you located (country)?

yes I can access https://pub.dev/api/packages/meta in my browser
I am located in India

**Comment by sigurdm** [comment]
And can you access: https://storage.googleapis.com/pub-packages/packages/meta-1.1.8.tar.gz ?

**Comment by vishnuiiit** [comment]
> And can you access: https://storage.googleapis.com/pub-packages/packages/meta-1.1.8.tar.gz ?

yes this too, as i am able to download meta1.1.8 from this link, could this have anything to do with this

> ![image](https://user-images.githubusercontent.com/53317018/80622404-5e343b00-8a66-11ea-98a8-1989e438b7df.png)
> 
> one more thing that I noticed is that as shown in the above image, there is no option for adding dart libraries and therefore there is no path to dart packages in flutter

**Comment by sigurdm** [comment]
No I don't think so - usually you should be able to do all dependency management with 'flutter pub' and your pubspec.yaml.

**Comment by sigurdm** [comment]
@jonasfj do you have a clue?

**Comment by jonasfj** [comment]
Can you paste the output of `flutter pub get -v` into a gist and drop a link here.

**Comment by vishnuiiit** [comment]
> Can you paste the output of `flutter pub get -v` into a gist and drop a link here.

yes of course

https://gist.github.com/vishnuiiit/8abefe689aa8514ee91373518ca3d085

**Comment by vishnuiiit** [comment]
I added flutter_test in pubspec.yaml that I once removed

pubspec.yaml
```
name: stock_exchange
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
```

and it gave me this error on pub get

```
[stock_exchange] flutter.bat pub get
Running "flutter pub get" in stock_exchange...                  
Error on line 1, column 7 of D:\flutter\packages\flutter_test\pubspec.yaml: "name" field doesn't match expected name "flutter_test".

  ╷

1 │ name: test_api

  │       ^^^^^^^^

  ╵
pub get failed (65;   ╵)
exit code 65
```

could this help?
