### ISSUE TITLE
Pub get hangs when the same package is requested from different hosts

### ISSUE THREAD

**Issue by simolus3** [dart-lang/pub#2509]
# Environment

- `pub version` or `flutter pub version`: `Pub 2.8.3`
- OS version: `Linux 5.6.12-1-MANJARO x86_64 GNU/Linux`
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

When a package would be required from two different hosts, `pub get` hangs. The following example shows this:

```yaml
name: foo

dependencies:
  front_end: any
  kernel:
    hosted:
      name: kernel
      url: https://kneipe.simonbinder.eu/dart/edge
```

Note: Here, `front_end` from `pub.dev` has a dependency on `kernel` (from `pub.dev`). Adding another hosted dependency for `kernel` causes pub to hang.

## Expected behavior

I'd expect `pub get` to fail with an error.

## Actual behavior

`pub get` hangs without output.

## --trace output

`pub get --trace` only displays `Resolving dependencies...`.
