### ISSUE TITLE
pub global activate precompiles way too much when using -spath

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/pub#2526]
# Environment

- `pub version` or `flutter pub version`:
```
jcollins-macbookpro2:dartdoc jcollins$ pub version
Pub 2.9.0-14.0.dev
```

- OS version:
macOS 10.5.5., also reproduced on Ubuntu 16.04.6 LTS via Travis.

# Problem

`pub global activate -spath .` on the head of dartdoc changed in behavior after 2.9.0-13.0.dev.  It now precompiles so many things that it grinds my travis build depending on this feature to a halt (dart-lang/dartdoc#2233).  

```yaml
name: dartdoc
# Run `grind build` after updating.
version: 0.32.1
description: A non-interactive HTML documentation generator for Dart source code.
homepage: https://github.com/dart-lang/dartdoc
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.6
  args: '>=1.5.0 <2.0.0'
  collection: ^1.2.0
  cli_util: ^0.1.3+2
  crypto: ^2.0.6
  html: '>=0.12.1 <0.15.0'
  # We don't use http_parser directly; this dep exists to ensure that we get at
  # least version 3.0.3 to work around an issue with 3.0.2.
  http_parser: '>=3.0.3 <4.0.0'
  logging: ^0.11.3+1
  process: ^3.0.5
  markdown: ^2.1.1
  meta: ^1.0.0
  mustache: ^1.1.0
  package_config: '>=0.1.5 <2.0.0'
  path: ^1.3.0
  pub_semver: ^1.3.7
  quiver: ^2.0.0
  resource: ^2.1.2
  stack_trace: ^1.4.2
  yaml: ^2.1.0

dev_dependencies:
  async: '>=2.0.8'
  build: ^1.3.0
  build_runner: ^1.10.0
  build_version: ^2.0.1
  coverage: ^0.13.0
  dhttpd: ^3.0.0
  glob: ^1.1.5
  grinder: ^0.8.2
  io: ^0.3.0
  http: ^0.12.0
  pedantic: ^1.9.0
  test: ^1.3.0

executables:
  dartdoc: null
```

## Expected behavior

With 13, a reasonable looking small set of dependencies was precompiled:

```
jcollins-macbookpro2:dartdoc jcollins$ pub global activate -spath .
Resolving dependencies... 
Got dependencies!
Precompiling executables... 
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled markdown:markdown.
Precompiled coverage:run_and_collect.
Precompiled coverage:collect_coverage.
Precompiled grinder:_boot.
Precompiled coverage:format_coverage.
Precompiled dhttpd:dhttpd.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.
Package dartdoc is currently active at path "/Users/jcollins/dart/dartdoc".
Installed executable dartdoc.
Activated dartdoc 0.32.1 at path "/Users/jcollins/dart/dartdoc".
jcollins-macbookpro2:dartdoc jcollins$ pub version
Pub 2.9.0-13.0.dev
```

## Actual behavior

Compare that to the current output:

```
jcollins-macbookpro2:dartdoc jcollins$ pub global activate -spath .
Resolving dependencies... 
Got dependencies!
Precompiling executables... 
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled grinder:init.
Precompiled grinder:init.
Precompiled grinder:grinder.
Precompiled grinder:grinder.
Precompiled markdown:markdown.
Precompiled markdown:markdown.
Precompiled markdown:markdown.
Precompiled markdown:markdown.
Precompiled coverage:run_and_collect.
Precompiled grinder:grinder.
Precompiled coverage:run_and_collect.
Precompiled coverage:run_and_collect.
Precompiled grinder:init.
Precompiled coverage:collect_coverage.
Precompiled coverage:collect_coverage.
Precompiled coverage:collect_coverage.
Precompiled coverage:run_and_collect.
Precompiled coverage:collect_coverage.
Precompiled markdown:markdown.
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled grinder:_boot.
Precompiled grinder:_boot.
Precompiled grinder:_boot.
Precompiled coverage:format_coverage.
Precompiled coverage:format_coverage.
Precompiled coverage:format_coverage.
Precompiled coverage:run_and_collect.
Precompiled coverage:format_coverage.
Precompiled dhttpd:dhttpd.
Precompiled markdown:markdown.
Precompiled dhttpd:dhttpd.
Precompiled dhttpd:dhttpd.
Precompiled grinder:grinder.
Precompiled grinder:_boot.
Precompiled grinder:init.
Precompiled coverage:collect_coverage.
Precompiled dhttpd:dhttpd.
Precompiled coverage:run_and_collect.
Precompiled markdown:markdown.
Precompiled grinder:_boot.
Precompiled coverage:collect_coverage.
Precompiled coverage:format_coverage.
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled dhttpd:dhttpd.
Precompiled coverage:collect_coverage.
Precompiled coverage:run_and_collect.
Precompiled markdown:markdown.
Precompiled grinder:_boot.
Precompiled coverage:format_coverage.
Precompiled dhttpd:dhttpd.
Precompiled coverage:format_coverage.
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled coverage:run_and_collect.
Precompiled grinder:_boot.
Precompiled coverage:collect_coverage.
Precompiled dhttpd:dhttpd.
Precompiled markdown:markdown.
Precompiled coverage:format_coverage.
Precompiled grinder:_boot.
Precompiled coverage:run_and_collect.
Precompiled grinder:grinder.
Precompiled coverage:collect_coverage.
Precompiled grinder:init.
Precompiled dhttpd:dhttpd.
Precompiled markdown:markdown.
Precompiled coverage:format_coverage.
Precompiled grinder:_boot.
Precompiled dhttpd:dhttpd.
Precompiled coverage:collect_coverage.
Precompiled coverage:run_and_collect.
Precompiled coverage:format_coverage.
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled grinder:_boot.
Precompiled dhttpd:dhttpd.
Precompiled markdown:markdown.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:graph_inspector.
Precompiled coverage:run_and_collect.
Precompiled build_runner:graph_inspector.
Precompiled coverage:collect_coverage.
Precompiled grinder:grinder.
Precompiled grinder:init.
Precompiled test:test.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled test:test.
Precompiled coverage:format_coverage.
Precompiled dhttpd:dhttpd.
Precompiled test:test.
Precompiled build_runner:graph_inspector.
Precompiled grinder:_boot.
Precompiled build_runner:build_runner.
Precompiled build_runner:build_runner.
Precompiled test:test.
Precompiled build_runner:build_runner.
Precompiled build_runner:build_runner.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
Precompiled test:test.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
Precompiled test:test.
Precompiled build_runner:build_runner.
Precompiled test:test.
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
Precompiled test:test.
Precompiled build_runner:build_runner.
Precompiled build_runner:build_runner.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.
Precompiled test:test.
Package dartdoc is currently active at path "/Users/jcollins/dart/dartdoc".
Installed executable dartdoc.
Activated dartdoc 0.32.1 at path "/Users/jcollins/dart/dartdoc".
jcollins-macbookpro2:dartdoc jcollins$ pub version
Pub 2.9.0-14.0.dev
```

While this does eventually complete on my laptop, it seems to grind to a halt on Travis (perhaps, excessive parallelism?) and nevertheless is way too much precompiling I think?

## --trace output

Not relevant... pub doesn't think anything bad happened so there is no trace output.
