### ISSUE TITLE
pubspec.lock file change between different regions and operating systems

### ISSUE THREAD

**Issue by afrueh** [dart-lang/pub#2580]
## Introduction

We have a global split environment that works on shared code base.

We check-in the main pubspec.lock file of the application and  do not checking the pubspec.lock files of the sub-packages of the project as then the changes would cause more changes after getting all packages in the application (Fetching the dependencies for the complete project can take over 30 minutes).

This is not a blocking issue but a little bothersome as it generates merge conflicts.

## Use case

`pubspec.lock` file into the repository but we experience continues changes in the main `pubspec.lock` file based on **operating system** or **region**.

### a) Relative path based package changes between OSX and Windows users:

```
example_package:
    dependency: transitive
    description:
      path: "modules/example-module"
      relative: true
    source: path
    version: "1.0.0"
```

**_`flutter pub get` on OSX:_**
`path: "modules/example-module"`
 
**_`flutter pub get `on Windows:_**
`path: "modules\\example-module`
 
#### Example: 
 
```
analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.39.13"
```

**_`flutter pub get `in China:_**
`url: "https://pub.flutter-io.cn"`

**_`flutter pub get `outside of China:_**
`url: "https://pub.dartlang.org"`

## Proposal

a) I guess it would be a possibility to make the path in the pubspec.lock file operating system independent and modify the path based on operating system while the dependencies are resolved

b) I guess a common pub URL that is available in all regions that forward to the region specific URLs would be possible
