### ISSUE TITLE
`pub --verbose get --no-precompile` hangs on dart 2.10.0

### ISSUE THREAD

**Issue by jmagman** [dart-lang/pub#2614]
From https://github.com/flutter/flutter/issues/63206 @kika:
>When it hangs `-v` shows the conflict, that is never output without `-v` and then it just sits there wasting CPU.

>Minimal repro case

<details>
  <summary>This one hangs</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.6
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

<details>
  <summary>This one errors out with conflict (as expected)</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.2
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

>The only difference is `meta: ^1.1.6` in first one and `meta: ^1.2.2` in the second

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.1 at /Volumes/ExtStripe/Scratch/flutter
    • Framework revision 2ae34518b8 (2 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 5s (mobile)                 • 0B3D73C5-1448-4647-A42E-5D37434D3126 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

• No issues found!  
</details>

>Also commented at https://github.com/dart-lang/pub/issues/2262#issuecomment-670611847

**Comment by jmagman** [comment]
I can reproduce.  `flutter pub get` is calling `pub --verbose get --no-precompile` which never exits:
```
[        ] SLVR:   derived: test >=1.15.3 <1.16.0-nullsafety or >=1.16.0-nullsafety.1
[        ] SLVR:   conflict: test >=1.16.0-nullsafety.1 depends on test_core 0.3.12-nullsafety.1
[        ] SLVR:   ! test >=1.16.0-nullsafety.1 is partially satisfied by test >=1.15.3 <1.16.0-nullsafety or >=1.16.0-nullsafety.1
[        ] SLVR:   ! which is caused by "if flutter_gherkin any and flutter_driver any from sdk then test_core 0.3.12-nullsafety or test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or test >=1.15.3 <1.16.0-nullsafety or >=1.16.0-nullsafety.1"
[        ] SLVR:   ! thus: if flutter_gherkin any and flutter_driver any from sdk then test_core 0.3.12-nullsafety or 0.3.12-nullsafety.1 or test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or test >=1.15.3 <1.16.0-nullsafety
[        ] SLVR:   ! not test_core 0.3.12-nullsafety or 0.3.12-nullsafety.1 is satisfied by not test_core >=0.3.8
[        ] SLVR:   ! which is caused by "test_core >=0.3.8 depends on analyzer ^0.39.5"
[        ] SLVR:   ! thus: if flutter_gherkin any and flutter_driver any from sdk then test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or test >=1.15.3 <1.16.0-nullsafety or analyzer ^0.39.5
[        ] SLVR:   ! not analyzer ^0.39.5 is satisfied by analyzer ^0.38.1
[        ] SLVR:   ! which is caused by "functional_data_generator >=0.3.0 depends on analyzer ^0.38.1"
[        ] SLVR:   ! thus: if flutter_gherkin any and flutter_driver any from sdk and functional_data_generator >=0.3.0 then test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or test >=1.15.3 <1.16.0-nullsafety
[        ] SLVR:   ! not test >=1.15.3 <1.16.0-nullsafety is satisfied by not test >=1.15.3 <1.16.0-nullsafety
[        ] SLVR:   ! which is caused by "test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18"
[        ] SLVR:   ! thus: if flutter_gherkin any and flutter_driver any from sdk and functional_data_generator >=0.3.0 then test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or 0.2.18
[        ] SLVR:   ! not test_api 0.2.14 or 0.2.15 or 0.2.16 or 0.2.17 or 0.2.18 is satisfied by test_api 0.2.19-nullsafety
[        ] SLVR:   ! which is caused by "every version of flutter_driver from sdk depends on test_api 0.2.19-nullsafety"
[        ] SLVR:   ! thus: one of flutter_gherkin any or flutter_driver any from sdk or functional_data_generator >=0.3.0 must be false
[        ] SLVR:   ! flutter_driver any from sdk is satisfied by flutter_driver any from sdk
[        ] SLVR:   ! which is caused by "myproject depends on flutter_driver any from sdk"
[        ] SLVR:   ! thus: flutter_gherkin is incompatible with functional_data_generator >=0.3.0
[        ] SLVR:   ! flutter_gherkin any is satisfied by flutter_gherkin any
[        ] SLVR:   ! which is caused by "myproject depends on flutter_gherkin any"
[        ] SLVR:   ! thus: functional_data_generator >=0.3.0 is forbidden
[        ] SLVR:   ! functional_data_generator >=0.3.0 is satisfied by functional_data_generator ^0.3.3
[        ] SLVR:   ! which is caused by "myproject depends on functional_data_generator ^0.3.3"
[        ] SLVR:   ! thus: version solving failed
```

**Comment by jonasfj** [comment]
Reprocuced: `flutter pub get` hangs for `pubspec.yaml`:
```yaml
name: myproject
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter_gherkin: any
  functional_data_generator: ^0.3.3
```

This hangs, but the logs end with `SLVR:   ! thus: version solving failed`.

Hence, I'm not sure if this is a `pub` issue or in flutter integration.
