### ISSUE TITLE
A git branch reference is not updated on pub get

### ISSUE THREAD

**Issue by Vanethos** [dart-lang/pub#2650]
**Note**
This was done with `flutter pub get`, and not `pub get` directly.

**Description**

I have 2 Dart projects: Project A and Project B.

- Project A is a package
- Project B is a Flutter app
- Project B depends on A via a git reference:

```dart
  flutter_repo_a:
    git:
      url: https://github.com/Vanethos/flutter_repo_a.git
      ref: master
```

If I commit further changes to repo A and run `flutter pub get`, the `pubspec.lock` is not upgraded with the latest version, so the following reference is left untouched:

```yaml
  flutter_repo_a:
    dependency: "direct main"
    description:
      path: "."
      ref: master
      resolved-ref: "635111088646b5a606e84a15f6265040ef3bb54f"
      url: "https://github.com/Vanethos/flutter_repo_a.git"
```

However, if I run `flutter pub upgrade`, it picks up the new commit reference, changing it to:

```yaml
  flutter_repo_a:
    dependency: "direct main"
    description:
      path: "."
      ref: master
      resolved-ref: "0942d3df9de28096b1d09e959c133e0cfb8e6cdd"
      url: "https://github.com/Vanethos/flutter_repo_a.git"
```

Is this the default behavior? 

If so, can I use 

`flutter pub upgrade flutter_repo_a` 

To update **only** that package without impacting the remaining packages?

Projects in question for testing:

https://github.com/Vanethos/flutter_repo_a
https://github.com/Vanethos/flutter_repo_b
