### ISSUE TITLE
[pub] `publish --dry-run` does NOT warning TODO in LICENSE while pub.dev forbids

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/pub#2743]
# Environment

- `pub version` or `flutter pub version`: Pub 2.11.0-213.1.beta
- OS version: macOS 10.15.7
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

When LICENSE file is
```markdown
TODO: Add your license here.
```

- `flutter pub publish -n` goes OK
- `flutter pub publish` fails with `LICENSE file "LICENSE" contains generic TODO.`

[pubspec.yaml](https://github.com/woodemi/quick_blue/blob/c31ab377fc40adb08adc0b1d7d516e6a51c84f40/quick_blue_platform_interface/pubspec.yaml)

```yaml
name: quick_blue_platform_interface
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/woodemi/quick_blue
repository: https://github.com/woodemi/quick_blue/tree/master/quick_blue_platform_interface

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
```

## Expected behavior

`flutter pub publish -n` warns about `LICENSE file "LICENSE" contains generic TODO.`

## Actual behavior

`flutter pub publish -n` goes OK

## --trace output

```
Could not find an option named "trace".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```
