### ISSUE TITLE
Pub get - ****** B A T C H  R E C U R S I O N exceeds STACK limits ******

### ISSUE THREAD

**Issue by thomaslc66** [dart-lang/pub#2775]
# Environment

- `pub version` or `flutter pub version`: The last one probably but got the error when running this command.
````
PS C:\Users\Thomas\Documents\flutter_mobidoc> pub version
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
````
- OS version: Windows 10 pro
- Are you using the Chinese community mirror or a corporate firewall? No.

# Problem

Shoud finish without 255 error.

## Actual behavior

Error stack trace using pub get --verbose
 
````
[  +76 ms] Page de codes active�: 65001
[   +1 ms] DESKTOP-8U21R64\Thomas
[+120448 ms] ***  La récursivité de la commande dépasse les limites de la pile ***
[   +3 ms] Nombre de récursions=317, Utilisation de la pile=90 pour-cent
[        ] ***       Le traitement  est abandonné       ***
[ +189 ms] Running "flutter pub get" in flutter_mobidoc... (completed in 120,7s, longer than expected)
[   +3 ms] "flutter run" took 121 463ms.
[   +9 ms] pub get failed (255; ***       Le traitement  est abandonné       ***)
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:335:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +246 ms] ensureAnalyticsSent: 242ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 255
````

Link to my first issue opened in the flutter package: https://github.com/flutter/flutter/issues/71285

I've been trying to install flutter for more than a week now.
So I've been installing flutter from all sources, uninstalling everything (even android studio and SDK) starting over using all branches from the flutter repository but I've always the same error in results.

Thank you in advance for your help.

**Comment by jonasfj** [comment]
> pub version or flutter pub version: The last one probably but got the error when running this command.

 * Is the error happening when you call `pub version`?
 * What about `pub --help` does that work?
 * Does `dart pub --help` work?
 * What does `dart --version` say?

If the error doesn't happen when calling `pub version`, then I'm curious to find what `pubspec.yaml` is causing problems for you.
 * Where did you run `pub get`? (what `pubspec.yaml` is in this folder?)
 * What version of `pub` did you use? Then one that comes with Flutter?

**Comment by thomaslc66** [comment]
Thank you for your response. 
I've posted the result of the command line: pub version in my first post.
But here you can find all the command line you asked me to run.

````
PS C:\Users\Thomas\Documents\flutter_mobidoc> pub version                                                                             Page de codes active : 65001                                                                                                          DESKTOP-8U21R64\Thomas                                                                                                                ***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
PS C:\Users\Thomas\Documents\flutter_mobidoc> pub --help
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
PS C:\Users\Thomas\Documents\flutter_mobidoc> dart pub --help
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 2c956a31c0a3d350827aee6c56bb63337c5b4e6e...
WARNING: Module BitsTransfer is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
PS C:\Users\Thomas\Documents\flutter_mobidoc> dart --version
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
Building flutter tool...
Running pub upgrade...
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
````

Here is the pubsec.yaml:
````
name: flutter_mobidoc
description: mobidoc

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

````


Based on the command line I run it seems that the dart was downloaded from flutter yes.
Let me know if you need anything else?
