### ISSUE TITLE
I couldn't pub get a package from gitlab repository that contains two packages

### ISSUE THREAD

**Issue by yukitaka13-1110** [dart-lang/pub#2853]
## version
Pub 2.11.0-174.0.dev

## Steps to Reproduce

I forked a package published to dartpub. 
[DartPub](https://pub.dev/packages/twilio_programmable_video)
[GitLab](https://gitlab.com/twilio-flutter/programmable-video)
This package contains `twilio_programmable_video` and `twilio_programmable_video_platform_interface`.
`twilio_programmable_video` depends on `twilio_programmable_video_platform_interface`  in the repository by relative path.
Tree is like this.
```
packages
    ├ packageA
        └ pubspec.yaml
    └ packageB
        └ pubspec.yaml
```

I rewrite `pubspec.yaml` as the following.

```yaml
dependency_overrides:
  twilio_programmable_video_platform_interface:
    git:
      url: ssh://git@gitlab.com/myname/programmable-video.git
      ref: master
      path: programmable_video_platform_interface
  twilio_programmable_video:
    git:
      url: ssh://git@gitlab.com/myname/programmable-video.git
      ref: master
      path: programmable_video
```

Then I tried to `flutter pub get` and failed with the following error.

```
Error on line 17, column 11: Invalid description in the "twilio_programmable_video" pubspec on the "twilio_programmable_video_platform_interface" dependency: "../programmable_video_platform_interface" is a relative path, but this isn't a local pubspec.
   ╷
17 │     path: ../programmable_video_platform_interface
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
```

My `pubspec.yaml` is wrong?
Is there another way to write it correctly?

**Expected results:** 
`flutter pub get` finish successfully.

**Actual results:** 
An error occurred when `flutter pub get`.

<details>
  <summary>Logs</summary>

```
$ flutter pub get


Error on line 17, column 11: Invalid description in the "twilio_programmable_video" pubspec on the "twilio_programmable_video_platform_interface" dependency: "../programmable_video_platform_interface" is a relative path, but this isn't a local pubspec.
   ╷
17 │     path: ../programmable_video_platform_interface
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
```

</details>

**Comment by sigurdm** [comment]
As the message says, it cannot solve relative paths in non-local pubspecs.

For your `twilio_programmable_video` fork I would change the pubspec.yaml to use an override instead of a path-dependency:
```yaml
dependencies:
  programmable_video_platform_interface: any
  ...

dependency_overrides:
  programmable_video_platform_interface:
     path: ../programmable_video_platform_interface
```

Try if that works!
