### ISSUE TITLE
Git dependencies path issue

### ISSUE THREAD

**Issue by felix-ht** [dart-lang/pub#2882]
# Environment

- `pub version` or `flutter pub version`: Pub 2.12.0-29.10.beta
- OS version: Ubuntu 20.04
- Are you using the Chinese community mirror or a corporate firewall? NO

# Problem

```yaml
name: pubspec_issue
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  parse_server_sdk: 
    git: 
      url: https://github.com/felix-ht/Parse-SDK-Flutter.git
      path: packages/dart

  parse_server_sdk_flutter: 
    git: 
      url: https://github.com/felix-ht/flutter-mapbox-gl.git
      path: packages/flutter

  mapbox_gl:
      git:
        url: https://github.com/felix-ht/flutter-mapbox-gl.git
        ref: fix-offline-region-method-channel-issue


dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
```

## Expected behavior

that this configuration uses works as expected

## Actual behavior

mapbox_gl git seems to "inherit" the path of the other git repo dependencies.  The same behavior shows up if dependency_overrides are used or dependency_overrides and normal dependencies are mixed. If i remove both  parse_server_sdk and parse_server_sdk_flutter everything is fine and pub searches for pubspec.yaml in mapbox_gl in the root folder.
If i add a path to mapbox_gl this gets used. However simple path like . or ./. also get replaced.

So the core issue is that if one git repository uses a specific path other git dependencies cannot have the pubspec.yaml in the root folder.

## --trace output

```
Could not find a file named "packages/flutter/pubspec.yaml" in https://github.com/felix-ht/flutter-mapbox-gl.git e841d298fd90a89155a6265e616a6b61a515d168.
```
