### ISSUE TITLE
pubspec.yaml should have a "latest" keyword for easy authoring

### ISSUE THREAD

**Issue by eseidel** [dart-lang/pub#2895]
I never remember what the right syntax is depending on the latest package.

I know "any" is discouraged, but I use it anyway, because it's convenient.

What if instead, there was a `latest` keyword (or similar) which just replaced with the correct syntax the first time it fetched?

That makes `pub get` no longer idempotent (not quite the right word, but I can't think of the right one?) with regards to pubspec.yaml, so maybe this instead belongs in the Editor plugins or some higher level user affordance?

Curious for your thoughts @devoncarew.  Feel free to close.  Just jotting down thoughts as I do some weekend hacking with Dart.

**Comment by eseidel** [comment]
Would also allow docs like this to be copyable:
https://flutter.dev/docs/development/data-and-backend/json#code-generation

```
dependencies:
  # Your other regular dependencies here
  json_annotation: <latest_version>

dev_dependencies:
  # Your other dev_dependencies here
  build_runner: <latest_version>
  json_serializable: <latest_version>
```
