### ISSUE TITLE
support git refs via pub global activate

### ISSUE THREAD

**Issue by DartBot** [dart-lang/pub#29]
<a href="https://github.com/kevmoo"><img src="https://avatars.githubusercontent.com/u/17034?v=3" align="left" width="96" height="96"hspace="10"></img></a> **Issue by [kevmoo](https://github.com/kevmoo)**
_Originally opened as dart-lang/sdk#23524_

---

pub global activate --source git [path] only supports the primary branch it seems.

No way to specify another rev/ref/etc

**Comment by sh4869** [comment]
Any updates on this?

**Comment by daniel-v** [comment]
I up this, would be a nice feature.

**Comment by PiN73** [comment]
If one is using some package for Dart/Flutter project, there is a workaround:

Instead of
```
$ flutter pub global activate package_name
$ executable_name
```

do this:
- In your project's pubspec.yaml file:
```
dev_dependencies:
  package_name:
    git:
      url: https://github.com/munificent/kittens.git
      ref: commit / branch / tag / etc
```
```
$ flutter pub get
```
```
$ flutter pub run package_name:executable_command
```

What is `executable_command`? You can find it out in the package_name's pubspec.yaml where it will be
```
executables:
  executable_name: executable_command
```
