### ISSUE TITLE
Null safety is not ignored when chrome test exectued

### ISSUE THREAD

**Issue by muzuro** [dart-lang/pub#2948]
# Environment

- `pub version` or `flutter pub version`: Pub 2.12.2
- OS version: Windows 10
# Problem

I am migrating webapp to dart 2.12.2. I am trying to execute test with command: `dart --no-sound-null-safety pub run test -p chrome`. But it fails like null safety still enabled.

Here is pubspec.yaml
```yaml
name: some
description: 
homepage: 
author: 
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^1.6.2
```

## Expected behavior

Test successfully executed

## Actual behavior

Test fails

## --trace output

```
Error: A library can't opt out of null safety by default, when using sound null safety.
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:test
 - package:test_core
 - package:fb_pixel
 - package:source_map_stack_trace
 - package:source_maps
 - package:test_api
 - package:stream_channel
 - package:js
 - package:path
 - package:stack_trace
 - package:source_span
 - package:async
 - package:term_glyph
 - package:meta
 - package:matcher
 - package:collection
 - package:boolean_selector
 - package:string_scanner
 - package:pedantic
 - package:pool
 - package:charcode

For solutions, see https://dart.dev/go/unsound-null-safety
Error: Compilation failed.
```
