### ISSUE TITLE
pubspec.lock paths are incompatible on Windows

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/pub#3012]
# Environment

```
Pub 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af
Dart SDK version: 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af (be) (Fri May 14 15:47:38 2021) on "windows_x64"
```

# Problem

When using `dart pub run build_runner build` (using the [`build_runner` package](https://pub.dev/packages/build_runner)), the command immediately crashed because:

```
Could not find a file named "pubspec.yaml" in "Pub\Cache\git\foo-<git-hash>\packages%5Cbar".
```

The `pubspec.yaml` for this package looks like this:

```yaml
dev_dependencies:
  foo:
    git:
      url: git@github.com:user/repo.git
      path: packages/bar
      ref: some-tag
```

The **generated** `pubspec.lock` for this package looks like this:

```
  foo:
    dependency: "direct dev"
    description:
      path: "packages\\bar"
      ref: "some-tag"
      resolved-ref: <git-tag>
      url: "git@github.com:user/repo.git"
    source: git
    version: "0.1.1"
```

And here it was immediately obvious to me: `packages\\bar` was the culprit.

## Expected behavior

1. The `path` in the `pubspec.lock` should be a forward slash (`packages/bar`) as the lock file should be version controlled for apps, which means that non-Windows users should use the same lock file.
2. The end result should be that `flutter pub run build_runner build` works :)

## Actual behavior

```
Could not find a file named "pubspec.yaml" in "Pub\Cache\git\foo-<git-hash>\packages%5Cbar".
```

## Workaround

I figured out a **workaround solution**:

1. **Manually** change the path from `packages\\bar` to `packages/bar` in the **`pubspec.lock`** file.
2. Success (`flutter pub run build_runner build` runs successfully).
