### ISSUE TITLE
HostedSource should check that `url` is valid!

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3024]
`HostedSource._parseDescription` should probably ensure that `description['url']`:
 * Can be parsed using `Uri.parse()` then catch and throw new `FormatException`, and,
 * Check that the parsed `Uri` has a scheme that is either `http` or `https`.

A `pubspec.yaml` like:
```yaml
name: myapp
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  retry:
    hosted:
      name: retry
      url: pub.dev  # <-- missing scheme
      version: ^3.0.0
```
causes:
```
Resolving dependencies... 
Bad state: Cannot use origin without a scheme: pub.dev/api/packages/retry
package:pub/src/source/hosted.dart 634:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 233:7           BoundHostedSource._fetchVersionsNoPrefetching
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 273:20          BoundHostedSource._fetchVersions
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 89:11  RateLimitedScheduler._processNextTask.runJob
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 98:5   RateLimitedScheduler._processNextTask
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                      Pool.withResource
This is an unexpected error. Please run

    dart pub --trace get 

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new 
```

Given that invalid URLs doesn't seem to work, I don't think it's a breaking change to add these checks.
