### ISSUE TITLE
Bad state: [BUG] firebase_messaging ^8.0.0-dev.7 is not satisfied.

### ISSUE THREAD

**Issue by mshamsi502** [dart-lang/pub#3028]
when i run `flutter pub get `, I get this result :
```
unning "flutter pub get" in mobile_jeanswest_app_android...     
Bad state: [BUG] firebase_messaging ^8.0.0-dev.7 is not satisfied.

package:pub/src/solver/partial_solution.dart 157:5  PartialSolution.satisfier

package:pub/src/solver/version_solver.dart 252:27   VersionSolver._resolveConflict

package:pub/src/solver/version_solver.dart 129:27   VersionSolver._propagate

package:pub/src/solver/version_solver.dart 93:11    VersionSolver.solve.<fn>

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 635:14           BoundHostedSource.withPrefetching.<fn>

===== asynchronous gap ===========================

package:pub/src/rate_limited_scheduler.dart 110:14  RateLimitedScheduler.withPrescheduling

===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 634:12           BoundHostedSource.withPrefetching

===== asynchronous gap ===========================

package:pub/src/solver/version_solver.dart 90:14    VersionSolver.solve

===== asynchronous gap ===========================

package:pub/src/entrypoint.dart 233:18              Entrypoint.acquireDependencies

This is an unexpected error. Please run



    dart pub --trace get --no-precompile



and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
exit code 1
```

**Comment by jonasfj** [comment]
@mshamsi502 thanks, this could be very interesting.
Can you share the minimal `pubspec.yaml` for reproducing this?

**Comment by mshamsi502** [comment]
@jonasfj  of course, thanks
my `pubspec.yaml` :
```

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  equatable: ^2.0.0
  flutter_bloc: ^7.0.0 
  easy_localization: ^3.0.0
  flutter_easyloading: ^3.0.0 
  flutter_keyboard_visibility: ^4.0.0
  flutter_phoenix: ^1.0.0
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  get_it: ^6.0.0
  pretty_dio_logger: ^1.1.1
  logging: ^0.11.3
  shared_preferences: ^2.0.4
  connectivity: ^3.0.2
  intent: ^1.4.0
  sqflite: ^2.0.0+2
  synchronized: ^3.0.0
  firebase_dynamic_links: any
  firebase_messaging: any
  cloud_firestore: any
  cupertino_icons: ^1.0.3
  percent_indicator: ^2.1.9+1
  sliding_up_panel: ^1.0.2
  flutter_svg: any
  flutter_html: ^2.0.0
  dotted_border: ^2.0.0
  fdottedline: ^1.0.1
  carousel_slider: ^3.0.0
  configurable_expansion_tile: ^1.0.0
  extended_text: ^7.0.0
  flutter_dialogs: ^1.1.0
  pinput: ^1.2.0
  drop_cap_text: ^1.1.3
  screenshot: ^0.3.0
  qr_flutter: ^4.0.0
  google_maps_flutter: ^0.5.27+3 
  location: ^3.0.2
  latlong: ^0.6.1
  geolocator: ^6.1.14
  geocoding: ^1.0.5
  geocoding_platform_interface: ^1.0.1
  search_map_place: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  build_runner: ^1.10.2

```

**Comment by jonasfj** [comment]
Hmm, I can't reproduce this bug, but I get an infinite loop (or at-least a very long one that I haven't seen the end of :rofl: ) when trying out:

```
name: _
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter_keyboard_visibility: 4.0.0
  shared_preferences: 2.0.6
  flutter_html: 2.0.0

  firebase_dynamic_links: '>=0.5.3 <=0.7.0+1'
  firebase_messaging: '>=7.0.3 <=9.0.0'
```

That's the minimal example I could create..
