### ISSUE TITLE
[pub get] Git error. Command: `git rev-list --max-count=1`

### ISSUE THREAD

**Issue by rockstar4095** [dart-lang/pub#3041]
I am getting the error, when trying to do pub get / pub upgrade:

```
Git error. Command: git rev-list --max-count=1 minor_changes
stdout: 
stderr: fatal: ambiguous argument 'minor_changes': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```

minor_changes - is the branch of my fork of bonfire package:

```
bonfire:
    git:
      url: https://github.com/rockstar4095/bonfire
      ref: minor_changes
```

It's not private. The most interesting thing is that this error does not occur on my other computer. Windows is installed on both machines. What could be the cause of the problem?

**Comment by mufle-tonmoy** [comment]
@rockstar4095 can you please try replacing the `ref` with the equivalent commit SHA (or it's abbreviation) for the branch/tag `minor_changes`?

**Comment by rockstar4095** [comment]
> @rockstar4095 can you please try replacing the `ref` with the equivalent commit SHA (or it's abbreviation) for the branch/tag HEAD of `minor_changes`?

I've tried it:
```
bonfire:
    git:
      url: https://github.com/rockstar4095/bonfire
      ref: c46542c1f23ca53de53f3bb3e45402cc203287fb
```

And it gave such output:

```
Git error. Command: `git rev-list --max-count=1 c46542c1f23ca53de53f3bb3e45402cc203287fb`
stdout: 
stderr: fatal: bad object c46542c1f23ca53de53f3bb3e45402cc203287fb
exit code: 128

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```

And with abbreviation it gives same "unknown revision or path not in the working tree" as before.
