### ISSUE TITLE
"pub add integration_test --sdk flutter" adds an entry with version: ^0.0.0 to pubspec

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#3046]
I'm not sure this is technically incorrect, but it seems a little superfluous (and something users may go and delete before committing :-)). If you run:

```
pub add integration_test --sdk flutter --dev
```

In a Flutter project, the entry is added with a version of 0.0.0:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: 
    sdk: flutter
    version: ^0.0.0 # <--
```

There's no `version` in the packages pubspec.yaml, so this may be correct, but it seems like it could probably be omitted (as the user would do if they added it themselves).
