### ISSUE TITLE
More Pubspec flexibility - Local Overrides and/or imports

### ISSUE THREAD

**Issue by rmtmckenzie** [dart-lang/pub#3088]
I've been thinking about this for a good long while but I haven't got around to opening a bug for it. The issue I'm dealing with is that I often end up doing work on dependencies locally on my machine.

This is easy enough to do with the `dependency_override` key. However, since this is in the same file, I then have to modify it every time I do a commit and have special checks in my CI to ensure that no development dependencies sneak in to the production build.

It would be very useful to be able to define a 'local-only' file which can overwrite parts of the pubspec.yaml - maybe something like pubspec.local.yaml, which wouldn't be committed. i.e.

```yaml
pubspec.yaml
  name
  description
  version
  dependencies:
    path_provider: ^2.0.1

pubspec.local.yaml
  dependency_overrides:
    path_provider:
      path: ../path_provider
```

There would of course have to be some rules about what could be overwritten - or maybe for simplicity, the two files would just be concatenated together (with keys being merged) and anything you defined in the local one couldn't be defined in the main one.

Another possibility would be the ability to include other .yaml files into the main pubspec i.e.

```yaml
pubspec.yaml
  name
  description
  
  version:
    from: version.yaml
    key: version
  # or
  !include version.yaml

  dependencies:
     ...
  
  dependency_overrides:
    from: overrides.yaml
```

I haven't fully thought through how that would work and it would mean using non-standard YAML (although there is some precedent for that). 

Any other ideas for how to do this would be greatly appreciated. I hate how a lot of stuff is done in Java, but property files and the configurability of the build system (especially with gradle) is really quite wonderful and one of the few things I think is missing from dart.

I'm also not 100% sure that this is the right place, or if it's a duplicate (although I didn't find anything); if either is the case let me know =).
