### ISSUE TITLE
How to fix Invalid version constraint error?

### ISSUE THREAD

**Issue by moonkmink** [dart-lang/pub#3150]
How can I fix this? When trying to run 'flutter pub get' it fails with the error 
```
Error on line 15, column 8 of pubspec.yaml: Invalid version constraint: Could not parse version "flutter". Unknown text at "flutter".

   ╷

15 │   sdk: flutter
   │        ^^^^^^^
   ╵
```
The respective part of my pubspec.yaml file looks like in this pic:
![image](https://user-images.githubusercontent.com/89242311/134814247-3a7ce7a7-829a-440d-b861-ccf47fc85ab0.png)

```
name: first_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/popcat1.png
    - assets/popcat2.png
```
Actually, I want to fix the below error in the pic and I think the above error cause the below error but I'm not sure.
![image](https://user-images.githubusercontent.com/89242311/134889445-bde29203-6a87-4f41-a3b9-e39dc1729cc5.png)

below error says >>
```
The argument type 'ChangeNotifierProvider<FormModel>' can't be assigned to the parameter type 'Widget'.dart(argument_type_not_assignable)
```

Thank you 

> ใครช่วยได้ขอให้ไม่ปวดหลัง ผมไม่ร่วง จาเรินๆ นะคะ  
#2322 #2386 #2656 #2752 #2805 #2915 #2805 #2911
