### ISSUE TITLE
`pub get` is much slower than it used to be.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/pub#3157]
# Environment

- `pub version` or `flutter pub version`: `Pub 2.15.0-156.0.dev`
- OS version: `Linux 5.10.46-4rodete1-amd64 #1 SMP Debian 5.10.46-4rodete1 (2021-08-20) x86_64 GNU/Linux`
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

Recently, the `pub get` command (at least through `flutter pub get`) has gotten a lot slower. As a Flutter dev, I run pub get on all the flutter projects in the flutter repo multiple times a day (via `flutter update-packages`), and it used to take ~1 second per directory, and now it is often 6-7 seconds per directory.

An example is the `dev/bots` directory in flutter/flutter, which has the following pubspec:

```yaml
name: tests_on_bots
description: Scripts which run on bots.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: 2.3.0
  crypto: 3.0.1
  flutter_devicelab:
    path: ../devicelab
  http_parser: 4.0.0
  meta: 1.7.0
  path: 1.8.0
  platform: 3.0.2
  process: 4.2.3
  test: 1.17.12

  _discoveryapis_commons: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  _fe_analyzer_shared: 26.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  analyzer: 2.3.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  archive: 3.1.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  async: 2.8.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  boolean_selector: 2.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  charcode: 1.3.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  checked_yaml: 2.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  cli_util: 0.3.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  collection: 1.15.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  convert: 3.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  coverage: 1.0.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  equatable: 2.0.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  file: 6.1.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  frontend_server_client: 2.1.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  gcloud: 0.8.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  glob: 2.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  googleapis: 3.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  googleapis_auth: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  http: 0.13.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  http_multi_server: 3.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  io: 1.0.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  js: 0.6.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  json_annotation: 4.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  logging: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  matcher: 0.12.11 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  metrics_center: 1.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  mime: 1.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  node_preamble: 2.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  package_config: 2.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  pedantic: 1.11.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  pool: 1.5.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  pub_semver: 2.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  pubspec_parse: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf: 1.1.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_packages_handler: 3.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_static: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_web_socket: 1.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_map_stack_trace: 2.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_maps: 0.10.10 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_span: 1.8.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  stack_trace: 1.10.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  stream_channel: 2.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  string_scanner: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  term_glyph: 1.2.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  test_core: 0.4.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  typed_data: 1.3.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  vm_service: 7.3.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  watcher: 1.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  web_socket_channel: 2.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  webkit_inspection_protocol: 1.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  yaml: 3.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dev_dependencies:
  test_api: 0.4.3

# PUBSPEC CHECKSUM: 9337
```

## Expected behavior

Running `flutter pub get` in this directory used to take less than a second, or at most, up to two seconds to complete.  Now it is often over 6s, although I've seen it take as little as 2s. The average time for `flutter update-packages` has gone from about 60s to about 250s.

Here's the output of `flutter pub get -v` in the `dev/bots` directory, which takes about 7.4 seconds:

```
[  +54 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ab51a0260d29d50800ae5c9665ecb01883a9b503
[        ] executing: [/usr/local/google/home/gspencer/code/flutter/] git tag --points-at ab51a0260d29d50800ae5c9665ecb01883a9b503
[  +21 ms] Exit code 0 from: git tag --points-at ab51a0260d29d50800ae5c9665ecb01883a9b503
[   +2 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git describe --match *.*.* --long --tags ab51a0260d29d50800ae5c9665ecb01883a9b503
[  +48 ms] Exit code 0 from: git describe --match *.*.* --long --tags ab51a0260d29d50800ae5c9665ecb01883a9b503
[        ] 2.6.0-11.0.pre-132-gab51a0260d
[  +17 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/usr/local/google/home/gspencer/code/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:gspencergoog/flutter.git
[  +92 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Downloading package sky_engine...
[ +214 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/sky_engine.zip md5 hash: GQruEgYvc+fW9vE3V090vQ==
[ +170 ms] Downloading package sky_engine... (completed in 378ms)
[   +6 ms] executing: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/sky_engine.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/pkg
[  +56 ms] Exit code 0 from: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/sky_engine.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/pkg
[   +2 ms] Downloading flutter_patched_sdk tools...
[ +112 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk.zip md5 hash: e3W6mYRFymY3ejmVoHLZQQ==
[ +507 ms] Downloading flutter_patched_sdk tools... (completed in 619ms)
[   +5 ms] executing: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/common
[  +99 ms] Exit code 0 from: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/common
[   +8 ms] Downloading flutter_patched_sdk_product tools...
[ +102 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk_product.zip md5 hash: /XoUuAo/sHn1ItgbPT0mSA==
[ +419 ms] Downloading flutter_patched_sdk_product tools... (completed in 522ms)
[   +5 ms] executing: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk_product.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/common
[ +100 ms] Exit code 0 from: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/flutter_patched_sdk_product.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/common
[   +7 ms] Downloading linux-x64 tools...
[ +103 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/artifacts.zip md5 hash: GxADx903oxfORtoGWHdz2A==
[+2105 ms] Downloading linux-x64 tools... (completed in 2,207ms)
[   +1 ms] executing: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/artifacts.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64
[ +563 ms] Exit code 0 from: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/artifacts.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64
[  +44 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] Downloading linux-x64/font-subset tools...
[  +88 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/font-subset.zip md5 hash: qmC/QHuNUPixHyE5yPe+vw==
[ +110 ms] Downloading linux-x64/font-subset tools... (completed in 199ms)
[   +1 ms] executing: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/font-subset.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64
[  +50 ms] Exit code 0 from: unzip -o -q /usr/local/google/home/gspencer/code/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/bccb3a57eb3ef0ff5ef1e041829b7afb187b9f7e/linux-x64/font-subset.zip -d /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64
[  +68 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +53 ms] Running "flutter pub get" in bots...
[   +3 ms] executing: [/usr/local/google/home/gspencer/code/flutter/dev/bots/] /usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose get --no-precompile
[  +43 ms] MSG : Resolving dependencies...
[  +10 ms] MSG : + _discoveryapis_commons 1.0.2
[        ]     | > _fe_analyzer_shared 26.0.0 (was 23.0.0)
[        ]     | > analyzer 2.3.0 (was 2.0.0)
[        ]     | > args 2.3.0 (was 2.2.0)
[        ]     | > async 2.8.2 (was 2.8.1)
[        ]     | + equatable 2.0.3
[        ]     | > frontend_server_client 2.1.2 (was 2.1.0)
[        ]     | + gcloud 0.8.3
[        ]     | + googleapis 3.0.0 (5.0.1 available)
[        ]     | + googleapis_auth 1.1.0
[        ]     | > logging 1.0.2 (was 1.0.1)
[        ]     | > matcher 0.12.11 (was 0.12.10)
[        ]     | + metrics_center 1.0.1
[        ]     | > package_config 2.0.2 (was 2.0.0)
[        ]     |   pedantic 1.11.1 (discontinued replaced by lints)
[        ]     | > platform 3.0.2 (was 3.0.0)
[        ]     | > pub_semver 2.1.0 (was 2.0.0)
[        ]     | > pubspec_parse 1.1.0 (was 1.0.0)
[        ]     |   shelf 1.1.4 (1.2.0 available)
[        ]     | > test 1.17.12 (was 1.17.10)
[        ]     | > test_api 0.4.3 (was 0.4.2)
[        ]     | > test_core 0.4.2 (was 0.4.0)
[        ]     | > vm_service 7.3.0 (was 7.1.1)
[        ] MSG : Changed 21 dependencies!
[  +87 ms] Running "flutter pub get" in bots... (completed in 2,316ms)
[ +111 ms] "flutter get" took 7,482ms.
[  +54 ms] ensureAnalyticsSent: 51ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

Here's the output of `flutter pub get -v` in the `dev/bots` directory with pub version `Pub 2.14.0-383.0.dev` from the Flutter `dev` branch, which takes about 1.6 seconds:

```
[  +52 ms] executing: uname -m
[  +25 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 225a43d941ddd1753765fec3682011e9ddffb11d
[        ] executing: [/usr/local/google/home/gspencer/code/flutter/] git tag --points-at 225a43d941ddd1753765fec3682011e9ddffb11d
[  +22 ms] Exit code 0 from: git tag --points-at 225a43d941ddd1753765fec3682011e9ddffb11d
[        ] 2.5.0-6.0.pre
[  +18 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'dev'
[  +55 ms] executing: [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +63 ms] Running "flutter pub get" in bots...
[   +7 ms] executing: [/usr/local/google/home/gspencer/code/flutter/dev/bots/] /usr/local/google/home/gspencer/code/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +64 ms] MSG : Resolving dependencies...
[   +7 ms] MSG : < _fe_analyzer_shared 23.0.0 (was 26.0.0) (26.0.0 available)
[        ]     | < analyzer 2.0.0 (was 2.3.0) (2.3.0 available)
[        ]     | < args 2.2.0 (was 2.3.0) (2.3.0 available)
[        ]     | < async 2.8.1 (was 2.8.2) (2.8.2 available)
[        ]     | < frontend_server_client 2.1.0 (was 2.1.2) (2.1.2 available)
[        ]     | < logging 1.0.1 (was 1.0.2) (1.0.2 available)
[        ]     | < matcher 0.12.10 (was 0.12.11) (0.12.11 available)
[        ]     | < package_config 2.0.0 (was 2.0.2) (2.0.2 available)
[        ]     |   pedantic 1.11.1 (discontinued replaced by lints)
[        ]     | < platform 3.0.0 (was 3.0.2) (3.0.2 available)
[        ]     | < pub_semver 2.0.0 (was 2.1.0) (2.1.0 available)
[        ]     | < pubspec_parse 1.0.0 (was 1.1.0) (1.1.0 available)
[        ]     |   shelf 1.1.4 (1.2.0 available)
[        ]     | < test 1.17.10 (was 1.17.12) (1.17.12 available)
[        ]     | < test_api 0.4.2 (was 0.4.3) (0.4.3 available)
[        ]     | < test_core 0.4.0 (was 0.4.2) (0.4.2 available)
[        ]     | < vm_service 7.1.1 (was 7.3.0) (7.3.0 available)
[        ]     | These packages are no longer being depended on:
[        ]     | - _discoveryapis_commons 1.0.2
[        ]     | - equatable 2.0.3
[        ]     | - gcloud 0.8.3
[        ]     | - googleapis 3.0.0
[        ]     | - googleapis_auth 1.1.0
[        ]     | - metrics_center 1.0.1
[        ] MSG : Changed 21 dependencies!
[  +23 ms] Running "flutter pub get" in bots... (completed in 1,410ms)
[  +83 ms] "flutter get" took 1,624ms.
[  +48 ms] ensureAnalyticsSent: 45ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

I did these checks in the same Flutter repo, on the same machine on a corporate network, swapping between Flutter `master` and `dev` branches, with the same `.pub-cache` that was already populated with the needed package versions.
