### ISSUE TITLE
Specifing a branch of a local git repository package in my `pubspec.yaml`

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/pub#3166]
Given I have a Dart/Flutter project that is using local a package (which is a git repository), I would like to specify a branch for that local package. For example I have the following development directory:

```
.
├── my_application
└── my_package
```

In my `my_package` I have a branch called `new-functionality`. I want to use the `new-functionality` branch *without* doing a git-checkout in the repository.

In `my_application/pubspec.yaml`, I would like to specify that local package and branch  along the lines of this:

```yaml
dependencies:
  my_package:
    git:
      url: ../my_package # I know this is not valid
      ref: new-functionality # the branch I would like to specify
```

In the Dart/Flutter [package dependency documentation](https://dart.dev/tools/pub/dependencies#git-packages) I couldn't find any way to achieve this with a git repository on my local machine.

---

For now, I am able to git-checkout the desired branch in that local repository and specify the path like a typical [path package](https://dart.dev/tools/pub/dependencies#path-packages):

```yaml
dependencies:
  my_package:
    path: ../my_package
```

**Comment by sigurdm** [comment]
I tried this locally, and for me everything seems to work fine:
```
name: blah

dependencies: 
  pub:
    git:
      url: ../other_package
      ref: feature_branch_name

environment:
  sdk: '>=2.12.0 <3.0.0'
```

What kind of error do you get?
