### ISSUE TITLE
Inconsistent behavior of dart pub global activate on Desktop and GitLab

### ISSUE THREAD

**Issue by Stargator** [dart-lang/pub#3290]
# Environment

- `pub version`: Pub 2.15.1
- OS version: N/A, I think Linux. It's the environment of a GitLab job
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

  Please describe the problem in detail, including the specific command that is
  failing.
  I'm running dart pub global activate junitreport --verbose

  But the executable tojunit is support to run `bin/tojunit.dart` which does not exist in the .pub-cache/global_packages/junitreport/. In face, junitreport does not have a `bin` directory.

> WARN: Warning: Executable "tojunit" runs "bin/tojunit.dart", which was not found in junitreport

  Was the problem with a specific package you were trying to fetch? junitreport

  If relevant, what does the `pubspec.yaml` file for your project look like: [pubspec.yaml](https://github.com/dart-lang/pub/files/7919268/pubspec.yaml.txt)

```yaml
environment:
  sdk: '>=2.15.0 <3.0.0'

executables:
  repomod: 0.0.1-alpha

dependencies:
  args: ^2.3.0
  dart_style: ^2.2.0
  logging: ^1.0.2
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  test: '<2.0.0'

```

## Expected behavior

I expected .pub-cache/global_packages/junitreport would have a bin directory and all other necessary files to allow the `tojunit` command to work properly.

I tested this locally on my MacOS and it works fine. As far as I can tell in the logs, running the above locally has **only** one section that does not exist in the GitLab job:

> MSG : Building package executables...
> IO  : Deleting directory /Users/Stargator/Workspace/GitLab/repomod/.pub_cache/global_packages/junitreport/bin.
> MSG : Built junitreport:tojunit.
> FINE: Building package executables finished (1.014s).

So I would expect to see the above output when running the command in a GitLab job

## Actual behavior

The .pub-cache/global_packages/junitreport directory is missing its bin directory and unable to allow the tojunit executable to run properly.

## --trace output

[job_output.txt](https://github.com/dart-lang/pub/files/7919264/job_output.txt)
