### ISSUE TITLE
Support environment version constraints when using `pub get`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub#3323]
Hello!

It seems that when pub is searching for a matching version of a package, it isn't taking `environment` constraints in mind.

Consider a machine that has Dart 2.8 installed, running pub get on a project with the following pubspec:

```yaml
environment:
  sdk: ">=2.8.0"

dependencies:
  foo:
```

Now consider that `foo` has two versions X and Y were Y > X

Version X has for pubspec:

```yaml
name: foo
version: X

environment:
  sdk: ">=2.8.0"
```

Version Y has for pubspec:

```yaml
name: foo
version: Y

environment:
  sdk: ">=2.16.0"
```

With the way package resolution currently works, it will always resolve to version Y. But that doesn't make sense, because the machine running `pub get` has Dart 2.8 installed, so Y is incompatible with this machine.

My request would be to add support for such scenario and detect that Y is incompatible, such that:
- if X matches the version constraints, resolve to X instead of Y
- if no version is found respecting both the dependencies and environment constraints, we have an error message similar to when there is a version conflict.
- is respected for transitive dependencies too, such that if a transitive requires 2.16.0 but 2.8.0 is installed, an error message should also appear
