### ISSUE TITLE
`Dart pub add` can leave trailing whitespace

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#3380]
Starting with this pubspec:
```yaml
name: blah
environment:
  sdk: ^2.10.0
```

Running:

```
dart pub add --dev lints
```

I get:

```yaml
name: blah
environment:
  sdk: ^2.10.0
dev_dependencies: 
  lints: ^1.0.1
```
Which has a trailing space at the line with `dev_dependencies: `.

Probably best to fix in package yaml_edit...
