### ISSUE TITLE
pub to support git dependency resolution

### ISSUE THREAD

**Issue by exvuma** [dart-lang/pub#3382]
## Request

Pub is able to resolve dependencies that use a git hash to specify a dependency

## Context

Our motivation on the Dependabot team is to have `pub`  be as well (if not better 😄 ) supported as other ecosystems. For example, npm, yarn, gomod, etc.. can use git URLs to upgrade dependencies. Note in  [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) pub is the ecosystem that does not support git deps

Not having this on pub causes problems for multiple use cases: 

* when private git dependency is included in the pubspec, currently pub is not able to resolve the dependency tree and therefore cannot update any dependencies.
* unable to reach the private dependency. the user will need to configure a private git registry in order for this to be possible though.

Thanks for working with us on this project. Let me know if you need more context or how we can help 

CC/ Dependabot engineers @jurre @mctofu

**Comment by jonasfj** [comment]
Current support for git-dependencies in `pubspec.yaml` is documented in:
https://dart.dev/tools/pub/dependencies#git-packages

In short, you write:
```yaml
dependencies:
  # This specifies dependency on package kittens from a git repository
  kittens:
    git:
      # Required, URL to the repository, this can also be https://...
      url: git@github.com:munificent/kittens.git
      
      # Optional, this can be a revision / branch / tag
      ref: main
      
      # Optional, path to package
      path: packages/kittens/

  # It is also possible to write a version constraint, but nobody does this.
  # And it doesn't really make sense, since we only ever try one commit
  # from the git-repository.
  #version: ^1.2.3
```

The hard part here is that `dart pub get/upgrade` will only ever try one revision from the git-repository. So version constraints and version numbers don't really matter for a git-dependency.

### When `ref` is a branch or omitted
When `ref` is a branch, or `ref`is not specified which is the same as specifying the default branch (`ref: main`).

Then `dart pub get` will use the revision from `pubspec.lock`, and if the lock file doesn't contain a revision, then it'll resolve the `ref` to a revision and use that.
Running `dart pub upgrade` will resolve `ref` and ignore the value in `pubspec.lock`.

This makes sense, and this kind of upgrade should be reasonably for `dependency_services` to support.

### When `ref` is a tag or commit-hash
Then resolving the `ref` always yields the same commit. So doing `dart pub get` or `dart pub upgrade` makes no difference.

**How can we upgrade in this scenario?** If we change the `ref` in the `pubspec.yaml` that not just a breaking upgrade, in this terminology it amounts to changing the source the package originates from -- so I'm not sure this is wise to do.


--------------------------------------

In practice many people probably just want the main branch, so maybe it's acceptable to not support upgrading `ref`. Or maybe we have to willing to break our own metaphors, and change `ref` when it is locked to a commit (not sure how tell if it's locked to a tag or a branch). 

@sigurdm thoughts?
