### ISSUE TITLE
Dependency is not up-to-date when using making changes in git repository

### ISSUE THREAD

**Issue by timosturm** [dart-lang/pub#3389]
# Environment

Dart version: `Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "linux_x64"`
Pub version: `Pub 2.16.2`

# Problem

When running `flutter pub get` the dependency does not contain recent changes from branch.

```yaml
  <dependency>:
    git:
      url: https://github.com/[...].git
      ref: <branch1>
```

# Example

+ Add dependency as shown in `.yaml`
+ Run `flutter pub get`
+ Commit change to `<branch1>`
+ Run `flutter pub get` or `flutter pub cache repair` or `flutter clean` or a combination of those commands.

Expected behavior: Up-to-date library from git is used.
Actual behavior: The old version is still used.

A work around is to change the `ref` tag, run `pub get` and change it back and run `pub get` again. But that is not a good solution.
