### ISSUE TITLE
`pub publish` false positive when using `pubspec_overrides.yaml`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub#3393]
# Problem

When using the new `pubspec_overrides.yaml` to override dependencies during dev:

```yaml
# pubspec_overrides.yaml
dependency_override:
  my_package:
    path: path/to/my_package
```

then trying to publish the package, pub complains with:

```
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
```

## Expected behavior

My understanding is that pubspec_overrides.yaml applies only during development (and not to published packages). As such, I'd expect this to be valid and publish to work
