### ISSUE TITLE
Incorrect colored output in the "outdated" command

### ISSUE THREAD

**Issue by davidmartos96** [dart-lang/pub#3459]
# Environment

- `pub version` or `flutter pub version`: Pub 2.17.1
- OS version: Fedora 35 64 bits
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

Hello,
I encountered with an edge case situation with the colored output of the `pub outdated` command. It only occurs on certain circumstances but I was able to create a simple pubspec.yaml to reproduce it.

```yaml
name: color_bug
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  purchases_flutter: ^3.9.3
  vector_math: ^2.1.0

dev_dependencies:
  build: ^2.0.1
  build_runner: ^2.1.8
  built_value_generator: ^8.0.4
  drift_dev: ^1.6.0

```

With Flutter 3.0.1, if I run `flutter pub outdated --color` I get the following output (img 1). 
But if a make a slight variation of the pubspec, like changing the dependency of `purchases_flutter` to `^3.10.0` then I get the output of the second image.
 
 
![image](https://user-images.githubusercontent.com/22084723/173025764-4c023eec-b89d-4115-9d2a-e479153f0ba5.png)

![image](https://user-images.githubusercontent.com/22084723/173026233-16be36fe-4732-4433-aab9-9a1c60e9f750.png)
