### ISSUE TITLE
'dart pub add xxxxxx' inserts json instead of yaml

### ISSUE THREAD

**Issue by rlsutton1** [dart-lang/pub#3476]
# Dart SDK version: 2.17.5 (stable) (Unknown timestamp) on "linux_x64"

- `pub version` or `flutter pub version`: 2.17.5
- OS version: Ubuntu 22.04
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

When the existing pubspec has no dependencies, 'dart pub add xxxxxx'  inserts json instead of yaml for the new dependency.

## Existing pubspec.yaml
```yaml
name: test
version: 0.0.1
description: A test
environment:
  sdk: '>=2.15.1 <3.0.0'
dev_dependencies:
  lint_hard: ^1.0.0
dependencies: 

```

## Expected behavior
```yaml
name: test
version: 0.0.1
description: A test
environment:
  sdk: '>=2.15.1 <3.0.0'
dev_dependencies:
  lint_hard: ^1.0.0
dependencies:
  path: ^1.8.2
```

## Actual behavior
```yaml
name: test
version: 0.0.1
description: A test
environment:
  sdk: '>=2.15.1 <3.0.0'
dev_dependencies:
  lint_hard: ^1.0.0
dependencies:  {path: ^1.8.2}


```

## --trace output

```
dart pub add path --trace
Resolving dependencies... 
  lint_hard 1.0.3 (2.0.0 available)
Got dependencies!

```
