### ISSUE TITLE
Getting wrong version package with open constraints

### ISSUE THREAD

**Issue by LinXunFeng** [dart-lang/pub#3489]
# Environment

- `flutter pub version`: Pub 2.16.2
- OS version: MacOS 12.4 (21F79)

# Problem

`my_base` is my private package. I want to install `version 1.0.5`

I publish version to `1.0.5` and the version constraints are shown below

```yaml
my_base: 
  version: ">=1.0.0 <1.1.0"
  hosted:
    url: http://xxx.xxx.xxx.xxx:yyyy/
```

When running `flutter pub upgrade`, it shows:

```
...
my_base 1.0.1 (was 1.0.0) (1.0.5 available)
...
```

I modify version constraint `1.0.0` to `1.0.2` and run `flutter pub upgrade` again, it works

```yaml
my_base: 
  version: ">=1.0.2 <1.1.0"
  hosted:
    url: http://xxx.xxx.xxx.xxx:yyyy/
```

```shell
...
my_base 1.0.5 (was 1.0.1)
...
```

Does anyone know why will getting a wrong version with using open constraint (`version: ">=1.0.0 <1.1.0"`)?

## Expected behavior

Installing `version 1.0.5` with using open constraint `version: ">=1.0.0 <1.1.0"`

## Actual behavior

Installing `version 1.0.1` with using open constraint `version: ">=1.0.0 <1.1.0"`
Installing `version 1.0.5` with using open constraint `version: ">=1.0.2 <1.1.0"`
