### ISSUE TITLE
Illegal scheme character when depending on git dependency

### ISSUE THREAD

**Issue by EstebanCardenas** [dart-lang/pub#3497]
Illegal scheme character error thrown when including a git dependency in the `pubspec.yaml` file.

Pubspec.yaml file:

```
name: app
description: app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  authentication:
    git:
      url: git@gitlab.com:app/ifp/modules/authentication.git
      ref: main
  dashboard: 
    git:
      url: git@gitlab.com:app/ifp/modules/dashboard.git
      ref: main
```

Error:

```
flutter pub get
Running "flutter pub get" in app...                         
Illegal scheme character (at character 4)
git@gitlab.com:app/ifp/modules/dashboard.git
```

Stack trace:

```
dart:core                                           Uri.parse
package:path/src/context.dart 1077:33               _parseUri
package:path/src/context.dart 1052:22               Context.prettyUri
package:path/path.dart 461:34                       prettyUri
package:pub/src/source/git.dart 276:16              GitSource._describeUncached
===== asynchronous gap ===========================
package:pub/src/source/git.dart 224:11              GitSource.doGetVersions.<fn>
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                       Pool.withResource
===== asynchronous gap ===========================
package:pub/src/source/git.dart 218:12              GitSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 186:20            SystemCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/package_lister.dart 82:31    PackageLister._versions.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/package_lister.dart 126:15   PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 336:14   VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 281:26                   minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 335:19   VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:18    VersionSolver.solve.<fn>
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 954:14           HostedSource.withPrefetching.<fn>
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 110:14  RateLimitedScheduler.withPrescheduling
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 953:12           HostedSource.withPrefetching
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 93:14    VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 280:16              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5               GetCommand.runProtected
```
