### ISSUE TITLE
pub outdated fails when overridden package has no hosted version

### ISSUE THREAD

**Issue by FaFre** [dart-lang/pub#3502]
I encounter the problem with pub 2.17.6 that pubspec_overrides.yaml is not taken into account for local (non-published) packages.

pubspec.yaml:
```yaml
dependencies:
  local_package: any
```
pubspec_overrides.yaml:
```yaml
dependency_overrides:
  local_package:
    path: ../../utils/local_package
```

Output of `dart pub outdated`:
`Package not available (could not find package local_package at https://pub.dartlang.org).`

On the other hand `dart pub upgrade` is working as expected and upgrades other dependencies accordingly. It also prints the warning that overrides are used:
`Warning: pubspec.yaml has overrides from pubspec_overrides.yaml`
