### ISSUE TITLE
[Feature request] Special pubspec key for hosted packages to avoid repetitive pub url

### ISSUE THREAD

**Issue by leoshusar** [dart-lang/pub#3518]
I would love to be able to write hosted packages without writing the pub server url again and again.
Instead of this:
```yaml
dependencies:
  package_1:
    hosted: https://my.pub.dev/
    version:  ^1.0.0
  package_2:
    hosted: https://my.pub.dev/
    version:  ^1.0.0
  package_3:
    hosted: https://my.pub.dev/
    version:  ^1.0.0
  package_4:
    hosted: https://another.pub.dev/
    version:  ^1.0.0
  package_5:
    hosted: https://another.pub.dev/
    version:  ^1.0.0
```

Maybe something like this:
```yaml
hosted_dependencies:
  https://my.pub.dev/:
    package_1: ^1.0.0
    package_2: ^1.0.0
    package_3: ^1.0.0
  https://another.pub.dev/:
    package_4: ^1.0.0
    package_5: ^1.0.0
```

As you can see, this would be much shorter and cleaner.

The reason I used separate `hosted_dependencies` and `hosted_dev_dependencies` is because I don't know if it would be possible to somehow "extend" `dependencies` in pub code (since it's just a list of packages) and I couldn't think of great way how to write it.
Or maybe like this?
```yaml
dependencies:
  hosted:
    https://my.pub.dev/:
      package_1:  ^1.0.0
    https://another.pub.dev/:
      package_2:  ^1.0.0
  regular_package: ^1.0.0
```

What do you think?
