### ISSUE TITLE
pubspec is generated in non human friendly form  (`{ }` json notation)

### ISSUE THREAD

**Issue by maximveksler** [dart-lang/pub#3530]
# Environment

- Dart version (run `dart --version`): `Dart SDK version: 2.17.6 (stable) (Unknown timestamp) on "linux_x64"`
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): `Ubuntu 21.04`
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

The result of `flutter pub add` results in pubspec yaml that is not human readble. 

Please see https://github.com/maximveksler/flutter_pubspec_bug_reproduce for a working reproduction scenario.

## Expected behavior

`dependencies:` section should be in yaml human friendly form.

```yaml
name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.8.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
```

## Actual behavior

`dependencies:` section is json normalized and is not pretty printed.

```yaml
name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"


dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
dependencies: {equatable: ^2.0.3, json_annotation: ^4.6.0, meta: ^1.8.0, uuid: ^3.0.6}
```

**Comment by maximveksler** [comment]
Applying the command in sequence does not produce the negative effect.

I.e. 
```
flutter pub remove equatable
flutter pub add equatable

flutter pub remove json_annotation
flutter pub add json_annotation

flutter pub remove meta
flutter pub add meta

flutter pub remove uuid
flutter pub add uuid
```

Produces a readble pubspec yaml (as exptected).

```yaml
name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.8.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
```
