### ISSUE TITLE
Dependency "dependency_overrides:" fails

### ISSUE THREAD

**Issue by alexisbg** [dart-lang/pub#3691]
Dart: 2.18.5
OS: WSL on Windows 10

A package **project_3** depends on **project_2** and **project_2** depends on **project_1**. The version of all of three is **1.0.0**. Here is [the sample repository](https://github.com/alexisbg/nested_path_deps). **project_2** and **project_3** have an dependency_overrides.

**project_2** pubspec.yaml:
```yaml
dependencies:
  project_1: ^1.0.0

dependency_overrides:
  project_1:
    path: ../project_1
    version: 1.0.0
```

**project_3** pubspec.yaml:
```yaml
dependencies:
  project_2: ^1.0.0

dependency_overrides:
  project_2:
    path: ../project_2
    version: 1.0.0
```

`dart pub get` works well with **project_2** but it fails with **project_3**:
```
Resolving dependencies...
Because project_2 1.0.0 from path depends on project_1 any which is forbidden, project_2 1.0.0 from path is forbidden.
So, because project_3 depends on project_2 1.0.0 from path, version solving failed.
exit code 69
```

It seems **project_3** ignores the **project_2** `dependency_overrides` or the **project_1** version number. A workaround is to comment **project_1** in `dependencies`:
```yaml
dependencies:
  # project_1: ^1.0.0

dependency_overrides:
  project_1:
    path: ../project_1
    version: 1.0.0
```

Did I miss something or make a mistake?

**Comment by sigurdm** [comment]
`dependency_overrides` are only counted at the root project of the revolution.

You would need to repeat the `project_1` override in the `pubspec.yaml` for `project_3`.

By the way, you also don't have to mention the version number in the override.

```yaml
dependencies:
  project_2: ^1.0.0

dependency_overrides:
  project_1:
    path: ../project_1
  project_2:
    path: ../project_2
```
