### ISSUE TITLE
Pub dependency constraint resolver overconstraint

### ISSUE THREAD

**Issue by Pante** [dart-lang/pub#3721]
# Environment

- Flutter 3.3.10/Dart 2.18.6

# Problem
Given the following pubspec:
```yml
environment:
  flutter: '>=3.3.0'
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  awesome_notifications: ^0.7.4+1
  intl: ^0.18.0
```

Dependencies fail to be resolved with the following error message:
```
Because <app>depends on awesome_notifications ^0.7.4+1 which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because <app> depends on intl ^0.18.0, version solving failed.
```

## Expected behavior
The dependency should be resolved since `^0.18.0` always satisfies `^0.17.0`. It seems really strange that dependency resolution fails in this particular case. In my opinion, this defeats the purpose of allowing dependency ranges.
