### ISSUE TITLE
dart pub outdated shows invalid message when pubspec.lock contains a retracted version of a package

### ISSUE THREAD

**Issue by maRci002** [dart-lang/pub#3874]
https://pub.dev/packages/shared_preferences_android/versions has a retraced version: [2.1.1](https://pub.dev/packages/shared_preferences_android/versions/2.1.1)

`pubspec.lock`

```
  shared_preferences_android:
    dependency: transitive
    description:
      name: shared_preferences_android
      sha256: "1bc5d734b109c327b922b0891b41fc51483ccbd53c0d19952b7e230349a5d90b"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
```

Running `dart pub outdated` / `flutter pub outdated`:

```
Showing outdated packages.
[*] indicates versions that are not the latest available.              
                                                                       
Package Name                Current   Upgradable  Resolvable  Latest   
                                                                       
direct dependencies:                                                   
collection                  *1.17.0   *1.17.0     *1.17.0     1.17.1   
intl                        *0.17.0   *0.17.0     *0.17.0     0.18.0   
                                                                       
dev_dependencies: all up-to-date.                                      

transitive dependencies:   
async                       *2.10.0   *2.10.0     *2.10.0     2.11.0
characters                  *1.2.1    *1.2.1      *1.2.1      1.3.0
js                          *0.6.5    *0.6.5      *0.6.5      0.6.7
matcher                     *0.12.13  *0.12.13    *0.12.13    0.12.15
material_color_utilities    *0.2.0    *0.2.0      *0.2.0      0.3.0
meta                        *1.8.0    *1.8.0      *1.8.0      1.9.1
path                        *1.8.2    *1.8.2      *1.8.2      1.8.3
shared_preferences_android  *2.1.1    2.1.0       2.1.0       2.1.0
source_span                 *1.9.1    *1.9.1      *1.9.1      1.10.0
test_api                    *0.4.16   *0.4.16     *0.4.16     0.5.1
win32                       *3.1.4    *3.1.4      *3.1.4      4.1.3

transitive dev_dependencies:
cli_util                    *0.3.5    *0.3.5      *0.3.5      0.4.0
pub_updater                 *0.2.4    *0.2.4      *0.2.4      0.3.0

1 upgradable dependency is locked (in pubspec.lock) to an older version.
To update it, use `dart pub upgrade`.
```

When running `dart pub upgrade` nothing happens.
