### ISSUE TITLE
Package validation found the following potential issue: * 2 checked-in files are ignored by a `.gitignore`. linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux   linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux

### ISSUE THREAD

**Issue by indratrisnar** [dart-lang/pub#3941]
# Environment

- Dart version (run `dart --version`): 3.0.0
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): windows 11
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem
I created a new package and used package shared_preferences in it.
when I run "dart pub publish --dry-run", a warning occurs when validating the package.

```yaml
name: d_session
description: Easy way to access Shared Preference and use as Session.
version: 0.0.1
homepage: https://github.com/indratrisnar/d_session

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

```

## Expected behavior
0 warning, ready to publish

## Actual behavior
show 1 warning

## --trace output

```
Validating package... (1.7s)
Package validation found the following potential issue:
* 2 checked-in files are ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.

  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore

  Files that are checked in while gitignored:

  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux

Package has 1 warning.
```
