### ISSUE TITLE
Proposal: `package_incompatibilities.yaml` in the Dart SDK

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3962]
The general idea is that in the root of the Dart SDK we should introduce a `package_incompatibilities.yaml` file.
It should sit next to the existing `version` and `revision` files, and it should be explained in the [README.md](https://github.com/dart-lang/sdk/blob/main/README.dart-sdk) file.

The `package_incompatibilities.yaml` file should have the following form:
```yaml
incompatibilities:
- package: foo
  ranges:
  - >=3.0.0 <3.1.0
  reason: |-
    Libraries opt-out of null-safety using language version marker.
- package: bar
  ranges:
  - 1.0.0
  - 1.2.0
  reason: |-
    Relies on APIs that were removed in Dart 3.0.0
```

In essences the file would allow SDK developers to declare specific package versions to be incompatible with future versions of the Dart SDK.

**Behavior**:
 * If a _package version_ matching `package_incompatibilities.yaml` is in `pubspec.lock` then using it is fine.
 * Otherwise, `dart pub get` should never allow a _package version_ matched in `package_incompatibilities.yaml`.
 * If a conflict arises, then the "reason" from `package_incompatibilities.yaml` can be surfaced.

**Use cases**:
 * We've removed a deprecated API or feature that only affects a few packages.
 * We're using an experimental feature and published with SDK constraint `^3.1.0-dev` instead of `>=3.1.0-dev <3.1.0` (and we regret it because the experimental feature was changed).

-----------------

Whether we'd frequently want to use this functionality I don't know, I recall a few cases where it would have been a nice tool. I don't envision us wanting to use this frequently or at scale.

Mostly, I'm writing this proposal, so that we can consider implementing it should become relevant in the future.
