### ISSUE TITLE
Null-check crash in packagegraph

### ISSUE THREAD

**Issue by FBot1** [dart-lang/pub#3967]
# Environment

- Dart version (run `dart --3.0.5`):
- OS linuxlite 6.0:
- Are you using the Chinese community mirror or a corporate firewall? I dont know

# Problem
 I cant create a file when I run a command line and its needed to complete this task Im practicing in https://gallery.flutter.dev/#/demo/app-bar,
 when I tried to compile the code seems like some files need to be imported but I cant generate the file please help 

```yaml
<copy/paste pubspec.yaml>
```name: app2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_gen: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


## Expected behavior

<!--
  What did you expect the result of the command to be?
-->create an automatic file

## Actual behavior

<!--
  What actually happened?
-->

## --trace output

```
<copy/paste the full output>
```
Deprecated. Use `dart run` instead.
Null check operator used on a null value
package:pub/src/package_graph.dart 70:55  PackageGraph.transitiveDependencies.<fn>.<fn>
dart:core                                 Iterable.toSet
package:pub/src/package_graph.dart 70:58  PackageGraph.transitiveDependencies.<fn>
package:pub/src/utils.dart 661:41         mapMap
package:pub/src/package_graph.dart 67:11  PackageGraph.transitiveDependencies
package:pub/src/package_graph.dart 96:12  PackageGraph.isPackageMutable
package:pub/src/executable.dart 96:33     runExecutable
===== asynchronous gap ===========================
package:pub/src/command/run.dart 100:20   RunCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    /home/fr/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
