### ISSUE TITLE
Introduce `$FLUTTER_ROOT/sdk-packages.yaml`

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3980]
When looking for `sdk: flutter` sdk-packages today, we do:
https://github.com/dart-lang/pub/blob/98565c3e5defcd80c59910795ba3548552102f2c/lib/src/sdk/flutter.dart#L81-L95

Effectively, we search for `<packageName>` in (ordered by preferences):
 * `$FLUTTER_ROOT/packages/<packageName>`
 * `$FLUTTER_ROOT/bin/cache/pkg/<packageName>`

Instead of having multiple search paths hardcoded in `pub`, I propose that we introduce an `sdk-packages.yaml` file.

```yaml
# Declaration of SDK-packages supplied by the Flutter SDK.
# An SDK-package is a package that the user can depend on
# using a dependency constraint like:
#
#         dependencies:
#           flutter_test:
#             sdk: flutter
#
# Paths in the list below are relative to this file.
sdk: flutter
packages:
- name: flutter
  path: packages/flutter
- name: flutter_test
  path: packages/flutter_test
- name: sky_engine
  path: bin/cache/pkg/sky_engine
```

## Migration

1. `dart pub` will read `sdk-packages.yaml` when present, and fallback to existing logic
   when no `sdk-packages.yaml` file is present.
2. `pub` is rolled into the Dart SDK.
3. Flutter SDK starts supplying a `sdk-packages.yaml` file.
4. `dart pub` will refuse detect a valid Flutter SDK, unless `sdk-packages.yaml` is present.

## Open questions

 * We could bike-shed the name further, I'm open to ideas, `sdk-packages.yaml` just seemed natural.
 * Should we use a `.json` file instead, it would arguably be a tiny bit faster, but we wouldn't be able to have comments.

-----------------

@sigurdm, Do you agree that this would be cleaner from a `pub` perspective? And pretty easy to do?

@jonahwilliams, any thoughts? is there anyone else you think we should run this past?

@christopherfujino, any thoughts? Is it intentional that `flutter_tools` is something that Flutter Apps can take a dependency on? If it doesn't have an API that you intend to expose, this could possibly offer a mechanism that would allow you to make it private.
