### ISSUE TITLE
Forbidden to import http from path:

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#3983]
(This is current HEAD of pub)

```
name: sample
environment:
  sdk: ^3.0.0
dependencies:
  http:
   path: ../pub # Contains package:pub
```

```
dart ~/projects/pub/bin/pub.dart get
Resolving dependencies... 
Because sample depends on http from path which is forbidden, version solving failed.
```

Not really clear what is forbidden and why...

If I change the name of the dependency:
```
name: sample
environment:
  sdk: ^3.0.0
dependencies:
  blah:
   path: ../pub
```
I get the expected failure:

```
> dart pub get
Resolving dependencies... (1.6s)
Error on line 6, column 4 of pubspec.yaml: Expected to find package "blah", found package "pub".
  ╷
6 │    path: ../pub
  │    ^^^^^^^^^^^^
  ╵
```

Not sure why http is special here...
