### ISSUE TITLE
Allow the use of different dependency following build environment

### ISSUE THREAD

**Issue by geosebas** [dart-lang/pub#4034]
I have the following problem, I'm currently developing 2 apps in Flutter, both depends on a package that I develop too, called `shared_libs` for the example. Problem here is that when I need to work on a feature that include modification in both the app and the `shared_libs` packages.

Here what I currently have in my `pubspec.yaml`:

```yaml
dependencies:
  shared_libs:
    git:
      url: https://gitlab.com/xxx/shared_libs.git
  # shared_libs:
  #   path: ../shared_libs
```

So, I need to change the `pubspec.yaml` file each time before each work session, and change back when I want to commit changes.

I tried looking for a solution for this, but was unable to find anything.

I was naively hoping for something like this  
```yaml
dependencies:
  shared_libs:
    debug:
      path: ../shared_libs
    git:
      url: https://gitlab.com/xxx/shared_libs.git

```
or 
```yaml
dependencies:
  shared_libs:
    git:
      url: https://gitlab.com/xxx/shared_libs.git
debug_dependencies:
  shared_libs:
    path: ../shared_libs
```

But it seems I was hoping for nothing.
Beside pre/after commit script, I don't have any idea.

Do anyone here have another solution ? Maybe allow to build with a specified `pubspec.yaml` ?

Thanks a lot !
