### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub#4049]
There are many packages that need a special setup for them to work properly. For example `freezed` needs [all these steps](https://pub.dev/packages/freezed#install), some are normal dependencies, some are dev dependencies and some are optional.

I think this could be automated by adding a `install_steps` into the library's `pubspec.yaml`, and when we call `dart pub add` it will check if there are any `install_steps` defined there, and if positive, add all needed dependencies.

It could look like this:

```yaml
install_steps:
  - flutter:
    - freezed_annotation
    -  build_runner: dev
    - freezed: dev
    - json_annotation: optional
    - json_serializable:
      - dev
      - optional: 'for adding json serialization'
```

Then `pub add` could ask if the optional should be added and show the optional item's message like:

> Do you want to add json_serializable for adding json serialization? y/N

With this feature, we don't have to go to pub's webiste every time we need to add a package, just to check how we are supposed to install it. This would also fixes the `Installing` tab at pub.dev, that actually doesn't reflect the reality of many packages.
