### ISSUE TITLE
Package Publish Fails (Possibly Involving Symlinks)

### ISSUE THREAD

**Issue by getBoolean** [dart-lang/pub#4057]
# Environment

- Dart version (run `dart --version`): `3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "windows_x64"`
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): Windows 11 Pro, version 23H2 build 22631.2715
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem

I'm attempting to run `dart pub publish --dry-run` in my [dart_holodex_api](https://github.com/getBoolean/dart_holodex_api) repo, but I am getting an error. I am using Puro here, but @pingbird was able to [reproduce without puro](https://github.com/pingbird/puro/issues/61#issuecomment-1826411458)

```yaml
name: dart_holodex_api
description: A Dart wrapper for ...
version: 2.0.0
homepage: https://github.com/getBoolean/dart_holodex_api
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ">=0.13.4 <2.0.0"
  intl: ">=0.17.0 <0.19.0"
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  dotenv: ^4.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lints: "^3.0.0"
  test: ^1.16.0
```

## Expected behavior

The publish command should work when symlinks are involved.

## Actual behavior

The publish command seems to fail because of a symlink. @pingbird was able to reproduce it when the repo was inside a symlink (see https://github.com/pingbird/puro/issues/61#issuecomment-1826411458), but that is still odd because I do not have the repo in a symlink.

PowerShell script to check for symlinks:
```
$ ((get-item B:\dev).Attributes.ToString())
Directory
$ ((get-item B:\dev\GitHub).Attributes.ToString())
Directory
$ ((get-item B:\dev\GitHub\dart_holodex_api).Attributes.ToString())
Directory
```

## --trace output

```
$ dart pub publish --dry-run --trace
Resolving dependencies... 
Got dependencies!
Invalid argument (beneath): ../../../../dev/GitHub/dart_holodex_api: "must be relative and normalized"
package:pub/src/ignore.dart 229:7         Ignore.listFiles
package:pub/src/package.dart 232:19       Package.listFiles
package:pub/src/command/lish.dart 268:33  LishCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\Boolean\.puro\shared\pub_cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```

[pub_log.txt](https://github.com/dart-lang/pub/files/13465194/pub_log.txt)
