### ISSUE TITLE
Dependency overrides cannot override dependency errors

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#4139]
## Actual behavior

```
Error on line 17, column 11: Invalid description in the "native_assets_builder" pubspec on the "native_assets_cli" dependency: "../native_assets_cli/" is a relative path, but this isn't a local pubspec.
```

With the root `pubspec.yaml` from `flutter_tools`:

```yaml
name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/wiki/Updating-dependencies-in-Flutter
  archive: 3.3.2
  args: 2.4.2
  browser_launcher: 1.1.1
  dds: 3.1.2
  dwds: 23.3.0
  completion: 1.0.1
  coverage: 1.7.2
  crypto: 3.0.3
  file: 7.0.0
  flutter_template_images: 4.2.0
  html: 0.15.4
  http: 0.13.6
  intl: 0.18.1
  meta: 1.12.0
  multicast_dns: 0.3.2+6
  mustache_template: 2.0.0
  package_config: 2.1.0
  process: 5.0.2
  fake_async: 1.3.1
  stack_trace: 1.11.1
  usage: 4.1.1
  webdriver: 3.0.3
  webkit_inspection_protocol: 1.2.1
  xml: 6.5.0
  yaml: 3.1.2
  native_stack_traces: 0.5.6
  shelf: 1.4.1
  vm_snapshot_analysis: 0.7.6
  uuid: 3.0.7
  web_socket_channel: 2.4.3
  stream_channel: 2.1.2
  shelf_web_socket: 1.0.4
  shelf_static: 1.1.2
  pub_semver: 2.1.4
  pool: 1.5.1
  path: 1.9.0
  mime: 1.0.5
  logging: 1.2.0
  http_multi_server: 3.2.1
  convert: 3.1.1
  async: 2.11.0
  unified_analytics: 5.8.1

  cli_config: 0.1.2
  graphs: 2.3.1
  # TODO(dacoharkes): Publish and bump
  native_assets_builder: 0.3.2
  native_assets_cli: 0.4.2

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.7.0
  test_core: 0.6.0

  vm_service: 14.0.0

  standard_message_codec: 0.0.1+4

  _fe_analyzer_shared: 67.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  analyzer: 6.4.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  boolean_selector: 2.1.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  built_collection: 5.1.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  built_value: 8.9.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  clock: 1.1.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  csslib: 1.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  dap: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  dds_service_extensions: 1.7.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  devtools_shared: 6.0.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  extension_discovery: 2.0.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  fixnum: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  frontend_server_client: 3.2.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  glob: 2.1.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  http_parser: 4.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  io: 1.0.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  js: 0.6.7 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  json_rpc_2: 3.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  matcher: 0.12.16+1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  petitparser: 6.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  platform: 3.1.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_packages_handler: 3.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  shelf_proxy: 1.0.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_map_stack_trace: 2.1.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_maps: 0.10.12 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  source_span: 1.10.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  sse: 4.1.4 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  string_scanner: 1.2.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  sync_http: 0.3.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  term_glyph: 1.2.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  typed_data: 1.3.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  vm_service_interface: 1.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  watcher: 1.1.0 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  web: 0.4.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  yaml_edit: 2.1.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dev_dependencies:
  collection: 1.18.0
  file_testing: 3.0.0
  pubspec_parse: 1.2.3

  checked_yaml: 2.0.3 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  json_annotation: 4.8.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  node_preamble: 2.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  test: 1.25.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

# TODO(dacoharkes): Remove
dependency_overrides:
  native_assets_builder:
    git:
      url: https://dart.googlesource.com/native
      ref: b5d409cfae689a67cc0f4c5dba62a816692022b3
      path: pkgs/native_assets_builder
  native_assets_cli:
    git:
      url: https://dart.googlesource.com/native
      ref: b5d409cfae689a67cc0f4c5dba62a816692022b3
      path: pkgs/native_assets_cli

dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true
# PUBSPEC CHECKSUM: 980d
```

The `pubspec.yaml` that is being complained about:

```yaml
name: native_assets_builder
description: >-
  This package is the backend that invokes top-level `build.dart` scripts.
version: 0.4.0-wip
repository: https://github.com/dart-lang/native/tree/main/pkgs/native_assets_builder

environment:
  sdk: '>=3.0.0 <4.0.0'

publish_to: none

dependencies:
  graphs: ^2.3.1
  logging: ^1.2.0
  # native_assets_cli: ^0.4.1
  native_assets_cli:
    path: ../native_assets_cli/
  package_config: ^2.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  file_testing: ^3.0.0
  test: ^1.24.3

```

## Expected behavior

The dependency overrides would mean that the relative path dependency is the other pubspec.yaml is completely ignored.

@jonasfj @sigurdm Am I missing something about how dependency_overrides are supposed to work? It seems to me that I should be able to import a bunch of WIP non published packages and test them downstream together with dependency overrides.
