### ISSUE TITLE
Entry error, can not include space in path ?

### ISSUE THREAD

**Issue by Dynesshely** [dart-lang/pub#4221]
# Environment

- Dart version (run `dart --version`):
  - Dart SDK version: 3.3.3 (stable) (Tue Mar 26 14:21:33 2024 +0000) on "windows_x64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):
  - Windows 11 23H2 (22631.3447)
- Are you using the Chinese community mirror or a corporate firewall?
  - Nope, I'm using proxy with default pub source

# Problem

When run `dart pub publish`, the console output error is:

```text
Invalid argument(s): Entry E:\Development\Projects\Crequency\KitX\KitX Standard\KitX%20Shared\KitX.Shared.Dart\kitx_shared_dart is not inside E:\Development\Projects\Crequency\KitX\KitX Standard\KitX Shared\KitX.Shared.Dart\kitx_shared_dart.
package:pub/src/io.dart 1125:9  createTarGz.<fn>
This is an unexpected error. The full log and other details are collected in:

    C:\Users\Dynesshely\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```

And I'm gussing is the `createTarGz` function doesn't think the path with `%20` is not equals to ` ` ?

My project yaml file is:

```yaml
name: kitx_shared_dart
description: A port of KitX.Shared in dart
version: 3.24.10+6873
repository: https://github.com/Crequency/KitX-Standard/KitX.Shared.Dart/

environment:
    sdk: ^3.3.0

dependencies:
    built_collection: ^5.1.1
    built_value: ^8.9.1

dev_dependencies:
    lints: ^3.0.0
    test: ^1.24.0
    # Run `dart run build_runner build` to generate `.g.dart` files.
    # You can also execute `build_runner.ps1` with pwsh to run the command.
    build_runner: ^2.4.9
    built_value_generator: ^8.9.1
```

## Expected behavior

The library will be normally publish to pub.dev

## Actual behavior

Failed at compressing.

## --trace output

I attached the `pub_log.txt`

[pub_log.txt](https://github.com/dart-lang/pub/files/14969493/pub_log.txt)
