### ISSUE TITLE
Pub global activate with local path sometimes has no effect

### ISSUE THREAD

**Issue by matthew-carroll** [dart-lang/pub#4295]
# Environment

- Dart version (run `dart --version`):

```
Dart SDK version: 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "macos_arm64"
```

- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):

macOS 14.3.1

- Are you using the Chinese community mirror or a corporate firewall?

No

# Problem
I maintain a CLI package. There's the published version on Pub, and then there's version that I work on locally.

When I want to activate the Pub version, I use `dart pub global activate static_shock_cli`.

When I want to activate the local version, I set the current working directory to where that package is defined and then I run `dart pub global activate --source=path .`

## Expected behavior
When I activate the local version, the local version should run when I issue commands.

## Actual behavior
The Pub version continue to be run when I try execute commands.

## Details
On a seemingly random basis, I'm unable to effectively activate my local version. There's no error when I try to activate my local version. The output suggests success. However, when I go to run the tool, it clearly doesn't have any of my local changes - it's still running the version from Pub.

When this happens, I also explicitly run `dart pub global deactivate static_shock_cli` before then trying again to activate the local version. This has no effect. Pub somehow still ends up executing the Pub version, which I just told it to deactivate.

I've discovered that if I delete all the references I can find in my Pub cache for this package, then I can get Pub to truly activate my local version. But that's the level of intervention it seems to take to get this working.

One final detail is that I primarily work with Flutter. That's where my Dart distribution comes from. I occasionally switch between the `master` branch and `stable` branch of Flutter. It's possible that at times I end up activating the local version of my CLI package when I'm on `master` and other times on `stable`. However, if my local package isn't activating, and I realize that I'm on `master`, even if I then switch to `stable`, the problem persists. The only way out seems to be to manually delete directories out of the pub cache.

**Comment by sigurdm** [comment]
This sounds like a bug. Not sure how it can happen.

Any help you can give with reproducing this would be nice.

If you could attach the output of running `dart pub --verbose global activate  --source=path .` in the case where it fails to update the activated version, that would be great.

**Comment by matthew-carroll** [comment]
Ok, I'll have to wait until it randomly happens again.

**Comment by eripoll** [comment]
I seem to have the same issue. 
`dart pub global activate --source path . `
```
Resolving dependencies... 
Downloading packages... 
  _fe_analyzer_shared 68.0.0 (72.0.0 available)
  analyzer 6.5.0 (6.7.0 available)
  macros 0.1.0-main.0 (0.1.2-main.4 available)
  very_good_analysis 5.1.0 (6.0.0 available)
Got dependencies!
4 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Package sfdk_cli is currently active at path ".../sfdk_cli".
Installed executable sfdk_cli.
Activated sfdk_cli 0.0.2 at path ".../sfdk_cli".
```
which is expected (except for the dependencies issues)

Run sfdk_cli --version
I get
`0.0.1`

The activate source doesn't seem to do anything anymore since I updated to Flutter latest stable version

**Comment by eripoll** [comment]
@sigurdm ⏫

**Comment by sigurdm** [comment]
Weird. The attached log says `MSG : Activated [1msfdk_cli[0m 0.1.0 at path "/Users/e******l/Dev/before/sfdk_cli".` not 0.0.2 as what you pasted... Also not 0.0.1 as you got in the version output.

Not sure what to make of this...

**Comment by eripoll** [comment]
Oh sorry, Yes let me explain. The log file I shared is from my actual package.
What I mentioned above was from a brand new project as I was trying to reproduce the bug in a blank project to see if I could reproduce. 
Sorry for not explaining this, @sigurdm

**Comment by sigurdm** [comment]
Sorry, I'm not following.

Did you manage to reproduce in the blank project?

**Comment by eripoll** [comment]
Yes I did, @sigurdm . No matter which project, whether a fully-fledged one or a blank one, I have the same issue.
Each time I activate, it stays on the previous version,

**Comment by matthew-carroll** [comment]
I just ran into this again. I discovered that I have to delete the `.dart_tool` directory within my CLI package to get it to build fresh.

When I delete the `.dart_tool` directory, and activate from source, the next invocation of my CLI command explicitly shows a recompilation:

```
Resolving dependencies in `/Users/admin/Projects/static_shock/static_shock/packages/static_shock_cli`... 
Downloading packages... 
Got dependencies in `/Users/admin/Projects/static_shock/static_shock/packages/static_shock_cli`.
Building package executable... (1.6s)
Built static_shock_cli:static_shock_cli.
```

If I don't delete the `.dart_tool` directory then the above build output isn't shown, and any new behaviors I added since the last activation doesn't exist in the binary.

Specifically, within the `.dart_tool` directory, deleting the `.snapshot` file is what makes the difference.

**Comment by SandPod** [comment]
We at Serverpod (and contributors to our framework) are experiencing the same issue.

This is usually my workaround:

On Mac, I can find out where the cached binary is stored by running:
```
$ which serverpod
-> /Users/alex/.pub-cache/bin/serverpod
$ cat /Users/alex/.pub-cache/bin/serverpod
-> 
#!/usr/bin/env sh
# This file was created by pub v3.5.1.
# Package: serverpod_cli
# Version: 2.1.0-beta.3
# Executable: serverpod
# Script: serverpod_cli
if [ -f /Users/alex/.pub-cache/global_packages/serverpod_cli/bin/serverpod_cli.dart-3.5.1.snapshot ]; then
  dart "/Users/alex/.pub-cache/global_packages/serverpod_cli/bin/serverpod_cli.dart-3.5.1.snapshot" "$@"
  # The VM exits with code 253 if the snapshot version is out-of-date.
  # If it is, we need to delete it and run "pub global" manually.
  exit_code=$?
  if [ $exit_code != 253 ]; then
    exit $exit_code
  fi
  dart pub -v global run serverpod_cli:serverpod_cli "$@"
else
  dart pub global run serverpod_cli:serverpod_cli "$@"
fi
```

And then manually remove the file `/Users/alex/.pub-cache/global_packages/serverpod_cli/bin/serverpod_cli.dart-3.5.1.snapshot`

**Comment by jsiedentop** [comment]
With macOs I have the same issue and would like to add more info.

I update my dart tool with, the following command, but it doesn't work.
```bash 
dart pub global activate --source path . --overwrite
```

When I run my tool it's actually a shell script, that will be executed and the content makes clear, that if there is a snapshot with the current dart version, the snapshot will be executed instead of the latest from the source directory. 

```bash
# /Users/<user>/.pub-cache/bin/<tool>
# The content of the script is
if [ -f /Users/<user>/src/<tool>/bin/main.dart-3.5.2.snapshot ]; then
  dart "/Users/<user>/src/<tool>/bin/main.dart-3.5.2.snapshot" "$@"
  # The VM exits with code 253 if the snapshot version is out-of-date.
  # If it is, we need to delete it and run "pub global" manually.
  exit_code=$?
  if [ $exit_code != 253 ]; then
    exit $exit_code
  fi
  dart pub -v global run <tool>:<tool> "$@"
else
  dart pub global run <tool>:<tool> "$@"
fi
```

Deleting the old snapshot was also by first approach, but it's also possible to run the tool via `dart pub global run <tool>:<tool>` to update the snapshot. 

So my current workaround to update the tool is:
```bash
dart pub global activate --source path . --overwrite
dart pub global run <tool>:<tool>
```

My guess why the bug does not always occur: After updating my dart vm, the first run on the tool will create a new snapshot. the second time. However, a second attempt to update the tool fails. I would expect, that `dart pub global activate` should always recreate the snapshot to make sure, that the latest changes will be applied.

**Comment by spideythewebhead** [comment]
I am having the same issue.

When I am running this command `dart pub global activate -s path .`

I am getting this and I am not able to call the cli executable

```
Resolving dependencies... 
Downloading packages... 
  js 0.7.1 (0.7.2 available)
  web 1.1.0 (1.1.1 available)
Got dependencies!
2 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information
```

What I noticed the `web` dependency was new (beforehand I was only getting the `js`).
Then I've tried running `dart pub upgrade` and the problem was resolved as it upgraded the `web` dependency and `dart pub global activate ...` completed successfully.

I can replicate this behavior consistently.. when I reverted the changes back it failed again

Also pinning the dependencies in `pubspec.yaml` helped to solve this too, as it changed the `pubspec.lock`

```
Dart SDK version: 3.6.2 (stable) (Wed Jan 29 01:20:39 2025 -0800) on "linux_x64"

Flutter 3.27.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d8a9f9a52e (4 weeks ago) • 2025-01-31 16:07:18 -0500
Engine • revision 82bd5b7209
Tools • Dart 3.6.2 • DevTools 2.40.
```


Adding my current pubspec.yaml/lock hopefully it can help

pubspec.yaml
```yaml
name: my_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  myexec:
```

pubspec.lock
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      sha256: dc27559385e905ad30838356c5f5d574014ba39872d732111cd07ac0beff4c57
      url: "https://pub.dev"
    source: hosted
    version: "80.0.0"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      sha256: "192d1c5b944e7e53b24b5586db760db934b177d4147c42fbca8c8c5f1eb8d11e"
      url: "https://pub.dev"
    source: hosted
    version: "7.3.0"
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: bf9f5caeea8d8fe6721a9c358dd8a5c1947b27f1cfaa18b39c301273594919e6
      url: "https://pub.dev"
    source: hosted
    version: "2.6.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "8aab1771e1243a5063b8b0ff68042d67334e3feab9e95b9490f9a6ebf73b42ea"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  convert:
    dependency: transitive
    description:
      name: convert
      sha256: b30acd5944035672bc15c6b7a8b47d773e41e2f17de064350988c5d02adb1c68
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
  coverage:
    dependency: transitive
    description:
      name: coverage
      sha256: e3493833ea012784c740e341952298f1cc77f1f01b1bbc3eb4eecf6984fb7f43
      url: "https://pub.dev"
    source: hosted
    version: "1.11.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      sha256: "1e445881f28f22d6140f181e07737b22f1e099a5e1ff94b0af2f9e4a463f4855"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.6"
  file:
    dependency: transitive
    description:
      name: file
      sha256: a3b4f84adafef897088c160faf7dfffb7696046cb13ae90b508c2cbc95d3b8d4
      url: "https://pub.dev"
    source: hosted
    version: "7.0.1"
  frontend_server_client:
    dependency: transitive
    description:
      name: frontend_server_client
      sha256: f64a0333a82f30b0cca061bc3d143813a486dc086b574bfb233b7c1372427694
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  glob:
    dependency: transitive
    description:
      name: glob
      sha256: c3f1ee72c96f8f78935e18aa8cecced9ab132419e8625dc187e1c2408efc20de
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      sha256: aa6199f908078bb1c5efb8d8638d4ae191aac11b311132c3ef48ce352fb52ef8
      url: "https://pub.dev"
    source: hosted
    version: "3.2.2"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  js:
    dependency: transitive
    description:
      name: js
      sha256: c1b2e9b5ea78c45e1a0788d29606ba27dc5f71f019f32ca5140f61ef071838cf
      url: "https://pub.dev"
    source: hosted
    version: "0.7.1"
  lints:
    dependency: "direct dev"
    description:
      name: lints
      sha256: c35bb79562d980e9a453fc715854e1ed39e24e7d0297a880ef54e17f9874a9d7
      url: "https://pub.dev"
    source: hosted
    version: "5.1.1"
  logging:
    dependency: transitive
    description:
      name: logging
      sha256: c8245ada5f1717ed44271ed1c26b8ce85ca3228fd2ffdb75468ab01979309d61
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: dc58c723c3c24bf8d3e2d3ad3f2f9d7bd9cf43ec6feaa64181775e60190153f2
      url: "https://pub.dev"
    source: hosted
    version: "0.12.17"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: e3641ec5d63ebf0d9b41bd43201a66e3fc79a65db5f61fc181f04cd27aab950c
      url: "https://pub.dev"
    source: hosted
    version: "1.16.0"
  mime:
    dependency: transitive
    description:
      name: mime
      sha256: "41a20518f0cb1256669420fdba0cd90d21561e560ac240f26ef8322e45bb7ed6"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
  node_preamble:
    dependency: transitive
    description:
      name: node_preamble
      sha256: "6e7eac89047ab8a8d26cf16127b5ed26de65209847630400f9aefd7cd5c730db"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      sha256: "92d4488434b520a62570293fbd33bb556c7d49230791c1b4bbd973baf6d2dc67"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  pool:
    dependency: transitive
    description:
      name: pool
      sha256: "20fe868b6314b322ea036ba325e6fc0711a22948856475e2c2b6306e8ab39c2a"
      url: "https://pub.dev"
    source: hosted
    version: "1.5.1"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "7b3cfbf654f3edd0c6298ecd5be782ce997ddf0e00531b9464b55245185bbbbd"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.5"
  shelf:
    dependency: transitive
    description:
      name: shelf
      sha256: e7dd780a7ffb623c57850b33f43309312fc863fb6aa3d276a754bb299839ef12
      url: "https://pub.dev"
    source: hosted
    version: "1.4.2"
  shelf_packages_handler:
    dependency: transitive
    description:
      name: shelf_packages_handler
      sha256: "89f967eca29607c933ba9571d838be31d67f53f6e4ee15147d5dc2934fee1b1e"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
  shelf_static:
    dependency: transitive
    description:
      name: shelf_static
      sha256: c87c3875f91262785dade62d135760c2c69cb217ac759485334c5857ad89f6e3
      url: "https://pub.dev"
    source: hosted
    version: "1.1.3"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      sha256: "3632775c8e90d6c9712f883e633716432a27758216dfb61bd86a8321c0580925"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  source_map_stack_trace:
    dependency: transitive
    description:
      name: source_map_stack_trace
      sha256: c0713a43e323c3302c2abe2a1cc89aa057a387101ebd280371d6a6c9fa68516b
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      sha256: "190222579a448b03896e0ca6eca5998fa810fda630c1d65e2f78b3f638f54812"
      url: "https://pub.dev"
    source: hosted
    version: "0.10.13"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "254ee5351d6cb365c859e20ee823c3bb479bf4a293c22d17a9f1bf144ce86f7c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "8b27215b45d22309b5cddda1aa2b19bdfec9df0e765f2de506401c071d38d1b1"
      url: "https://pub.dev"
    source: hosted
    version: "1.12.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: "969e04c80b8bcdf826f8f16579c7b14d780458bd97f56d107d3950fdbeef059d"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: "7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: "301b213cd241ca982e9ba50266bd3f5bd1ea33f1455554c5abb85d1be0e2d87e"
      url: "https://pub.dev"
    source: hosted
    version: "1.25.15"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: fb31f383e2ee25fbbfe06b40fe21e1e458d14080e3c67e7ba0acfde4df4e0bbd
      url: "https://pub.dev"
    source: hosted
    version: "0.7.4"
  test_core:
    dependency: transitive
    description:
      name: test_core
      sha256: "84d17c3486c8dfdbe5e12a50c8ae176d15e2a771b96909a9442b40173649ccaa"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.8"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: ddfa8d30d89985b96407efce8acbdd124701f96741f2d981ca860662f1c0dc02
      url: "https://pub.dev"
    source: hosted
    version: "15.0.0"
  watcher:
    dependency: transitive
    description:
      name: watcher
      sha256: "69da27e49efa56a15f8afe8f4438c4ec02eff0a117df1b22ea4aad194fe1c104"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: cd3543bd5798f6ad290ea73d210f423502e71900302dde696f8bff84bf89a1cb
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  web_socket:
    dependency: transitive
    description:
      name: web_socket
      sha256: "3c12d96c0c9a4eec095246debcea7b86c0324f22df69893d538fcc6f1b8cce83"
      url: "https://pub.dev"
    source: hosted
    version: "0.1.6"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      sha256: "0b8e2457400d8a859b7b2030786835a28a8e80836ef64402abef392ff4f1d0e5"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
  webkit_inspection_protocol:
    dependency: transitive
    description:
      name: webkit_inspection_protocol
      sha256: "87d3f2333bb240704cd3f1c6b5b7acd8a10e7f0bc28c28dcf14e782014f4a572"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  yaml:
    dependency: transitive
    description:
      name: yaml
      sha256: b9da305ac7c39faa3f030eccd175340f968459dae4af175130b3fc47e40d76ce
      url: "https://pub.dev"
    source: hosted
    version: "3.1.3"
sdks:
  dart: ">=3.6.2 <4.0.0"
```
