### ISSUE TITLE
Re-introduce Flutter SDK constraint upper-bound

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#4310]
At the Flutter 2.0.0 release it was determined that Flutter did not follow semantic versioning, and for this reason the upper-bound SDK constraint on Flutter should be ignored.

Hence,
```yaml

**Comment by jonasfj** [comment]
Discussing this offline, it appears that while this could be a tiny improvement, it might not be worth the squeeze.

What we really want is probably more like:
```yaml
name: mypkg
api:
  dart: 3.5.0 # indicating that we want the language version and API shipped in 3.5
```

Of course that leads down the road of designing API versioning.
