### ISSUE TITLE
Pub Workspace: only require paths at workspace level?

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/pub#4318]
In flutter/engine/pull/53539, you see in sub-workspace yaml files we have to specify the paths: flutter/engine/tools/engine_tool/pubspec.yaml:
* litetest and process_fakes both have relative paths.
* but they are both listed at the root workspace.

To make the sub-workspace yaml files more concise (and easier to maintain), can we leave the `path:` out of the sub files?

**Comment by sigurdm** [comment]
It is a bit unclear what you are trying.

But perhaps you can leave the `path` out from the sub-package, and only define it in a dependency_override in the root.

**Comment by matanlurey** [comment]
The idea we had was:

```yaml
# root/pubspec.yaml
dependencies:
  repo_private_dependency:
    path: tools/pkg/repo_private_dependency

# root/tools/pkg/some_other_dep/pubspec.yaml
dependencies:
  repo_private_dependency:
```

That doesn't work, because `repo_private_dependency` is not found on pub.dev.

**Comment by sigurdm** [comment]
Try
```yaml
# root/pubspec.yaml
dependency_overrides:
  repo_private_dependency:
    path: tools/pkg/repo_private_dependency

# root/tools/pkg/some_other_dep/pubspec.yaml
dependencies:
  repo_private_dependency:
```
