### ISSUE TITLE
Surface supported architectures per OS

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#4367]
We should consider surfacing the supported hardware architectures on pub per OS.

And there are more things we could report, such as the minimum supported SDK version for Android, iOS, and MacOS.

We have two options:

1. Declare them in the pubspec
2. Invoke the build hook to list supported inf

### 1. List in the pubspec

@jonasfj I'm 100% sure we've talked about this before, but I can't find a tracking issue. I'm pretty sure we also already had a sketch for the pubspec.

```yaml
platforms:
  android:
    architectures:
      - arm64
      - x64 # simulator
    minimum-sdk: 123
  ios:
    architectures:
      - ...
```

Pros:

* Declarative.

Cons:

* Could get out of sync with the build hook.

### 2. Let the hook report it

Pros:

* Most hook implementations would use one helper to both report the supported archs as well as produce the native code assets.

Cons:

* Requires invoking a script (in a sandbox) in order to get the info.
