### ISSUE TITLE
Pub workspaces confusing message when duplicate entries in workspace

### ISSUE THREAD

**Issue by orestesgaolin** [dart-lang/pub#4380]
# Environment

- Dart version 3.6.0 (build 3.6.0-239.0.dev)
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macOS

# Problem

I added the same package twice to my workspace definition and following error has been shown when running `flutter pub get` in the root:

```
Packages can only be included in the workspace once.

`./packages/permissions_repository/pubspec.yaml` is included in the workspace, both from:
* `./pubspec.yaml` and
* ./pubspec.yaml.
Failed to update packages.
```

pubspec.yaml snippet: 

```yaml
name: app
version: 24.9.3
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.2"

workspace:
  - packages/something
  - packages/permissions_repository
  - packages/something_else
  - packages/permissions_repository
...
```

## Expected behavior

I would expect to tell me that the package is included in pubspec.yaml twice without showing the same file twice. It gave an impression that there are 2 pubspec files affected.

## Actual behavior

As above

## --trace output

n/a
