### ISSUE TITLE
Dependency override in pubspec.yaml ignored when pubspec_overrides.yaml exists

### ISSUE THREAD

**Issue by scopendo** [dart-lang/pub#4387]
# Environment

- Dart version: 3.5.2
- OS kind and version: macOS 14.6.1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

We commonly use a `pubspec_overrides.yaml` file during development to set a relative path to internal packages (in different repositories) that our app depends on, leaving the `pubspec.yaml` set to a git URL to not break builds on our CI server.  We don't commit `pubspec_overrides.yaml`.

Occasionally, we use the `dependency_overrides` section of the `pubspec.yaml` to force a later version of a third-party dependency, which is needed on our CI server.  This override is ignored by `dart pub get|upgrade` unless it is repeated in the `pubspec_overrides.yaml` file.  This is cumbersome and can be error-prone.

<details>

<summary>pubspec.yaml</summary>

```yaml
name: example
description: Example App
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ...
  firebase_core: ^2.32.0

  flutter:
    sdk: flutter

  example_common:
    git:
      url: ssh://git@bitbucket.org/example/example-common.git
      ref: v1.0.0
   ...

dependency_overrides:
  # This override will be ignored if it's not specified in pubspec_overrides.yaml
  firebase_core: ^3.2.0
```

</details>

<details>

<summary>pubspec_overrides</summary>

```yaml
dependency_overrides:
  example_common:
    path: ../example_common

  # The override of firebase_core in pubspec.yaml will be ignored unless also specified here
  firebase_core: ^3.2.0
```

</details>

## Expected behavior

I expected that the dependency overrides in `pubspec_overrides.yaml` would complement overrides in `pubspec.yaml`.

## Actual behavior

The dependency overrides in `pubspec.yaml` are ignored.
