### ISSUE TITLE
Ability to host dependencies inside the package

### ISSUE THREAD

**Issue by MohiuddinM** [dart-lang/pub#4412]
Right now we can not add git or path dependencies inside published packages. This creates a lot of additional effort, as all internal dependencies have to be published separately. This may even require additional tooling etc.

A simpler solution will be to allow hosting dependencies inside the parent package. Let's say we create a _packages_ folder at the same level as the _lib_ folder. Then, any package inside this _packages_ folder can be declared as path dependencies inside the parent package without any problem.

An even better solution will be to allow specifying git and path dependencies as internally hosted in _pubspec.yaml_ of the parent package, and then _pub_ will handle everything internally. It can look like this:

```
name: parent_package

environment:
  sdk: ^3.0.0

dependencies:
  dep_1:
    path: ../packages/dep_1
    host_internally: true
  dep_2:
    git: <URL of git repo>
    host_internally: true
```

So, with these solutions implemented we won't have to waste time handling sub-dependencies and integrating additional tooling, and _pub_ would handle everything in the background.
