### ISSUE TITLE
Forbid unknown keys in dependency descriptions

### ISSUE THREAD

**Issue by Jannik-dev** [dart-lang/pub#4444]
# Environment

- Dart version: `3.5.4`

# Problem

I recently discovered that `pub get` worked fine when the version constraint on a hosted package has a wrong indentation.

This is my example `pubspec.yaml` (version is indented too much), it essentially acts like no version is specified, which could be quite tricky to track down when the project gets older:
```yaml
dependencies:
  plugin_platform_interface:
    hosted:
      url: https://pub.dev
      version: 2.1.3
```

When using the [pubspec_parse](https://pub.dev/packages/pubspec_parse) (version `1.3.0`) an error is thrown which I would expect from `pub get` as well.

## Expected behavior

An exception is thrown that there are characters which aren't in used during parsing or that the version has the wrong indentation.

## Actual behavior

`pub get` acts like the version line does not exist.
