### ISSUE TITLE
Pub error

### ISSUE THREAD

**Issue by MalikAreeb** [dart-lang/pub#4457]
# Environment

- Dart version (run `dart --version`):
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):
- Are you using the Chinese community mirror or a corporate firewall?

# Problem

```yaml
name: sing_with_me
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.1
  get_it: ^8.0.0
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.0.5
  top_snackbar_flutter: ^3.1.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  uni_links5: ^0.5.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic



```

## --trace output

```
Null check operator used on a null value
package:pub/src/source/hosted.dart 778:33                       HostedSource._getAdvisories.readAdvisoriesFromCache
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 796:12                       HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1084:24                      HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 416:26                       SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 220:18                       SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 75:21                        SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 580:5                           Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 76:5                           GetCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                              PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                         CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 236:18                             DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 47:16                              runDartdev
===== asynchronous gap ===========================
/Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:5  main
This is an unexpected error. The full log and other details are collected in:

    /Users/areebmalik/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```
