### ISSUE TITLE
add 'generate: true' to support in workspaces

### ISSUE THREAD

**Issue by abikko** [dart-lang/pub#4471]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 3.6.0 (stable) (Thu Dec 5 07:46:24 2024 -0800) on "macos_arm64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macOS 15.1.1
- Are you using the Chinese community mirror or a corporate firewall? - No

# Problem

Currently, I have project which currently is using intl package, 

and I generate messages from arb using the command 'flutter gen-l10n' with generate: true

but when I trying to run 'flutter pub get' in workspace - terminal giving me error '`generate: true` is not supported within workspaces.'

So, I removed 'generate: true' in pubspec.yaml, and I have another error: 
"Attempted to generate localizations code without having the flutter: generate flag turned on.
Check pubspec.yaml and ensure that flutter: generate: true has been added and rebuild the project. Otherwise, the localizations source code will not be importable."

```yaml
name: admin
description: New Admin on Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
```

## Expected behavior

Generate AppLocalizations - dart class

## Actual behavior

Giving error 
"Attempted to generate localizations code without having the flutter: generate flag turned on.
Check pubspec.yaml and ensure that flutter: generate: true has been added and rebuild the project. Otherwise, the localizations source code will not be importable."
