### ISSUE TITLE
Declaring a git dependency in the root package of a workspace doesn't work as expected

### ISSUE THREAD

**Issue by Pacane** [dart-lang/pub#4496]
# Environment
```
λ ~/code/dart/mono_repo_test/ main dart --version
Dart SDK version: 3.6.1 (stable) (Tue Jan 7 09:50:00 2025 -0800) on "macos_x64"
```

# Problem

I'm using pub workspaces, and I'm facing an issue.

When I declare a git dependency in my root package, and reference it in a child package, I get an error when doing `flutter pub get`.

[Here's a sample project that highlights the issue.](https://github.com/Pacane/mono_repo_repro)

root pubspec.yaml
```yaml
name: _
environment:
  sdk: ^3.6.1
workspace:
- package1
- package2
- app
dependencies:
  args: ^2.6.0
  freezed_annotation: ^2.4.4
  cupertino_icons: ^1.0.8
  phoenix_socket: 
    git:
      url: https://github.com/braverhealth/phoenix-socket-dart
      ref: 4c3f76476cb846c1bcf92272952162f52af25c86

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  build_runner: ^2.4.14
  freezed: ^2.5.8
```

leaf package:
```yaml
name: package2
description: A sample command-line application with basic argument parsing.
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  args:
  phoenix_socket:

dev_dependencies:
  lints:
  test:
```

## Expected behavior
pub get completes properly

## Actual behavior
Getting this error message:
```
λ ~/code/dart/mono_repo_test/ main* flutter pub get
Resolving dependencies... 
Because package2 depends on phoenix_socket from hosted and _ depends on phoenix_socket from git, version solving failed.
Failed to update packages.
```

One thing I noticed is that I can work around the issue by
- explicitly add the git dependency url/path/refs to the child pubspec files.
- adding a dependency_override in the root pubspec file.

Is that expected behaviour? To me, those work arounds seem a bit counter-productive with the concept of pub workspaces.
