### ISSUE TITLE
Features export like in Cargo in Rust.

### ISSUE THREAD

**Issue by shigomany** [dart-lang/pub#4528]
## Description

Hello everyone! I would like to propose a functionality similar to that in the Cargo package manager in Rust ([description](https://doc.rust-lang.org/cargo/reference/features.html)). This solution allows you to turn on or off a part of your package's functionality, and also, depending on the enabled feature, enable a dependency (but in general, I think you can do without this functionality).

## Proposal

I want suggest to `features` in **pubspec.yaml** like this:

```yaml

dependencies:
   my_awesome_dependency:
      version: ^1.0.0
      features:
         - add
         - sub
```

Inside in `my_awesome_dependency` in **pubspec.yaml**. I think it's necessary for analyzer and json schema.

```yaml
dependencies:
   ...

features:
   - add
   - sub
```

Features are simply string lines that configure what code will ultimately be available; this can be done through the mechanism of annotations to export files.

```dart
library;

@Feature('add')
export 'src/add.dart';

@Feature('sub')
export 'src/sub.dart';
```

## About issue

I didn't find another issues about it. I understand that in general it is possible to turn on and off part of the functionality via `bool.fromEnviroment`, which will subsequently be filtered out by the `Tree Shaking` mechanism (because it's const values), but this is need configure from project to project.
