### ISSUE TITLE
[FR] Improves how we resolves packages between different hosts

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub#4534]
I'm using our cn mirror (`pub.flutter-io.cn`) when developing some projects that don't use the mirror and have a lock file with `pub.dev` resolved.

Now, say we have `package:a` that has version 1.0.0 and 1.1.0 that can both be resolved with the current project, the lock file specified `package:a` resolved as version 1.0.0 from `pub.dev` host. When I run `pub get` and after it finishes, the resolved version becomes 1.1.0 along with the changed host `pub.flutter-io.cn`.

Before:
```yaml
a:
  dependency: "direct main"
  description:
    name: a
    sha256: abcdef
    url: "https://pub.dev"
  source: hosted
  version: "1.0.0"
```

After:
```yaml
a:
  dependency: "direct main"
  description:
    name: a
    sha256: fedcba
    url: "https://pub.flutter-io.cn"
  source: hosted
  version: "1.1.0"
```

I'd raise at least 3 unexpected behaviors:
1. Changing hosts should not lead to version changes, unless the previous ref cannot be resolved in the new host. I wouldn't expect to have an upgrade behavior when I was changing the host.
2. `package > description > url` should be removed or only present when explicitly specified. The `sha256` has already covered the identification of the resolved package, we don't need a host to identify. There is a related improvement that takes place in other popular package management tools: pnpm. See https://github.com/pnpm/pnpm/releases/tag/v10.0.0
3. You don't need `package > description > name`, it's redundant nowadays.

## Expected results

My idea about `pubspec.lock`:

**Host-based ref**
<table>
<tr>
<td> pubspec.yaml </td> <td> pubspec,lock </td>
</tr>
<tr>
<td>

```yaml
a: ^1.0.0
```

</td>
<td>

```yaml
a:
  dependency: "direct main"
  description:
    sha256: abcdef
  source: hosted
  version: "1.0.0"
```

</td>
</tr>
<tr>
<td>

```yaml
a:
  hosted: https://pub.flutter-io.cn
  version: ^1.0.0
```

</td>
<td>

```yaml
a:
  dependency: "direct main"
  description:
    sha256: abcdef
    url: https://pub.flutter-io.cn
  source: hosted
  version: "1.0.0"
```

</td>
</tr>
</table>
