### ISSUE TITLE
Running globally activated package attempts to upgrade a dependency and ignores lockfile

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/pub#4536]
# Environment

- Dart version (run `dart --version`): `Dart SDK version: 3.6.2 (stable) (Wed Jan 29 01:20:39 2025 -0800) on "macos_arm64"`
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macOS 15.3.1
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

I have a project within which a `dart pub get` is successful and prints the following:

```console
Resolving dependencies... 
Downloading packages... 
  _fe_analyzer_shared 76.0.0 (80.0.0 available)
  analyzer 6.11.0 (7.3.0 available)
  built_value 8.9.4 (8.9.5 available)
  dart_style 2.3.8 (3.0.1 available)
  js 0.7.1 (0.7.2 available)
! taconic_annotation 0.0.1 from path ../taconic_annotation (overridden in ./pubspec_overrides.yaml)
```

I can activate it using `dart pub global activate --source="path" .` successfully which prints:

```console
Resolving dependencies in `taconic`... 
Downloading packages... 
  _fe_analyzer_shared 76.0.0 (80.0.0 available)
  analyzer 6.11.0 (7.3.0 available)
  built_value 8.9.4 (8.9.5 available)
  dart_style 2.3.8 (3.0.1 available)
  js 0.7.1 (0.7.2 available)
! taconic_annotation 0.0.1 from path taconic_annotation (overridden in taconic/pubspec_overrides.yaml)
Got dependencies in `taconic`!
5 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Package taconic is currently active at path "/Users/brandontrautmann/Development/mobile/flutter/taconic".
Installed executable taconic.
Activated taconic 0.0.1 at path "/Users/brandontrautmann/Development/mobile/flutter/taconic".
```

However, when I invoke that executable, I get the following error:

```console
Downloading packages... . 
  _fe_analyzer_shared 76.0.0 (80.0.0 available)
  analyzer 6.11.0 (7.3.0 available)
> built_value 8.9.5 (was 8.9.4)
  dart_style 2.3.8 (3.0.1 available)
  js 0.7.1 (0.7.2 available)
! taconic_annotation 0.0.1 from path taconic_annotation (overridden in /Users/brandontrautmann/Development/mobile/flutter/taconic/pubspec_overrides.yaml)
Would change 1 dependency in `/Users/brandontrautmann/Development/mobile/flutter/taconic`.
4 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
The current activation of `taconic` cannot resolve to the same set of dependencies.

Try reactivating the package.
`dart pub global activate taconic`
```

I understand the output, but don't understand why I am able to successfully `pub get` _and_ activate the package, but running it causes an additional download and an attempt to change previously locked dependency constraints. Is this a bug or a misunderstanding on my part?

`taconic/pubspec.yaml`:

```yaml
name: taconic
description: Command line application for exporting mobile routes.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ^6.8.0
  args: ^2.4.2
  collection: ^1.18.0
  dart_style: ^2.3.6
  equatable: ^2.0.7
  file: ^7.0.0
  json_annotation: ^4.9.0
  optional: ^6.1.0+1
  taconic_annotation:
    path: ../taconic_annotation
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.7.1
  test: ^1.25.7

executables:
  taconic: taconic
```

`taconic_annotation/pubspec.yaml`:

```yaml
name: taconic_annotation
description: Annotations that support route introspection via the `taconic` CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
```

## Expected behavior

A package that successfully `pub get`s and successfully activates can be run.

## Actual behavior

The package successfully `pub get`s and successfully activates but fails to run.
