### ISSUE TITLE
'dart pub global activate -s path <path>' does not work with Dart workspace

### ISSUE THREAD

**Issue by christerswahn** [dart-lang/pub#4553]
# Environment

- Dart version (run `dart --version`): Dart SDK version: 3.7.2 (stable)
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macos_arm64, version 15.3.1
- Are you using the Chinese community mirror or a corporate firewall? no

# Problem

When using Dart workspace for a monorepo where a package has an executable, the command `dart pub global activate -s path <path>` does not work.

It does not work regardless of which current directory it is run from.

The workspace root pubspec:
```yaml
name: my_monorepo
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: 3.29.0

workspace:
  - packages/lints
  - packages/my_cli
```

The pubspec of the cli package that has an executable:
```yaml
name: my_cli
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  args: ^2.6.0

dev_dependencies:
  test: ^1.24.0

executables:
  mycli: mycli
```

## Expected behavior

Output from the activate command with workspace disabled in the my_cli package:
```bash
Package serverpod_cloud_cli is currently active at path "/Users/<user>/dev/cloud/workspace/packages/my_cli".
Installed executable mycli.
Activated mycli 1.0.0 at path "/Users/<user>/dev/cloud/workspace/packages/my_cli".```
```

mycli is activated and accessible via the shell path.

## Actual behavior

Output from the activate command:
```bash
Package my_monorepo is currently active at path "/Users/<user>/dev/cloud/workspace".
Activated my_monorepo 0.0.0 at path "/Users/<user>/dev/cloud/workspace".
```

mycli is not activated.

## --trace output

```
<copy/paste the full output>
```

`dart pub global activate` does not seem to support `--trace`.
