### ISSUE TITLE
Pub fails to resolve version constraints when it should be able to

### ISSUE THREAD

**Issue by xavierchanth** [dart-lang/pub#4603]
# Environment

My current Flutter/Dart version:
```
Flutter 3.32.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8defaa71a7 (7 days ago) • 2025-06-04 11:02:51 -0700
Engine • revision 1091508939 (12 days ago) • 2025-05-30 12:17:36 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1
```

# Problem

In the pubspec below, you will see two dependencies of interest.
`at_onboarding_flutter` which has `intl: ^0.19.0` in it's pubspec.yaml's dependencies map.

Secondly, under dev_dependencies in the pubspec below, you will see `flutter_test`.
`flutter_test` has pinned `intl: 0.20.2`.

This is causing resolution of the dependencies to fail. Yes, I can put `intl: 0.20.2` into overrides, but I shouldn't have to. Version resolution of a transitive dependency should never need an explicit override just for it to resolve where there is a compatible version between all transitive dependency graphs. When look at the constraints of:

`0.20.2` and `^0.19.0`, this very clearly resolves to a single version, `0.20.2` which qualifies for both , and yet pub tells me this:

```
flutter pub get
Resolving dependencies... (1.5s)
Note: intl is pinned to version 0.20.2 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of at_onboarding_flutter from git depends on intl ^0.19.0 and every version of
  flutter_localizations from sdk depends on intl 0.20.2, at_onboarding_flutter from git is incompatible with
  flutter_localizations from sdk.
So, because npt_flutter depends on both flutter_localizations from sdk and at_onboarding_flutter from git, version
  solving failed.
Failed to update packages.
```

First of all, they most definitely are compatible constraints, but also, why are dev_dependencies resolved in the same graph as main dependencies, when they aren't even used in the same contexts? I'd be curious to hear a case where resolving them in the same graph makes sense, if one exists.

pubspec.yaml:
```yaml
name: npt_flutter
description: "NoPorts Desktop app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.3.0+16
msix_config:
  # removed details as it is irrelevant to the issue
  # ...

environment:
  sdk: ^3.5.0

dependencies:
  adaptive_theme: ^3.6.0
  at_auth: ^2.0.7
  at_backupkey_flutter: ^4.0.16
  flutter_gen_runner:
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client_mobile
      ref: 8e8b68d2f00db0aeca266685be1e9c0b103ad301
  at_contact: ^3.0.8
  at_contacts_flutter: ^4.0.15
  at_onboarding_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: packages/at_onboarding_flutter
  at_server_status: ^1.0.5
  at_utils: ^3.0.16
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.15.0
  noports_core:
    path: ../noports_core
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.4
  phosphor_flutter: ^2.1.0
  pin_code_fields: ^8.0.1
  socket_connector: ^2.3.3
  toml: ^0.16.0
  tray_manager: ^0.2.3
  url_launcher: ^6.3.0
  uuid: ^3.0.7
  visibility_detector: ^0.4.0+2
  window_manager: ^0.4.2
  yaml: ^3.1.2
  yaml_writer: ^2.0.0
dev_dependencies:
  build_runner: ^2.4.12
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  msix: ^3.16.8

dependency_overrides:
  device_info_plus: 11.3.3
  file: 7.0.1
  meta: 1.15.0
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args
  at_onboarding_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets
      ref: at_onboarding_flutter_layers
      path: packages/at_onboarding_flutter
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk
      ref: 533f657eec18f13a11dafbf67c0006c6cc010dde
      path: packages/at_client_mobile
  flutter_lints: ^4.0.0

flutter:
  # removed as it is irrelevant
```

## Expected behavior

flutter pub get resolves my intl version to 0.20.2.

## Actual behavior

flutter pub get fails to resolve intl version.
