### ISSUE TITLE
Custom keys in pubspec are now throwing errors

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/pub#4613]
# Environment

Dart 3.8

# Problem

```console
% dart pub get
Error on line 18, column 7 of pubspec.yaml: Invalid description in the "[redacted]" pubspec on the "custom_lint" dependency: Unknown key "prs" in description.
   ╷
18 │ ┌       prs:
19 │ │         - asdf
20 │ │       url: https://github.com/Rexios80/dart_custom_lint
21 │ │       ref: 2f0abfad2dee2f5dba2df4999cbd04b72de6b711
22 │ └       path: packages/custom_lint
   ╵
```

This custom key is used by https://pub.dev/packages/git_dependency_prs to track the state of dependencies

```yaml
dependency_overrides:
  flutter_secure_storage: ^10.0.0-beta.4
  custom_lint:
    git:
      prs:
        - asdf
      url: https://github.com/Rexios80/dart_custom_lint
      ref: 2f0abfad2dee2f5dba2df4999cbd04b72de6b711
      path: packages/custom_lint
```

## Expected behavior

This didn't used to crash

## Actual behavior

It crashes

**Comment by sigurdm** [comment]
This is not a crash but intended behavior.
It was added in https://github.com/dart-lang/pub/pull/4458

I can see that it conflicts with that specific use-case. But I think the benefits (catching mistyped properties) outweigh the damage here.

If you are in charge of the [git_dependency_prs](https://pub.dev/packages/git_dependency_prs) tool, consider changing it to use a separate top-level property in the pubspec.

Perhaps something along the lines of

```yaml
dependencies:
    custom_lint:
      git:
        url: https://github.com/Rexios80/dart_custom_lint
        ref: 2f0abfad2dee2f5dba2df4999cbd04b72de6b711
        path: packages/custom_lint

git_dependency_prs:
  custom_lint:
      prs:
        - asdf
```
